### ISSUE TITLE
What does the index parameter of the `addSeries` and `addBand` methods represent?

### ISSUE THREAD

**Issue by thedanchez** [leeoniya/uPlot#1007]
Hello! Thank you so much for making uPlot. Incredible library that you have made here. 

I just have a question about the `addSeries` and `addBand` methods on the chart -- specifically the second index argument. In one of your demo examples [here](https://leeoniya.github.io/uPlot/demos/add-del-series.html) that is dynamically adding/deleting series, I noticed in the [code](https://github.com/leeoniya/uPlot/blob/master/demos/add-del-series.html#L74) for it that you have a set a fixed series index and yet the demo shows the series being added/deleted with no problems.

Was wondering if you would be able to shed light on the purpose of that index argument?

**Comment by leeoniya** [comment]
the index is just the position where the new series or band should be inserted. internally they use `Array.splice()`, so it gets passed straight through.

https://github.com/leeoniya/uPlot/blob/f98d1d34d92a128f18fbaac9293910eed85ea19c/src/uPlot.js#L2463

the demo has a hard-coded index of 2, so it always adds and deletes series in the third array position. this array is "live", so after deleting at index 2, the series that was previously at index 3 moves into position 2.

for bands the position doesnt really matter since they're only drawn on the canvas. for series the position may matter if you want the new series to be in a specific order in the legend. if you dont care, you can omit the index in both cases and it should just append to the end.
