### ISSUE TITLE
Large numbers don't work

### ISSUE THREAD

**Issue by dgl** [leeoniya/uPlot#102]
http://dg.cx/uplot-large-numbers.html with `20000000000` doesn't work, but `10000000000` does.

**Comment by leeoniya** [comment]
looks like the largest numeric divisor [1] is still too small to create a ticks at the minimum vertical spacing (40px)

https://github.com/leeoniya/uPlot/blob/1513290f6276c148e083a7c5d1412bf425870209/src/opts.js#L284-L286

you can provide your own `incrs` divisor array to the y axis. or we can generate this array dynamically rather than it being hard-coded internally. (it's 1,2,5 multiples at each magnitude). i'm not too eager to hard-code more.

**Comment by leeoniya** [comment]
we could be smarter and more efficient about it, similar to what `rangeNum()` [1] does

```js
function findNumIncr(valDelta, dim, minSpace) {
  let min = valDelta/dim * minSpace;
  let mag = Math.floor(Math.log10(min));
  let base = Math.pow(10, mag + 1);
  
  let m = [.1,.2,.5,1];
  
  for (let i = 0; i < m.length; i++) {
    let incr = base * m[i];

    if (incr >= min)
      return incr;
  }
}


findNumIncr(.543, 547, 40);
findNumIncr(100, 547, 40);
findNumIncr(22000000000, 547, 40);
```

[1]
https://github.com/leeoniya/uPlot/blob/1513290f6276c148e083a7c5d1412bf425870209/src/utils.js#L55

**Comment by leeoniya** [comment]
i decided to go with the generator approach, and simply increased the top and bottom ends of the numeric divisors array.

using the more interesting solution from my previous comment opens up a can of worms, since it breaks the uniform solution for indexed, time and numeric scales. this reduces the ability to re-use code and introduces more difficulties around absorbing obvious divisor arrays via the opts.

realistically, if you have a values of 22000000000, the only thing that matters is probably the first 3-4 digits and the number of zeros; there's a reason you didn't give me 22123123123 as an example :). i expect that data at those magnitudes to come in as small floats with a pre-determined multiples, and be formatted similarly, eg 2.2e10.

**Comment by leeoniya** [comment]
i've also added parameters to the `incrs` generator, so if you really need arbitrarily large numbers, you now have all the data to make your own:

```js
let xs = [1,2];

let data = [
  xs,
  xs.map((t, i) => 2e26), // change to 10000000000 and it'll work
];

const opts = {
  width: 1920,
  height: 600,
  title: "Area Fill",
  scales: {
    x: {
      time: false,
    },
  },
  series: [
    {},
    {
      color: "red",
      fill: "rgba(255,0,0,0.1)",
    },
  ],
  axes: [
    {},
    {
      incrs: (self, scMin, scMax, plotDim, minSpace) => {
        const mults = [.1,.2,.5,1];

        let base = (scMax - scMin)/plotDim * minSpace;
        let mag = Math.floor(Math.log10(base));
        let next = Math.pow(10, mag + 1);

        for (let i = 0; i < mults.length; i++) {
          let incr = next * mults[i];

          if (incr >= base)
            return [incr];
        }
      }
    },
  ],
};

let u = new uPlot.Line(opts, data, document.body);
```
