### ISSUE TITLE
Stable release, or versioning

### ISSUE THREAD

**Issue by cyljacky** [leeoniya/uPlot#125]
Hello, 
Is there any stable version marked along the history of repository?
As I tried to access the bench page at around Dec, 2019(or Jan, 2020, maybe?) and the graph cannot be generated. 
This makes me hesitate to use the repo into my projects.

**Comment by leeoniya** [comment]
hey @cyljacky 

there's no stable release yet.

i'm still considering moving the axes & ticks from the dom to canvas to reduce the amount of dom required per chart - there are users with a hundred uplot charts per page. this *could* be a breaking change in terms of css theming (e.g. things like `axis.class` would be replaced by more limited options for tick font styling).

the docs still need work. i think i may move them out of the readme to a wiki page to avoid tagging 1.0 with half-finished docs. the demos are the de-facto docs for now.

so, i cannot yet provide an absolute guarantee that nothing will break, but most potential breaks should be easy to adjust to. i can tell you that no large, conceptual changes will happen at this point.

i would encourage you to prototype your use case, since a lot of api refinement is a direct result of people actually trying the lib and opening issues/suggestions - that's the way to avoid and be stuck maintaining a sloppy 1.x.

**Comment by leeoniya** [comment]
gonna close this in favor of #131. there should be stable release in a week or so.

**Comment by leeoniya** [comment]
1.0.0 is tagged and published:

https://github.com/leeoniya/uPlot/releases/tag/1.0.0
https://www.npmjs.com/package/uplot
