### ISSUE TITLE
Onclick Plugin

### ISSUE THREAD

**Issue by GatCode** [leeoniya/uPlot#128]
Hello,
I am struggling to find a solution on how to select points via a mouseclick.

As you can see in the image below, the user should be able to select two points from the x axis.
![original](https://user-images.githubusercontent.com/19287308/74585676-925b9c00-4fdf-11ea-8453-ba8e3b467737.jpg)

And the result should be a new plot which sould look something like this, where only the two selected points are considered.
![interpolated](https://user-images.githubusercontent.com/19287308/74585677-94bdf600-4fdf-11ea-9efe-46b1a10d2271.jpg)

Can someone help me out?

**Comment by leeoniya** [comment]
hey @GatCode ,

there are a lot of ways to get this done and the strategy depends on exactly the behavior you need. from your examples, it looks like you're wanting this to work in conjunction with zooming, so i'll work off that.

if you're okay leaving the original trend data on the plot, and just drawing trendlines between the min/max datapoints at the x limits, then i would suggest using the `setSelect` hook and adding two trend extra manually-updated trend series with `spanGaps: true`. this solution is one that lets uPlot to handle a lot of the logic that you'd otherwise need more code to handle in userland:

https://jsfiddle.net/h8o6qaz2/

there's currently no way to have the zoom behavior snap to the datapoints, which is why a manual zoom action may zoom to arbitrary ranges along the scales, and we have to do our own clamping.

if you'd prefer to snap the selection range to datapoints rather than clamping the trendline range, you can easily disable and re-implement the zoom relying on `setSelect`:

https://jsfiddle.net/dzbxym41/1/

if this works for you, then it's probably the solution which involves the least amount of extra code. otherwise...

there's no `onclick` event - you should add your own using normal `addEventListener` in the `init` hook. if you don't want to utilize `data` & series to draw trendlines, you can always draw directly on the canvas.

you can see the draw-hooks demo for how this is done:

https://leeoniya.github.io/uPlot/demos/draw-hooks.html

**Comment by leeoniya** [comment]
if you want to hide the original data series on zoom, you can do that easily, too:

https://jsfiddle.net/ra2u6cwd/1/

the reason for adding `u.batch` is so that each `setSeries` call does not immediately trigger a full chart redraw.

**Comment by GatCode** [comment]
Thank you very much for your help!
This is exactly what I was looking for! 🎉
