### ISSUE TITLE
user-defined series path builder

### ISSUE THREAD

**Issue by silverwind** [leeoniya/uPlot#130]
While I've seen the note in README I wonder if you would consider at least accepting a user-supplied bezier-drawing function to smooth curves which is particularily nice to have on plots with only a few data points.

I'm no expert on canvas drawing, but I imagine for every line to render, you could call the user's function using `(xStart, yStart, xEnd, yEnd)` arguments, do `ctx.moveTo(xStart, yStart);` and accept back the arguments to use on `ctx.bezierCurveTo(cp1x, cp1y, cp2x, cp2y, x, y)` to draw the curve.

**Comment by silverwind** [comment]
Actually, I think it might be possible to just pre-interpolate the data using something like https://github.com/kjerandp/curve-interpolator and pass `$width` datapoints `uPlot`. While this approach would destroy accuracy in legend and such, I think it could be made to work somewhat in a tooltip-only chart where the tooltip shows the nearest "real" data value.

Still, some kind of first-class support would be preferred but I'd understand if you don't want to do it.

**Comment by leeoniya** [comment]
> Still, some kind of first-class support would be preferred but I'd understand if you don't want to do it.

first class support ain't gonna happen. uPlot was conceived as a tool for precise data insight and goes to great lengths to assure that. adding features that sacrifice precision for aesthetics is antithetical to that goal. it doesn't take many points to end up with a garbage chart:

![image](https://user-images.githubusercontent.com/43234/74878975-d2978300-532d-11ea-96a0-50945d3a48f8.png)

that being said, `series.draw: false` can already be used to disable the lines, but still have the series be "enabled" and participate in auto-scaling, legend and cursor hover points.

i can maybe add the ability to accept a function for `series.draw` which shifts the drawing responsibilities to the user and you can do whatever you want in there. e.g. the `candlestickPlugin` portion of [1] can be moved into a user-supplied `series.draw` function.

but as you can see from the candlestick demo, it's already quite easy to draw your own series as you see fit.

[1] https://leeoniya.github.io/uPlot/demos/candlestick-ohlc.html

**Comment by silverwind** [comment]
Ok, will attempt this using the `draw` hook like in the candlestick demo, thanks.

**Comment by leeoniya** [comment]
doing stuff in the draw `draw` hook will work, but it not ideal.

i may add a `series.path` api slightly to better support custom path drawing. doing things at the series level makes a lot more sense, since it allows you to take advantage of `drawSeries` hooks, built-in clipping & fill options, and probably other stuff.

**Comment by silverwind** [comment]
Sounds great. Let me know when you have something I can try.

**Comment by leeoniya** [comment]
updates:

`series.draw` is gone, replaced by `series.paths: () => null`.
(candlestick demo updated, cc @ldstein)

the API for `series.paths` matches the internal `buildPaths()` [1] signature:

```js
paths: (u, sidx, xdata, ydata, scaleX, scaleY) => {
  return {stroke, fill, clip};     // Path2D instances
}
```

a minor inconvenience remains with the fact that the native buildPaths() is able to use `getXPos()` & `getYPos()` directly to get canvas offsets, but the exposed `.valToPos()` returns css pixel offsets, making you re-multiply by `devicePixelRatio`. you can see this already being done here:

https://github.com/leeoniya/uPlot/blob/01be7829ce6a743fb19dad2a930b8f66b57ff48e/demos/candlestick-ohlc.html#L143-L147

i should add extra methods, or a bool param to `u.valToPos(val,"x", true)` to directly return canvas pixels.

i also realized that this change is insufficient to fully convert the candlestick rendering in the demo because the the candles are effectively custom path "points", for which i'll soon add a similar-ish api as part of #10.

[1] https://github.com/leeoniya/uPlot/blob/master/src/Line.js#L682

**Comment by leeoniya** [comment]
i think the core of what's necessary to draw your own paths is now in place.

have fun: https://jsfiddle.net/gu95ak3x/

**Comment by konsalex** [comment]
For the last fiddle, just updated the new object call to work properly: https://jsfiddle.net/konsalexee/cztwdf3v

The demo is great, needs some fine-tuning with `null` values and how to handle them, as they appear to just fall down smoothly to 0, while in that case a sharp/cliff decrease would be more appropriate.

**Comment by leeoniya** [comment]
uPlot now includes a smooth pathBuilder in the core, with a much better implementation than what's in this demo.

https://leeoniya.github.io/uPlot/demos/line-paths.html
