### ISSUE TITLE
Question: Date Formats

### ISSUE THREAD

**Issue by x2764tech** [leeoniya/uPlot#140]
Related to #139...

The current `fmtDate` function uses the regex ```/\{([a-z]+)\}|[^\{]+/yi```

Which is used to match `{YYYY}`, `{M}/{D}\n{YYYY}`, etc...

However, passing it something with an open parenthesis without letters will discard the rest of the string. 
Eg: `{YYYY}{1}{M}`, `{YYYY}{{M}` and ``{YYYY}{}{M}` will be translated as `{YYYY}`.

So the question is: What is the intended format for dates?

**Comment by leeoniya** [comment]
hey @x2764tech 

the format is simply to enclose any key strings [1] in `{}`. i have never seen a literal `{` inside of a formatted date string, so i'm not particularly interested in handling what i consider an extreme edge case.

i'm pretty certain we can just change the regex to `/gi` instead of `/yi` for this application since `exec` continues where it left off anyways, and the regex matches both cases - formatting tokens and "everything else".

[1] https://github.com/leeoniya/uPlot/blob/master/src/fmtDate.js#L63

**Comment by leeoniya** [comment]
closing this as resolved for now. if you can show a strong case for supporting curly braces in formatted date strings, we can re-open.
