### ISSUE TITLE
Scale with range doesn't adjust on zoom

### ISSUE THREAD

**Issue by switchtrue** [leeoniya/uPlot#142]
When setting a scale on a graph with a range, when zooming the scale doesn't adjust. As such, rather than zooming the graph just draws the series for the highlighted selection.

I'm not sure if this is a bug or expected behaviour. It seems unintuitive to me but maybe theres an event I'm supposed to use to capture the new range and pass it back in?

I've put together a fiddle example here: https://jsfiddle.net/97dcxhL5/

The use case is that I was to plot a graph that show from midnight to midnight of the current day regardless of how much data is present.

Zoomed out:
![Screen Shot 2020-03-05 at 10 36 44 am](https://user-images.githubusercontent.com/1535972/75933186-6db35f80-5ecd-11ea-9009-44f7b4ebb9bd.png)

Making Selection:
![Screen Shot 2020-03-05 at 10 36 58 am](https://user-images.githubusercontent.com/1535972/75933210-7c017b80-5ecd-11ea-80f0-9e2c4a053d5a.png)

Zoomed In - kinda...:
![Screen Shot 2020-03-05 at 10 37 07 am](https://user-images.githubusercontent.com/1535972/75933245-95a2c300-5ecd-11ea-8e1f-30d0b30ca180.png)

Example `scales`
```javascript
scales: {
  x: {
    time: false,
    range: [0, 100],
  }
}
```

**Comment by leeoniya** [comment]
i'm a bit confused as to what you're looking for.

with `time: false`, there's no such thing as midnight to midnight, since it's strictly numeric. so i'll ignore this for now.

you're assigning x scale a static range of `[0, 100]`, which it properly maintains. the way that uPlot zooms is by adjusting expanding or contracting the range of the scale, so you cannot have both a static x range and zooming along x - they are mutually exclusive.

if you're just trying get the "100" x tick value to show at the right edge of the grid when fully zoomed out, then you can do it a few ways.

the easiest way is to null-pad the data: https://jsfiddle.net/eLo7b69k/

a more non-hack way is to *conditionally* adjust the scale range: https://jsfiddle.net/eLo7b69k/1/

**Comment by switchtrue** [comment]
Sorry, `time: false` was just for the example - in my production code I have `time: true` and the `x` values are timestamps. It was just easier for the fiddle to use the static array of numbers.

Both of those options for making this work appear to be suitable. I'll test them and report back.

**Comment by switchtrue** [comment]
I went with the latter option of using the function and it works a treat!
