### ISSUE TITLE
Is it possible to have grid lines without a label?

### ISSUE THREAD

**Issue by photonstorm** [leeoniya/uPlot#149]
Trying to get axis gridlines to appear, but without the label or anything else, but it doesn't seem to matter what config combination I try it just doesn't happen. Is it possible? (none of the current examples show this, they all assume the labels will be present)

I can work around it in the meantime, but would love to know how to do it!

**Comment by leeoniya** [comment]
just have the axis values formatter return an empty array: `axis.values: u => []`.

if you also want to kill the default space allotted for the labels & ticks, play around with `axis.size`. maybe set it to 0.

you can also adjust/kill the axis gutters (see https://github.com/leeoniya/uPlot/issues/133)

**Comment by leeoniya** [comment]
> just have the axis values formatter return an empty array

correction:

this won't work in 1.0.0. you have to return an array of empty strings with a length equal to the axis splits: `axis.values: (u, splits) => Array(splits.length).fill("")`.

i just pushed a minor refactor to `master` which allows an empty array return.

**Comment by leeoniya** [comment]
@photonstorm 1.0.2 should have you covered.

if you're turning off axis values, i would recommend fixating the y range and controlling the grid-lines explicitly, otherwise if you leave them automatic, they just become meaningless adornments:

https://jsfiddle.net/vg8nLace/2/

let me know if you have any further questions.

cc @switchtrue

**Comment by photonstorm** [comment]
That's great, thank you. I'll give this a go when I update tomorrow.
