### ISSUE TITLE
remove redundant lineTo commands by rendering data as columns

### ISSUE THREAD

**Issue by 1wheel** [leeoniya/uPlot#15]
example: https://bl.ocks.org/1wheel/0e7f71ac0325b9be92c9dd19fe4bcc44

**Comment by leeoniya** [comment]
hey @1wheel , this looks pretty sweet. i actually saw this technique buried in some chart lib's docs with a bunch of caveats just a few days ago. i'm trying to find where i saw it and it's driving me nuts!

something similar here: https://www.amcharts.com/docs/v4/concepts/performance/#Simplifying_paths

thanks for the demo! unless you want to take a stab at this impl in uPlot, i'm going to focus on some of the other todos first and revisit this later. you know what they say about premature optimization 🤣

**Comment by leeoniya** [comment]
@1wheel i did a basic test of this strategy in another branch [1] and it does indeed shave off about 50% of the render time toggling a series on/off (which is a full rescale/redraw) went from ~23ms -> ~12ms. i'm using `fillRect()` calls at the pixel boundaries rather than `lineTo()` at `+0.5` offsets. fillRect handles 1x1 sizes more naturally, too.

i don't have any gap-filling logic there yet, so at higher zoom levels it's just dots.

[1] https://github.com/leeoniya/uPlot/tree/reduce-lineTo

**Comment by leeoniya** [comment]
a simplified variant of this has been implemented. thanks for the suggestion & PoC! 💯

**Comment by leeoniya** [comment]
btw, i think i nabbed the cold-start issue in https://github.com/leeoniya/uPlot/commit/9d71ac9289235aff8e79ad7da9eea53cf2bbd63d. i'm guessing it was a V8 de-opt due to some stuff was ending up as `NaN`s due to declared but undefined vars.

**Comment by 1wheel** [comment]
oh interesting!
