### ISSUE TITLE
Unexpected cursor snapping behavior with non-aligned series

### ISSUE THREAD

**Issue by mourner** [leeoniya/uPlot#155]
When using uPlot with two non-aligned time series (with `null` values and `spanGaps: true`, the cursor snapping behaves in a seemingly erratic fashion — jumping back and forth, skipping some values, etc.:

![uplot-cursor](https://user-images.githubusercontent.com/25395/76744874-982ed380-677d-11ea-8b53-be11855e7c5a.gif)

Is this expected, or a bug, and what's the current logic for snapping? I would expect it to snap to the closest point of either series on the x axis. And if expected, what would be the recommended way to deal with this?

Thanks a lot for such an awesome library @leeoniya!

**Comment by leeoniya** [comment]
hey @mourner,

definitely looks like a bug. can you provide the above dataset (or a representative one) to save me some typing? a fiddle would be appreciated.

> Thanks a lot for such an awesome library @leeoniya!

and thank you for https://github.com/mourner/flatbush. uPlot will likely use it in the near future for scatter plots in https://github.com/leeoniya/uPlot/issues/107

**Comment by mourner** [comment]
I couldn't reproduce this with a simple example, and then I realized what the issue was — the time values were not fully sorted (where uPlot likely assumes they are), so it was an issue on my side. Should uPlot produce a console warning when an x value is smaller than the previous one? Or maybe sort under the hood on initialization?

**Comment by leeoniya** [comment]
> Should uPlot produce a console warning when an x value is smaller than the previous one?

the search for closest value is just a binary search over the data[0] array and retrieval of the matched index from the remaining arrays. since there's no sequential scanning, it's not really possible to do this reliably.

> Or maybe sort under the hood on initialization?

all the data arrays would have to be sorted together (to maintain alignment), but i'm not aware of any way to get this done with native `.sort()`. also, i have not tested the cost of doing a native .sort() on already-sorted large arrays. i think the unsorted case is rare enough that it's not worth sacrificing perf or adding code for the typical case.

a good alternative would be a create a userland data validation function that can provide any kind of sorting or warnings. this would allow for opting into the extra overhead.
