### ISSUE TITLE
Line dots sometimes dont appear in plot

### ISSUE THREAD

**Issue by CrashLaker** [leeoniya/uPlot#157]
Hi all,

I'm trying to understand why sometimes the line markers somehow won't show in the plot.
![image](https://user-images.githubusercontent.com/4432491/77119404-24a6f380-6a15-11ea-9ab2-ba8d62ce1356.png)

is it my dataset or a bug?

here's my dataset. https://jsfiddle.net/1yh04Lme/
(try zooming on the first spikes)

**Comment by leeoniya** [comment]
series 19 has an invalid stroke: https://jsfiddle.net/q1ksrnpm/4/

i guess canvas swallows it, but `style.background` does not.

**Comment by CrashLaker** [comment]
How did you spot it?

Also is there like a verbose flag for developers to enable?

**Comment by leeoniya** [comment]
> How did you spot it?

i started trimming data, then trimming series until the problem went away, then slowly went backwards. then pretty-printing the series and noticed the mis-alignment.

> Also is there like a verbose flag for developers to enable?

nope. if i had to add runtime error checking and reporting to the codebase, it would be 2x bigger.

if you're using VSCode, the typings which will land shortly in #153 will help with catching some stuff, but probably still would not catch the issue, since both valid and invalid hex colors are string types.

**Comment by CrashLaker** [comment]
> i started trimming data, then trimming series until the problem went away, then slowly went backwards. then pretty-printing the series and noticed the mis-alignment.

nice. i'll try your approach more often. at least now I know that the problem is usually regarding the dataset.

> nope. if i had to add runtime error checking and reporting to the codebase, it would be 2x bigger.

I see. I guess It would also bring a boost of perfomance to it too right? looking forward to it. great job you all :)
