### ISSUE TITLE
Initializing uPlot with a single row leads to errors

### ISSUE THREAD

**Issue by leolabs** [leeoniya/uPlot#164]
```
Cannot read property 'push' of undefined
```

This is caused because `findIncr` doesn't return a result ([line](https://github.com/leeoniya/uPlot/blob/6c5a993ac096a34245070f3a3773cec1f207a2ee/src/uPlot.js#L133)) and `getIncrSpace` tries to then access the second item of `undefined` ([line](https://github.com/leeoniya/uPlot/blob/6c5a993ac096a34245070f3a3773cec1f207a2ee/src/uPlot.js#L904)).

It might be a good idea to check if the result is `undefined` in `getIncrSpace` or to return defaults from `findIncr`.

Screenshot from Sentry:
<img width="540" alt="Screenshot 2020-03-25 at 14 56 00" src="https://user-images.githubusercontent.com/541628/77544157-f445d600-6ea8-11ea-8cd5-03b39d5cd9a0.png">

In general, it would be interesting to choose a behavior for graphs with only one row since there isn't enough data to generate any lines, only points.

**Comment by leeoniya** [comment]
> In general, it would be interesting to choose a behavior for graphs with only one row since there isn't enough data to generate any lines, only points.

yes, this can/should be revisited now that uPlot can do point rendering (originally it could only do lines, areas & bands).

the main thing uPlot needs to draw *anything* is to set the scale ranges

the demo from #162 shows how chart can be initialized without data: https://jsfiddle.net/afL8o2zh/

there is already some accounting for determining a numeric/y scale when the data is completely flat (where max - min = 0): https://jsfiddle.net/afbkpdnz/

the logic is part of `extra` in `rangeNum`:

https://github.com/leeoniya/uPlot/blob/6c5a993ac096a34245070f3a3773cec1f207a2ee/src/utils.js#L67

however, there is no such logic for temporal scales (because the x scale is always manually ranged and `auto: false`). we would need some equivalent way of auto-ranging a temporal scale from a single timestamp to some "reasonable" min/max. what constitutes reasonable, though, is completely vague when it comes to time - i don't think there's a good answer.

on the other hand, if you can pre-range the scales as in the jsfiddle, then it should be easy to simply avoid scale ranging and line drawing, only leaving one point.

**Comment by leeoniya** [comment]
> what constitutes reasonable, though, is completely vague when it comes to time - i don't think there's a good answer.

i should add that part of this is due to the design decision of accepting timestamps and avoiding parsing from date strings, whixh could convey some sense of granularity, eg by omitting time from `2020-05-01` we can assume a range of 10 days to either side, or something.

i think the solution to this will be for uPlot to avoid drawing lines when there's a single data point *and* for the users to add their own `scales.x.range` function which handles setting the range when dataMin == dataMax.

i'll push some changes and add demo later today.

**Comment by leeoniya** [comment]
i decided to go with a default of placing the single datapoint at the left extreme of the plot and ranging temporal scale max to +24 hours and numeric x scale to the next magnitude (e.g. 17 -> 100, 213 -> 1000). this seems to be an okay compromise. if someone needs to customize this, they can always do it in an explicit `scale.range`.
