### ISSUE TITLE
Ability to update number of serias

### ISSUE THREAD

**Issue by rlz** [leeoniya/uPlot#167]
In my app users can turn on and off some series from plotting. I found that there is no way to remove or add series after the creation of uPlot object according to the typescript definition file.

**Comment by leeoniya** [comment]
there was some recent discussion about this here: https://github.com/leeoniya/uPlot/issues/162#issuecomment-603550064

i would like to understand your use-case better first.

**Comment by leeoniya** [comment]
an initial form of this has been added: `.addSeries(opts, data)` and `.delSeries(i, delData)`:

https://leeoniya.github.io/uPlot/demos/add-del-series.html

this involved quite a bit of internal refactoring work: https://github.com/leeoniya/uPlot/compare/79d7875...a40c94a. uPlot has a lot of inter-dependent init logic that must be done in careful order. because of this, adding imperative functions to the API is always tricky because you have to re-init and invalidate things all over the place. due to lack of automated tests, these things always risky. i have not carefully re-tested every demo yet, but from the few that i did test that rely on the refactored parts, i don't expect major issues.

the good news is that this did not add a huge amount of extra code. the meh news is that i had to adjust one signature of the `cursor.points.show` API (when it's a function, it will now be called once per series and should return one DOM element instead of being called once and returning a series-length array of DOM elements). i'm certain no one uses this signature yet anyhow, so i'm fine with this BC.

i'm looking for feedback on the API. specifically whether they should include data-related tasks or not. there are pros and cons:

pros:
- dx ergonomics: a single function call will update the chart with new series data
- it's harder to forget to properly set the data via `.setData()`
- the data-related stuff is optional

cons:
- you lose control over whether the x scale (zoom) gets reset by the internal `.setData()` call, since i don't expose this flag in the add/del APIs
- for live update type scenarios, you probably already have the new data ready to go and would prefer the ergonomics of continuing to call `.setData()` as usual after calling `.addSeries()`.

cc @LostKobrakai @josevalim @petermm

**Comment by leeoniya** [comment]
i think i'll drop the data-setting args. it's one extra line in userland [1] but feel more future-proof by not conflating data related calls with opts/config opts. fewer ways to do one thing is a plus in my book.

[1] https://jsfiddle.net/qtw7680k/

**Comment by josevalim** [comment]
This looks amazing @leeoniya, thank you!

> adding imperative functions to the API is always tricky because you have to re-init and invalidate things all over the place

Question: if you allowed `setSeries` to potentially receive new series, would that be a better API than the imperative `addSeries`? Or would that actually be more complex?

> for live update type scenarios, you probably already have the new data ready to go and would prefer the ergonomics of continuing to call .setData() as usual after calling .addSeries().

FWIW, I think both approaches are equally straight-forward from the usage/ergonomics perspective. :)

**Comment by leeoniya** [comment]
> Question: if you allowed `setSeries` to potentially receive new series, would that be a better API than the imperative `addSeries`? Or would that actually be more complex?

yeah it would be more complex in the current design. and with a different design it would be slower and much larger. uPlot makes a deep copy of your opts and then merges in a bunch of implicit defaults based on a lot of assumptions. these new opts become the living mutable state. it would be quite complicated to do diffing against it, especially since referential integrity is lost during the deep copy, and you may want to add series to somewhere other than the tail anyways.

**Comment by leeoniya** [comment]
ok, i dropped the data stuff and added an optional `seriesIdx` to `.addSeries(opts, seriesIdx)` so it can be inserted into arbitrary positions.

https://leeoniya.github.io/uPlot/demos/add-del-series.html
