### ISSUE TITLE
Cross line at cursor position rendered in wrong position if graph placed in container with overflow: 'scroll'

### ISSUE THREAD

**Issue by rlz** [leeoniya/uPlot#168]
I placed uPlot within div with {overflow: 'scroll'} CSS. It leads that position of the horizontal line intended to be placed at the cursor position drawn with offset depending on the scroll position.

**Comment by leeoniya** [comment]
since it is expensive to read back DOM offsets on every mousemove event, uPlot caches the bounding rect on window resize & scroll:

https://github.com/leeoniya/uPlot/blob/master/src/uPlot.js#L1715-L1718

i'm not sure what to do in cases like this when the position may shift due to some offsetparent scroll or css transform, etc.

maybe there should be an api exposed for updating the internal cached rect and leave the "when" up to the user?

**Comment by leeoniya** [comment]
i've exposed `.syncRect()`:

https://jsfiddle.net/ud7chaxs/

**Comment by rlz** [comment]
Thank you! I think it's enough. When it will be available via npm repo?

**Comment by leeoniya** [comment]
i'll tag a new release today or tomorrow.

**Comment by leeoniya** [comment]
v1.0.4 is up on npm now.
