### ISSUE TITLE
Axes with Exact Same Number of Labels

### ISSUE THREAD

**Issue by MehrdadKhnzd** [leeoniya/uPlot#178]
I have multiple axes on my chart, and that's very hard to read, because of this:
![image](https://user-images.githubusercontent.com/49184153/79632861-42cc5480-8177-11ea-9640-10beb845bab2.png)
I want the labels to be in line with each other, or in other words, I want the labels' count on each axe to be the same, so they get aligned to each other, and the grids don't conflict. How to achieve this?

**Comment by leeoniya** [comment]
in the specific case of your screenshot, i'm not sure it makes sense to have 3 separate °C scales when the units match and are nearly in the same range. here you can have a single °C scale & axis that covers 800 °C - 2000 °C, which would be the easiest solution. this would not be a workable solution if your ranges were very different and without much overlap, like 0-10 and 700-710.

typically you would disable the gird on the secondary axes (`axis.grid.show: false`) so they do not conflict rather than trying to get the axis ticks to align. i'm assuming you would want to align the ticks to some primary axis/scale (red), which at different zoom levels and data y-ranges will give you very strange numbers. if you zoomed some data and the red scale changed to 810-930 ticks, and the blue series in that x range became in the 1870-1980, when you try to align the ticks to the red, you might get values along the blue like 1877.3, 1936.5, 1962.1 - is this something you want?

if you have pre-defined (non-zoomable) ranges for the scales that you pre-divide manually so everything aligns, then it can work also.

you may find it rather difficult (or impossible) to get alignment that has nice numbers on all axes when you take into account that the scales are re-ranged dynamically (when `scale.auto: true`) according to each series' data to achieve "zoom".

there are two knobs in uPlot that would let you do whatever you want:

- `scale.range` is a function that returns the `[min,max]` you want to show based on the ymin/ymax of all the data found in the selected xmin/xmax. the default numeric ranging function is here:
https://github.com/leeoniya/uPlot/blob/1ef39ef1899bacb5a3ae7209cfd0f2600d9590e3/src/uPlot.js#L149-L151
- `axis.incrs` are then used with this `[min,max]` to determine the smallest divisor (`incr`) that still maintains the minimum `axis.space` for the current chart dimension.
- `axis.split` then uses the determined `incr` and scale's `[min,max]` to return the scale values where the ticks & grid should be placed. the default numeric axis splitting function is here:
https://github.com/leeoniya/uPlot/blob/1ef39ef1899bacb5a3ae7209cfd0f2600d9590e3/src/opts.js#L375-L384

that's a pretty complete rundown of how to fully customize whatever you need.

**Comment by MehrdadKhnzd** [comment]
Thanks for your thorough explanation. So I guess my current easiest solution is to remove all of the grids, but when I have enough time, I can fix this. Is there a way to bind the grids to the chart itself, not the axes? A static grid irrelevant to axes, something just to make the following the points of the chart easier. Or at least horizontal lines as the X-axis and the Y-axis of the chart. If I remove grids, it becomes completely blank and you lose borders, and that's annoying.

**Comment by leeoniya** [comment]
there's no way to draw the grids independent of the axes. but you can draw whatever you like directly on the canvas using its `draw*` hooks, including a static grid. take a look at https://leeoniya.github.io/uPlot/demos/draw-hooks.html

for borders you can use bit of css:

```css
.uplot .over {
    box-shadow: -1px 1px #333;
}
```

**Comment by MehrdadKhnzd** [comment]
Thanks again for your help! That's really appreciated!
