### ISSUE TITLE
Better ranger demo

### ISSUE THREAD

**Issue by Misiu** [leeoniya/uPlot#181]
The current demo (https://leeoniya.github.io/uPlot/demos/zoom-ranger.html) has great performance, but the UI isn't that intuitive.
Take a look at https://www.highcharts.com/stock/demo/compare or https://www.amcharts.com/demos/area-with-time-based-data/

In both demos, you can use a slider to select the range to display:
![chart](https://user-images.githubusercontent.com/1741838/79838625-975c1380-83b3-11ea-863a-aac0837ab83c.gif)

I'm looking for a chart library that could be used to replace the Home Assistant library.
Current one  draws charts quite good, but with a lot of points, like this:
![image](https://user-images.githubusercontent.com/1741838/79839591-04bc7400-83b5-11ea-8194-c8e1b93539f6.png) it's hard to see anything, especially without zoom (range selection)
your library has much better performance, the only thing missing is a more intuitive ranger.

**Comment by leeoniya** [comment]
hey @Misiu 

> I'm looking for a chart library that could be used to replace the Home Assistant library.

i'm a big fan of home-assistant and have been meaning to try it out when i get a bit more free time. the COVID lockdown seems like a good excuse :)

it would be cool to contribute uPlot into such a great project.

> the only thing missing is a more intuitive ranger.

can i ask how many datapoints (or what time window?) does home-assistant make visible on initial page load? is it the full data range or a pre-zoomed range?

i feel like the real value of a ranger is when you have to visually indicate that the initially displayed data is a subset of all data.

the linked zoom-related issues seem to indicate that the problem was mousewheel zoom being engaged unintentionally during page scroll. with uPlot, there would be no such issue and the zooming would still work normally. the original zooming plot also did not have a ranger.

have you seen the touch/pinch zoom demo?

https://leeoniya.github.io/uPlot/demos/zoom-touch.html

the issue with making a ranger behave the way you're showing (or panning, or the smooth zoom like in the touch demo) is that with you have to redraw the entire chart on every dragged/scrolled pixel. with 1k datapoints it might be fine, but with 100k datapoints it will be poor. it's the main reason i made the ranger demo without as-you-drag chart redraws.

if this is something that's deemed absolutely necessary, then it shouldn't be too hard to make a ranger that works on drag, but is more susceptible to performance issues with large datasets.

**Comment by leeoniya** [comment]
hey @Misiu 

i'm gonna close this. if you end up working on replacing the Home Assistant charts and get as far as getting uPlot integrated, working and likely to land, and still want to provide a draggable ranger, i'll help you get that coded.

as far as the ranger demo in this repo goes, i'd like to keep non-draggable.

thanks for your interest!
