### ISSUE TITLE
uplot.redraw() doesn't seem to trigger custom series[].paths

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#183]
Not sure if this is by design.

I'm drawing my series path manually (use case: the path line changes color depending on some other array's value). For this I set up a custom `series[].paths` function as described in the `"line-smoothing.html"` example.

I found no way of drawing a multi-colored path with `Path2D` so I'm junst doing the old style `uplot.ctx.lineTo(x,y)` and `uplot.ctx.stroke()` , then I just return `false` from the function. Seems to work well so far.

However, after I make some data changes (outside uplot) and do a `uplot.redraw()`, the path dissapears and the series[].paths function is not called again.

Zooming out fixes everything.

Is this a bug? or was I expected to invoke the paths function manually?

**Comment by leeoniya** [comment]
so, the original idea behind `.redraw()` in https://github.com/leeoniya/uPlot/issues/80 was to re-fire all `draw*` hooks (#76) and just repaint of cached Path2D objects without a full rebuild/recalc, but it can also be used to absorb mutated styles as in #182. `.redraw()` is therefore really cheap, but i agree that it's not obvious that it will not force a path rebuild.

i think it's a good idea to add a param like `.redraw(withRebuild)`, and default it to `true`. this would be equivalent to just calling `.setScale('x', {min: u.scales.x.min, max: u.scales.x.max})`, which also forces a full invalidation. i think this would be better match expected behavior, but still leave an opt-out when not desired.

**Comment by leeoniya** [comment]
implemented on master. see if that works as you'd expect.

**Comment by danyalejandro** [comment]
Works perfect now, thank you.
