### ISSUE TITLE
Weird cursor offset in certain cases

### ISSUE THREAD

**Issue by mourner** [leeoniya/uPlot#186]
I've embedded a uPlot chart in an Observable notebook here:
https://observablehq.com/@mourner/ukraine-covid-19-daily-onset-cases

It works great on load, but if you make any changes (e.g. press the "play" button on the right of any code "cell"), the chart cursor shifts ~50px to the right & ~200px down. Not sure what might be causing it, perhaps the mouse position code in uPlot doesn't take some things into account? (Observed in Chrome)

Thank you!

**Comment by leeoniya** [comment]
odd.

uPlot caches its `Element.getBoundingClientRect()`, and re-syncs it only on window scroll and resize. any other position changes should be manually synced by calling `.syncRect()` [1].

in this case it looks like the chart is getting fully re-created, so i'm not sure this is the issue here. if the non-minified source available anywhere? it's not easy to debug this without a minimal non-mnified repro.

[1] https://leeoniya.github.io/uPlot/demos/scroll-sync.html

**Comment by leeoniya** [comment]
probably what's going on is that this [1] only fires reliably after browser layout is done on page load. in cases of re-creation it fires too early and before the layout is fully done.

honestly, the whole `syncRect()` API is not ideal. i should just re-sync the rect on `mouseenter` of the plotting area and call it a day.

[1] https://github.com/leeoniya/uPlot/blob/193085438300389ff28bc479fc275875168b9c6d/src/uPlot.js#L1856

**Comment by leeoniya** [comment]
can you plz check if this is still reproducible after ca5a9357db592f2c19e49b3d17acb6f402727ca3?

**Comment by mourner** [comment]
@leeoniya thanks for responding in so quickly! I wasn't aware of `syncRect`, but calling it on `mouseenter` in the notebook solves the problem, so you're right! But I agree that making this automatic would be nice.
