### ISSUE TITLE
Any way to limit zoom-in?

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#187]
Sometimes if you click-drag to zoom (default out-of-box behavior) into super small areas with less than 10 points uPlot throws a TypeError (Uncaught TypeError: Cannot read property '2' of undefined).

Is there any way to limit the maximum zoom so that this never happens?

**Comment by leeoniya** [comment]
this could always be done be implementing your own zoom logic on top of the `setSelect` hook: https://leeoniya.github.io/uPlot/demos/trendlines.html

however, it should have been possible to do this by simply setting the `scale.range` function to intercept and adjust the min/max as needed. the problem was that internally i mutated the scales *during scaling* so it was impossible to get & return the original values (to "cancel" the zooming). i adjusted the logic to avoid mutating the scales so the current values can be read back.

see https://jsfiddle.net/x8wsmg2a/

[1]

**Comment by danyalejandro** [comment]
Thank you!

**Comment by piotrnajda3000** [comment]
> this could always be done by implementing your own zoom logic on top of the `setSelect` hook: https://leeoniya.github.io/uPlot/demos/trendlines.html
> 
> however, it should have been possible to do this by simply setting the `scale.range` function to intercept and adjust the min/max as needed. the problem was that internally i mutated the scales _during_ scaling so it was impossible to get & return the original values (to "cancel" the zooming). i adjusted the logic to avoid mutating the scales so the current values can be read back.
> 
> see https://jsfiddle.net/x8wsmg2a/

Hey, thank you for the JSfiddle! 

The page crashes when trying to zoom in below the minimum range in the [trendlines demo](https://leeoniya.github.io/uPlot/demos/trendlines.html):

https://github.com/leeoniya/uPlot/assets/58721991/df9ac22a-cd9f-475c-9f01-bd48b88eddb4

**Comment by AshwinTayson** [comment]
@leeoniya Hi! Thanks for the great library. I wanted to create a new issue but this feels relevant. How do I implement min and max zoom levels with a set initial zoom level.

Lets say there are 200 data points. I want to show the last 50 initially. You can zoom out to 75 data points but then you have to pan to see other data. At the same time you shouldn't be able to zoom in see less than 25 data points.

But whatever is the initial zoom value (50) becomes the max. What am I doing wrong here.

Attaching fiddle [here](https://jsfiddle.net/Lkxzvwps/7/)

On a related note, in the same example when you pan to the right after reaching the right end, the chart starts zooming in. Same on the left pan on leftmost end. Thank you in advance
