### ISSUE TITLE
Browser hangs when tzDate is defined with uPlot.tzDate

### ISSUE THREAD

**Issue by ALEUT** [leeoniya/uPlot#189]
I use uPlot with enough big datasets (400k+ timeseries records) and if I define ```tzDate: ts => uPlot.tzDate(new Date(ts), 'Etc/UTC')```, after several interval selections my tab in the browser (latest Chrome) hangs and can't do anything for a long time. I used profiler to investigate and it looks it hangs in this function. I replaced it with my own implementation:

```
tzDate: ts => new Date(getUTCDateFromLocal(ts))

const getTimezoneOffset = (date: number): number => new Date(date).getTimezoneOffset() * 60 * 1000;

const getUTCDateFromLocal = (date: number): number => date + getTimezoneOffset(date);
```

And as result it works with some slowdowns, but without hangs.

**Comment by leeoniya** [comment]
tzDate is pretty cheap and not called very often. the dataset size should have no effect on this. maybe it's hitting an endless loop higher up that it has to keep calling it. can you try adding `console.count()` into that function and see how many times it's called when at full zoom-out and then each zoom-in?

also `.getTimezoneOffset()` is not gonna work if you need to account for DST changes, which is why i'm not using it.

**Comment by ALEUT** [comment]
@leeoniya forgot to add that I use wheelZoomPlugin and it happens on scrolling. Measured with `console.count()` on scroll - got very big number of invocations: 300-400k.
Regarding my approach - it works well with DST because `getTimezoneOffset` returns different offset for date in DST and date not in DST. I already faced with it before, that's why I call `getTimezoneOffset` each time for each date instead of using cached value.

**Comment by leeoniya** [comment]
> forgot to add that I use wheelZoomPlugin and it happens on scrolling

if this only happens during scroll, then i think this is the most likely issue here. there's probably a bug in there. that demo has only been tried with numeric `x`.

can you put a breakpoint in the code below and tell me which values it's trying to set on the `x` that cause it to spike in tzDate calls? i would also recommend disabling the legend via `legend: {show: false}` to reduce the noise.

also, what browser are you in?

https://github.com/leeoniya/uPlot/blob/eadb59d91c0a3d77e3188ef63d1516af47d15ef5/demos/zoom-wheel.html#L72-L75

**Comment by ALEUT** [comment]
> can you put a breakpoint in the code below and tell me which values it's trying to set on the `x` that cause it to spike in tzDate calls? i would also recommend disabling the legend via `legend: {show: false}` to reduce the noise.

nxMin is 1426316889985.8914
nxMax is 1427081978774.1921

I use latest Chrome.

**Comment by leeoniya** [comment]
uPlot expects unix timestamps (seconds) in data[0], but it looks like you have js timestamps (milliseconds). then multiply them back in tzDate:

https://github.com/leeoniya/uPlot/blob/master/demos/months.html#L37

**Comment by ALEUT** [comment]
@leeoniya I have my own implementation for tzDate: `tzDate: (ts) => new Date(getUTCDateFromLocal(ts)),`

**Comment by leeoniya** [comment]
your original comment says that uPlot hangs with the standard tzDate imlementation but provide code that assumes millisecond timestamps:

> if I define tzDate: ts => uPlot.tzDate(new Date(ts), 'Etc/UTC')

uPlot requires that the x values are seconds. your own tzDate impl will not matter, because internally uPlot uses static values for time periods like hour = `3600`, which it uses in conjuction with x values to figure out axis ticks.

you can have a custom tzDate impl, but it must still handle seconds, which must be the x values.

**Comment by ALEUT** [comment]
@leeoniya thanks, looks the issue was in incorrect input format, now everything works fine!
