### ISSUE TITLE
Headless rendering

### ISSUE THREAD

**Issue by TudorHulban** [leeoniya/uPlot#192]
hi,
is headless rendering supported? would there be an example?
thank you!

**Comment by leeoniya** [comment]
headless like with `node-canvas` rather than Puppeteer in headless mode?

the title, legend, cursor, hovered points, and selected area are rendered in the DOM, but you can disable those.

the plot, grid, axes and labels are rendered on Canvas so this part should be do-able with likely some minor tweaks.

**Comment by TudorHulban** [comment]
something like:
https://www.highcharts.com/blog/news/52-serverside-generated-charts/

the constraint for some solutions is that what you see on browser you should have sent by email.

**Comment by leeoniya** [comment]
ok, this is basically headless Puppeteer or an alternative like what's done in https://github.com/leeoniya/uPlot/pull/175.

i don't think there's anything specific that uPlot needs to do in this case. you would just need to provide the matching chart config and data to the server for it to re-render there.

**Comment by TudorHulban** [comment]
thank you very much. will try the approach.
