### ISSUE TITLE
X axis other than time

### ISSUE THREAD

**Issue by mourner** [leeoniya/uPlot#2]
Quickly looking [at the code](https://github.com/leeoniya/uPlot/blob/master/src/uPlot.js#L337), it looks like only time series are supported currently — X axis can only be timestamps (not sure though since there are no docs yet). Would it be possible to support non-timed use cases (with custom-formatted X axis)?

**Comment by leeoniya** [comment]
as long as the axis remains numeric and pre-sorted ascending (both necessary for the binary search) it should be easy to add support. i've been gradually factoring out the hardcoded assumptions that existed in the original prototype and it's largely done.

**Comment by leeoniya** [comment]
the x-axis formatter and incr can already be overridden by opts during init.

https://github.com/leeoniya/uPlot/blob/master/src/opts.js#L60

**Comment by mourner** [comment]
Nice work BTW! I took a stab at that Telegram challenge myself, but dropped it because it was taking more time than I could afford. I knew it would eventually lead to some nice charting open source libraries surfacing :)

**Comment by leeoniya** [comment]
> that Telegram challenge

until i googled it just now, i had no idea what you were refering to. uPlot originated from my desire to make a much smaller dygraphs as i mention here [1]. not sure where ypu got the impression that it was rooted in some contest. :man_shrugging: 

[1] https://github.com/leeoniya/uPlot#acknowledgements

**Comment by leeoniya** [comment]
ok, so here are some thoughts on this.

first we need to add a `type` to xAxisOpts [1]. i'm thinking `s` (default), `ms` ,`n`. each of these would have to have an implied `incrs` and `values`.

one reason i'm considering `ms` is because that's JS's default for date values. on the other hand, to me any datasets that are granular down to the millisecond are unlikely to care about axis labels and incrs longer than an hour which would theoretically contain 3.6M data points. at that point, does the calendar date of that hour really matter?

it might just be easier not to accommodate `ms` in any special way, simply treat them as numeric and assume that these these types of datasets will provide ms offsets from some arbitrary point that's not calendar-bound.

thoughts?

[1] https://github.com/leeoniya/uPlot/blob/master/src/opts.js#L53

**Comment by leeoniya** [comment]
initial impl is done. the default x type is `t` (time), but can be changed to `n` for numeric. this must be done in both the `axes` and `series` opts:

https://jsfiddle.net/st0awf3g/

**Comment by leeoniya** [comment]
alright, i'm calling this done.
