### ISSUE TITLE
Make framework example pages in demos

### ISSUE THREAD

**Issue by mtfoley** [leeoniya/uPlot#205]
This is more of a suggestion than an issue, but perhaps adoption would boost with example pages that included use in frameworks.  I did a quick example as a Vue component and I tried to at least put some console logging in for hooks. No doubt this could be a lot better, but I wanted to start a discussion on it. See PR below for files.

**Comment by leeoniya** [comment]
hey @mtfoley, thanks for the PR!

i'll try to explain my position on this to the best of my ability.

i'd like to avoid committing examples for integration with third party code. there are several reasons for this.

1. i don't wan't to give the impression that i can or will offer assistance for interop with other code. this is a slippery slope and i don't have the resources (or knowledge) to explain more than the workings of uPlot itself.
2. i would prefer if uPlot's audience was one that is proficient enough with JS to be able to browse the demos, read the provided `.d.ts` API and immediately see how to use uPlot for their use-case within their environment without needing trivial examples that would only be helpful to e.g. junior Vue devs. again, this filter tends to keep the issues technical and their reporters are typically able to produce minimal repro code without much guidance. if you look through e.g. Chart.js's issues, many of them are support questions - and they have waaaay more approachable and extensive docs than uPlot!

i need to be able to say "look, this was a third party contrib and i cannot answer questions about it because i don't personally use <Vue|React|Angular...>". this is basically the litmus test for whether i want to accept code into the repo.

that being said, i think a Vue example could be ok to put into a wiki page here, and i can link to it from the README or docs without feeling obligated to support what's added there by others.

hope that makes some sense!

**Comment by mtfoley** [comment]
Cool with me - I tried clicking on Wiki in Github and it just redirects to the main page for the repo. Thanks for the review!

**Comment by leeoniya** [comment]
> I tried clicking on Wiki in Github and it just redirects to the main page for the repo.

Odd, i started a page here:

https://github.com/leeoniya/uPlot/wiki/Integration-Examples

**Comment by noobymcnoob** [comment]
> hey @mtfoley, thanks for the PR!
> 
> i'll try to explain my position on this to the best of my ability.
> 
> i'd like to avoid committing examples for integration with third party code. there are several reasons for this.
> 
>     1. i don't wan't to give the impression that i can or will offer assistance for interop with other code. this is a slippery slope and i don't have the resources (or knowledge) to explain more than the workings of uPlot itself.
> 
>     2. i would prefer if uPlot's audience was one that is proficient enough with JS to be able to browse the demos, read the provided `.d.ts` API and immediately see how to use uPlot for their use-case within their environment without needing trivial examples that would only be helpful to e.g. junior Vue devs. again, this filter tends to keep the issues technical and their reporters are typically able to produce minimal repro code without much guidance. if you look through e.g. Chart.js's issues, many of them are support questions - and they have waaaay more approachable and extensive docs than uPlot!
> 
> 
> i need to be able to say "look, this was a third party contrib and i cannot answer questions about it because i don't personally use <Vue|React|Angular...>". this is basically the litmus test for whether i want to accept code into the repo.
> 
> that being said, i think a Vue example could be ok to put into a wiki page here, and i can link to it from the README or docs without feeling obligated to support what's added there by others.
> 
> hope that makes some sense!

It's funny, I have made a Jupyter widget for uPlot and I didn't submit it for exactly that reason: I don't have the time to support it or put that burden on you.

**Comment by mtfoley** [comment]
The wiki page seems to work now so that’s great. @noobymcnoob and @leeoniya I am trying to become more of a contributor in OSS, so these perspectives are great. I certainly don’t have a repo that anyone makes use of but lessons like this will help if I ever do!
