### ISSUE TITLE
Customising Axis

### ISSUE THREAD

**Issue by indy-singh** [leeoniya/uPlot#209]
Hi,

Playing around with uPlot: https://plnkr.co/edit/6XUyri3Vvgs0N6yg?preview

I'm trying to match our current implementation of the same data that is graphed using Flot:-

![ref_flot](https://user-images.githubusercontent.com/1906778/81483656-b96ce700-9237-11ea-9fa5-c040748fc486.jpg)

Currently I'm stuck on:-

- Making "MEAN" axis _only_ display the mix and max values (from the data) on the axis
- Making "HITS" axis _only_ display the mix and max values (from the data) on the axis
- Making the "DAYS" axis _only_ have a tick on the first of each ~day~ month

Apologies if these are easy questions, I'm C# dev and don't really venture in JS land.

Thanks for any help!

Indy

**Comment by leeoniya** [comment]
hey Indy,

> Making the "DAYS" axis only have a tick on the first of each day

i'm assuming you meant the first of each month.

1. the easiest way to do this is to increase the minimum space required between axis splits `axes[0].space: 75` is sufficient for this chart's width and this range of data. this simple way of doing it is imperfect because it depends on the chart size and the dataset range. for example if you zoom, you will see higher resolution ticks.
2. you can instead make `axis.space` a function that computes and returns the minimum space dynamically, which is a bit more complicated but can accommodate all chart sizes and data ranges.
3. finally, you can go nuclear and define your own `axis.split` function to get full control of where to place each axis tick & gridline. this means you'll analyze the data between zoomed min/max and return the timestamps at which to split.

> Making "MEAN" axis only display the mix and max values (from the data) on the axis. Making "HITS" axis only display the mix and max values (from the data) on the axis.

i think option 3 from the list above would work well here since the determination is very simple:

https://plnkr.co/edit/M1ftdluk41mUbaCR

**Comment by indy-singh** [comment]
> I'm assuming you meant the first of each month.

Yes, sorry. The first day of each month is what I wanted.

> the easiest way to do this is to increase the minimum space required between axis splits axes[0].space: 75 is sufficient for this chart's width and this range of data. this simple way of doing it is imperfect because it depends on the chart size and the dataset range. for example if you zoom, you will see higher resolution ticks.

That is fine for now. I just want to benchmark what it is like rendering the data/graph via uPlot compared to Flot once I have a comparable uPlot representation. If we end up switching our of monitoring system to use uPlot, I can circle back to this.

> you can instead make axis.space a function that computes and returns the minimum space dynamically, which is a bit more complicated but can accommodate all chart sizes and data ranges.

Is there an example I could learn from in the demos?

Appreciate the response on the weekend - thanks!

Indy

**Comment by leeoniya** [comment]
this is pretty much it:

```js
space: (self, scaleMin, scaleMax, plotDim) => {
    let rangeSecs = scaleMax - scaleMin;
    let rangeDays = rangeSecs / 86400;
    let pxPerDay = plotDim / rangeDays;
    // ensure min split space is 28 days worth of pixels
    return pxPerDay * 28;
},
```

https://plnkr.co/edit/9YtJ5W4UuDzbzJAC

**Comment by indy-singh** [comment]
Awesome! Makes me life a lot easier.

Thanks,
Indy
