### ISSUE TITLE
Thanks for creating uPlot!

### ISSUE THREAD

**Issue by noobymcnoob** [leeoniya/uPlot#210]
I just finished doing a conversion of all of my charting code to uPlot from plotly. I use realtime candlestick charts in a semi-automated trading system where the requirements are complex.

Not only was I able to transfer a rather complex charting setup to uPlot but it is unbelievably fast. Charts redraw in milliseconds even when the entire dataset is changed.

When you deal with something day in and day out, the little things wear on you. Plotly was starting to do that for my use case (although it is a fantastic and flexible library, it is not that great for realtime work in my experience) and when I saw uPlot passed around on Hacker News, I had to check it out.

So I just wanted to say thanks for creating and publishing uPlot!

**Comment by leeoniya** [comment]
thanks for trying it out and the rave review!

would be cool to see a gif of the final thing in action.

the reason i prototyped uPlot wasn't even for speed, it was because i felt dygraphs' 122kb size could be made a bit smaller: https://github.com/danvk/dygraphs/pull/948. turns out i was right :) had that PR been merged, uPlot would likely not exist today.

cheers!

**Comment by noobymcnoob** [comment]
So many things are created because someone said it can't be done. :-)
