### ISSUE TITLE
Sync cursor with different time axes

### ISSUE THREAD

**Issue by EmiPhil** [leeoniya/uPlot#215]
Looking for a way to combine the brush (ranger) demo and the sync cursor demo so that when you highlight your cursor on one it is properly placed in the other.

Is this doable out of the box? If not, what hooks would you suggest using to achieve it?

In my use case the time stamps of the "bigger" chart should be a subset of those in the ranger if that helps at all.

Thanks!

**Comment by EmiPhil** [comment]
Adding a screenshot for more context in case it isn't super clear. The goal is for each of the Time values to be the same (or, if hovering in the ranger, then no time would be visible on the main chart if the ranger time is out of bounds of the main chart).

![Screenshot from 2020-05-11 15-01-48](https://user-images.githubusercontent.com/11808725/81612329-e5a07900-9399-11ea-8f17-ebcaebf1d899.png)

**Comment by EmiPhil** [comment]
So I was able to get this working (mostly, still some kinks...note that the times aren't quite the same). I can post code tomorrow because I'd still be interested in your thoughts on methodology. I had to stop using the sync feature to get it to work (probably rerolled a more specific version of it). For now here is an updated screenshot.

![Screenshot from 2020-05-11 17-04-44](https://user-images.githubusercontent.com/11808725/81620773-e8a36580-93a9-11ea-83f0-c63b5e9ed889.png)

**Comment by leeoniya** [comment]
hmm, interesting.

re-looking at the mousemove sync code (below), it uses the coordinate % along both x and y, so yeah you likely won't be able to use the native sync since it assumes matched x ranges.

we can prototype adding some option to `cursor.sync` to instead use the scale's value at the cursor position. the existing code already passes along the originating uplot instance, so it should be pretty easy to get this working. i guess we'd need to offer an x-scale and y-scale key to sync by:

`cursor.sync.scales: [xKey, yKey]`.

interested giving it the old college try?

https://github.com/leeoniya/uPlot/blob/b5fefa47977e79dd513009008e0ef62fc51411a3/src/uPlot.js#L1664-L1704
