### ISSUE TITLE
dynamic area for notes, legends

### ISSUE THREAD

**Issue by hz2018tv** [leeoniya/uPlot#226]
can we have a dynamic area for notes/legends/info ? it either finds an empty area within the plot itself or it is a box that user can drag to anywhere within the plot. right now, it is nice to have a floating tooltip, but sometimes it covers the curve section of interest. didnt seem to find such thing in the demos. more like a feature enhancement. thanks for the great work.

**Comment by leeoniya** [comment]
> it either finds an empty area within the plot itself...

there are no plans to offer collision or empty area detection.

> or it is a box that user can drag to anywhere within the plot....it is nice to have a floating tooltip, but sometimes it covers the curve section of interest.

if you don't want the tooltip, simply disable `legendAsTooltipPlugin()` and you will have the standard legend below the chart. you can also modify this plugin to make the legend draggable instead of following cursor. you can call it `draggableLegendPlugin`

https://github.com/leeoniya/uPlot/blob/43c16c9599aad4fd893266bad933160cf3be2360/demos/candlestick-ohlc.html#L262-L266

**Comment by hz2018tv** [comment]
tried to make the tooltip draggable, but seems to interfere with the zooming since the cursor is shared. guess eventlisteners of mouse is needed, havnt looked into the iife.js to see if other things would be effected.

**Comment by leeoniya** [comment]
you can try adding your own event listeners in the capturing phase (`useCapture)` [1], and selectively call preventDefault() if the target is draggable legend. this would prevent zoom while dragging.

[1] https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
