### ISSUE TITLE
How can I clear & empty uplot data?

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#232]
I have a simple, single plot. I often use uplot.setData() to switch the plot data without destroying & recreating the object.

Sometimes (due to data faults) I would like to remove all current series, data, etc. and expect uPlot to just show some kind of "empty space".

Following a different thread, I tried:

`u.batch(() => {
                u.delSeries(1)
                u.delSeries(0)
                u.redraw()
 })`
But I get a "TypeError: Cannot read property 'remove' of null". What am I missing here?

Ty

**Comment by leeoniya** [comment]
there was some [unreleased] work done in #217 to improve empty plot creation. though i'm not sure it would fix this specific case.

i'd like to get #216 wrapped up before reviewing more issues though.

**Comment by leeoniya** [comment]
ok, so what's going on in your case is that the series shift indices as they're deleted, and you cannot technically remove series[0], because that's the x data or timestamps.

you'll want to do something like this: https://jsfiddle.net/s8wn3vb0/1/

```js
u.delSeries(1);
u.delSeries(1);
u.redraw();  // not technically necessary, but may help release RAM
u.ctx.clearRect(0, 0, u.ctx.canvas.width, u.ctx.canvas.height);
```

you may also want to splice away the data as done here: https://github.com/leeoniya/uPlot/blob/master/demos/add-del-series.html#L73

so, it's a bit weird, but it makes sense. i'm not sure it's worth doing anything about the non-removable series[0] since it's not actually ever "drawn".

**Comment by leeoniya** [comment]
actually, what i think you're looking for is a variant of this: https://jsfiddle.net/9twvyr2L/

if you still want to show a grid instead of just empty space, you just need to set the scales manually, and then setData to `null`.

https://jsfiddle.net/7pm9htd2/

```js
u.batch(() => {
  u.delSeries(1);
  u.delSeries(1);

  u.setScale('x', {
    min: 1,
    max: 5,
  });

  u.setScale('y', {
    min: 1,
    max: 5,
  });

  u.setData(null);
});
```
