### ISSUE TITLE
TypeError when zooming between datapoints

### ISSUE THREAD

**Issue by archdragon** [leeoniya/uPlot#234]
An error that I've encountered when working on [LiveDashboard](https://github.com/phoenixframework/phoenix_live_dashboard)., but I think it makes more sense to describe it here. :)

Reproduced the error with following versions:
* v1.0.7
* v1.0.8
* Latest master

When trying to zoom in I sometimes encounter:

`TypeError: Cannot read property '2' of undefined`

Screenshot from the inspector:
![image](https://user-images.githubusercontent.com/1810732/82762411-2d46ec00-9e01-11ea-888e-727a7d61165f.png)

### How to reproduce (with phoenix livedashboard):

As far as I can tell this happens when trying to zoom (by selecting an area with the mouse) and the selected area does not include any datapoints. 

1. Open [LiveDashboard](https://github.com/phoenixframework/phoenix_live_dashboard)
2. Click metrics -> VM
3. Wait for a datapoint (or two) to load
4. Try zooming in in a space between datapoints

**Comment by leeoniya** [comment]
y auto-scaling ain't gonna work when there's nothing in the view to scale by.

you can either prevent zooming to locations with no datapoints by defining a custom `scales.x.range` or returning some fallback min/max in a custom `scales.y.range`.

https://jsfiddle.net/x8wsmg2a/

**Comment by archdragon** [comment]
Got it, thanks!

**Comment by hz2018tv** [comment]
I am getting those errors too sometimes. Shouldnt fixes go into the uplot lib to benefit all or it is up to each individual caller to make such check? works either way for me though.

**Comment by leeoniya** [comment]
> Shouldnt fixes go into the uplot lib to benefit all or it is up to each individual caller to make such check?

if there is a general solution that makes logical sense, has negligible perf impact, and minimal added core complexity, then definitely.

**Comment by hz2018tv** [comment]
agree. just from what I saw, it would make sense that the check happen in the uplot lib before zooming happens, then again, I am not versed enough in javascript to make that judgement, majority of my time were spent in the backend with python on data analysis, sometimes on the fromtend webpage for a change and refreshening.

**Comment by leeoniya** [comment]
this specific case was caused by `axis.values` customization (and reducuction of tick formatter resolution) without a corresponding reduction in `axis.incrs` resolution.

this is now handled by falling back to the highest-available formatter, which will now likely result in identical tick labels rather than an error.

in most cases it is still preferable to prevent those ticks from being generated by keeping `axis.incrs` and `axis.values` resolutions in sync. e.g.: https://github.com/leeoniya/uPlot/issues/200#issuecomment-624665712. (cc @danyalejandro)

@hz2018tv i don't know if your situation is related to this, but if you have a repro, i'll certainly take a look.

**Comment by hz2018tv** [comment]
updated to the latest repo, havent seen this error so far. actually I am not sure what triggers it, just noticed that using mouse wheel for zooming did it more, and it is hard for user to check data with mouse movement. thanks.
