### ISSUE TITLE
Pie / Donut

### ISSUE THREAD

**Issue by sausin** [leeoniya/uPlot#236]
Hello again,

I didn't want to clutter your thread (#107) about scatter charts which touches slightly upon donut / pie charts.

There wasn't anything in the documents regarding the plan (or not planned) for Donut / Pie charts. Is there a plan to include those?

Thanks!

**Comment by leeoniya** [comment]
uPlot really focuses on x/y type charts - specifically, high volume trends or histograms. for performance reasons alone, it uses canvas which i don't love having to use, honestly. i think that charts which do not have thousands of points are better and more easily done with svg. e.g. [1]. even the bars, candlesticks and box plots that uPlot does via demos/plugins are probably better done via svg, since you'll get free hover interaction, flexible styling, animation/transitions, accessibility, etc.

for the near term, i think uPlot will stay x/y only. even scatter plots are a bit of a stretch, because uPlot gives the first series, axis & x scale special treatment with the assumption that it's independent. this has to be ignored for scatter plots, which additionally need a dedicated spatial index for interaction and cannot get by with the current simple binary search.

i don't really see uPlot becoming a leaner/faster all-canvas Chart.js replacement, but serving more as an optimization when svg falls short on performance. if svg ever becomes fast enough, i'd love to rewrite uPlot in svg and then might consider adding other chart types.

[1] https://akzhy.com/blog/create-animated-donut-chart-using-svg-and-javascript/

**Comment by sausin** [comment]
Thanks for the info and providing the thoughts behind your decision, really appreciate it!
