### ISSUE TITLE
Hooks: array or single function?

### ISSUE THREAD

**Issue by ALEUT** [leeoniya/uPlot#238]
Hi @leeoniya 

I want to write my own plugin and looking at interface `Hooks` in the ts definitions, I see that all the hooks inside are arrays of functions, but in the examples I see plain functions without array. What is the correct format?

**Comment by leeoniya** [comment]
good catch.

all plugins get absorbed into `opts.hooks`, which are arrays of functions (as in the ts defs). due to the way hooks are merged *from plugins* (via array concat), they can technically be either in the returned object [1].

the reason i use non-arrays in the plugins is because i dont see why one plugin would ever define two of the same hook.

but you can use arrays in all cases if you prefer the uniformity.

[1] https://github.com/leeoniya/uPlot/blob/master/src/uPlot.js#L1868
