### ISSUE TITLE
snapshot of all cursor sync'ed plots

### ISSUE THREAD

**Issue by hz2018tv** [leeoniya/uPlot#240]
the default right-clicked context menu can probably take snapshot of the plot where cursor sits in. is there a way or solution to take a snapshot of all cursor sync'ed plots?

**Comment by hz2018tv** [comment]
right now, I have a <div></div> where I have an ohlc plot and a seperate vol bar plot that are cursor sync'ed for zooming. then I try to take a snapshot of the <div>. right now, I am using html2canvas, which works ok so far, but that mod is doing a canvas thing assuming you dont have one. since we are working with canvas already, is it possible to have a more "native" way to generate an snapshot image of all cursor sync'ed plots. open to all kinds of ideas.

**Comment by leeoniya** [comment]
the chart, grid & axes parts of are on canvas and the ohlc demo also draws the candles on this canvas.

you can get this image by using standard DOM apis for each `u.ctx.canvas`:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

however, all the interactive parts (cursor, legend/tooltip, selection region, hover points, column highlight) are in the DOM for performance and styling flexibility reasons.

to capture these you would need to draw them on canvas, too. i think a plugin which does this with some known/basic layout & style might not be too difficult and if you want to give it a shot, a PR would be great. but if you're trying to reproduce literally what you see, you would end up just recreating html2canvas.

i dont have any plans to move everything to canvas since that means i'm now responsible for layout, styling customization and a bunch of other concerns that are already addressed very well by html & css.

**Comment by hz2018tv** [comment]
understand. so if I only need basic charts, not cursor/tooltips/legend etc, my codes look like
< div id='uplot_chart' >< /div>
then I did

elE=document.getElementById('uplot_chart');
let uplot1=new uPlot(opts1,data1,elE);
let uplot2=new uPlot(opts2,data2,elE);

then how many canvas(es) are used in this way? and what is the best way to get to the canvas element? Thanks.

**Comment by leeoniya** [comment]
here's how to draw 2 canvases onto another bigger canvas: https://jsfiddle.net/g8zLv6b2/

in your case:

```js
let can1 = uplot1.ctx.canvas;
let can2 = uplot2.ctx.canvas;
```

**Comment by hz2018tv** [comment]
thanks, this is what I thought. will have to create a new canvas to blend can1 can2 in. looks like that I can not get away with a new canvas :D
