### ISSUE TITLE
Use mouse to move shift the plot horizontally from left and right

### ISSUE THREAD

**Issue by glomarch** [leeoniya/uPlot#243]
Is it possible to shift the whole plot from left to right after the plot is magnified.  It is a very important feature of the fast graph.  If it is implemented, it can display large data sets in great detail such as candle and stick chart for displaying financial data.

**Comment by leeoniya** [comment]
panning and drag-to-zoom obviously cannot work at the same time. i will make a demo for panning and maybe make it work with the wheel-zoom plugin rather than drag-zoom.

there's no way to control zoom behavior on-demand, so it might be difficult to get the exact behavior you want, where the zoom auto-disables at a specific point and switches to panning.

do you have an example chart in mind which behaves the way you describe?

also, have you seen uPlot's zoom-ranger (brush) demos?

**Comment by EmiPhil** [comment]
I've had experience with some charts where shift (or whatever) + drag will pan/zoom depending on if normal drag is pan/zoom.

Never seen a chart that auto switches after a zoom though. If you are going to do that I think you would need to telegraph the user of the change with a change in mouse cursor. I don't really like the sound of that behavior though.

I could imagine a pan/drag default setting and a keyboard code setting to switch between the two being doable.

And pan on a chart with `setSelect = false` would move the drag area I think. (Though in that particular case I have seen it where if you hover into the brush's selected area the default becomes panning)

**Comment by EmiPhil** [comment]
Actually I think space is the standard to pan. At least in drawing / photo editing applications

**Comment by EmiPhil** [comment]
I think we could support this kind of stuff really elegantly by providing a `setMode()` function where `mode` is either `drag` or `pan` or others (maybe `draw`) or maybe even a callback function that allows other implementations.

Then a user can bind a space key press to `setMode('pan')` and bam they are in control. And we don't have to think about nitty gritty like is it a toggle or a while holding etc etc. Added benefit that it would support @glomarch 's initial request because you could hook into the `setSelect` and call `setMode('pan')` in there and you would achieve the auto switch over.

**Comment by leeoniya** [comment]
i'm definitely against any kind of auto-switch behavior.

i don't think panning should be in the core because it adds behavior which does a full redraw on mousemove and would lead to a setting which can be very slow for large datasets. in fact, i explicitly state this in https://github.com/leeoniya/uPlot#non-features.

a panning plugin would be very simple to make - certainly much simpler than the touch/pinch-zoom & pan demo.

disabling drag on-demand e.g. `setCursor({drag: {x: false, y: false}})` might be okay, but can also be done with adding a capturing listener to the `.over` which intercepts and cancels the mousedown events, which would have the same effect.

**Comment by leeoniya** [comment]
@EmiPhil if you wanna take a stab at a panning demo and/or plugin, that would be cool :). i think that should be enough to close this out. i know you probably wanna take care of caterpillar squashing tho.

**Comment by EmiPhil** [comment]
I wouldn't mind working on a panning demo actually. Getting the identity functions implemented might take a while because I'd be working on something a bit deeper than my skill set (or maybe not, I don't really know) -- and ctrl+f round -> delete is a working hack to squash them 😂 

Not sure what you mean by wheel-drag exactly, but if I was to implement a pan demo I would want to bind panning to the space key cause that's the style I know. Though even just thinking about it briefly I can see how that could get hairy really quickly

**Comment by milahu** [comment]
> i don't think panning should be in the core because it adds behavior which does a full redraw on mousemove and would lead to a setting which can be very slow for large datasets. in fact, i explicitly state this in https://github.com/leeoniya/uPlot#non-features.

stupid idea: take a screenshot of the graph and drag only that picture (GPU texture, zero cost)

**Comment by leeoniya** [comment]
you can't really take a screenshot of something that's not drawn (out of the scale range), so this would mean rendering all data all the time, which has its own perf issues, of course. there are other reasons for not having this native, mostly because it interferes with native zoom, otherwise we'd need to add visible controls for switching between the two somehow. zoom can be used as a poor man's pan, but pan cannot be used as a poor man's zoom, so think it'll stay out of the core for now.

it seems to work just fine for 100k+ datapoints, see: https://github.com/leeoniya/uPlot/issues/329
