### ISSUE TITLE
investigate potential cursor regression

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#254]
spotted in:

https://github.com/astashov/liftosaur/commit/c244fc8f5528f61bf7a57124771766ae4a585e9c
https://github.com/Cryptkeeper/Minetrack/pull/179#issuecomment-640905192

cc @Cryptkeeper @hugmanrique @astashov

any repros and/or screencaps of before/after would be helpful.

**Comment by Cryptkeeper** [comment]
I have no before comparison since I've only tried to initially implement it now and only then noticed the offset. 

I assumed the issue was stemming from [my re-implementation](https://github.com/Cryptkeeper/Minetrack/pull/179/files#diff-80ba9ad3ca632d96d6dfe818cc983d7cR141) of uPlot's `#getYPos` (https://github.com/leeoniya/uPlot/blob/master/src/uPlot.js#L122) to enable a custom form of the `distsToCursor` calculation (https://github.com/leeoniya/uPlot/blob/master/src/uPlot.js#L1599-L1612). However the distances weren't predictable. 

I've attached a screenshot of my cursor location (red dot) and the distances generated. Somehow the green line is considered closer than the purple line the cursor is next to.

<img width="120" alt="cursor_location" src="https://user-images.githubusercontent.com/5879679/84220840-6f2a9000-aa99-11ea-8125-9f1f27b6f7f0.png">

Purple distance = 36.6
Green distance = 19
Blue distance = 125

Again, I assume this issue is me trying to recreate internal behavior and missing an offset or referencing the wrong data point. Input welcome! ❤️

**Comment by Cryptkeeper** [comment]
I've managed to resolve the issue, I was using the `uPlot.height` field which was returning 400 whereas the actual plotting area was only ~330. 👍

**Comment by leeoniya** [comment]
you can read back the plotting area rect from `u.bbox` which will give you canvas pixels. if you need css pixels you'll have to divide those by `devicePixelRatio` (just in case the browser is zoomed or display is dpi-scaled)

**Comment by Cryptkeeper** [comment]
That's actually what I cooked up, glad to know I picked the right switches. Thanks for the help! :)

**Comment by Cryptkeeper** [comment]
Just to confirm, my experience with this issue was implementation error and has been fixed.
