### ISSUE TITLE
.setScale(key, {show: false})

### ISSUE THREAD

**Issue by danekasper** [leeoniya/uPlot#264]
If axes[i].show is set to true after plot has been drawn and then uplot.redraw() or uplot.setdata(..) to reload plot received error that axis.space is not a function. This makes sense as initAxis is never set on the axes as it was initially set as false and it makes sense not to initiate these if aren't used. 

My desired behavior is to give a user optional axis (mainly dependent scales) that can be shown or hidden. 

The more I've looked into it, it seems like the fix is just to remove the uplot and call a new one. Which I'm probably fine with as I don't want to spending time on this instead of log/log plots 😋!

**Comment by leeoniya** [comment]
heh, yeah. those axis opts arent really meant to be toggled post-init; they're really there to turn *off* the default axes. does it work if you create the chart with the dependent axis shown but then do `u.axes[i].show = false; u.redraw(false);` immediately post-init (this will probably be too fast to ever see it drawn). then afterwards you can repeat the same thing without chart recreation (i think).

**Comment by danekasper** [comment]
While `u.axes[i].show = false; u.redraw(false);` does work, white space remains in the place of that axis. The white space is acceptable if there is only one axis on either side, but if you have 3 hidden axes and only show the u.axes[3] then you'll get a lot of white space on that side. 

My work around to set the opts.axes based on a given user defined axes object, destory uplot, and then replot is working okay for my 40k points (I guess only thanks to uplot being fast and efficient). 
`setAxes(axes); uplot.destroy();    uplot = new uPlot(opts, data, plotDiv); uplot.setSize(getSize());` 

I would agree with you toggling log scale on/off is nice to fiddle with, but, generally the data dictates if it should be Log or Linear from the beginning. 

Happy for you to close this issue.

**Comment by leeoniya** [comment]
i'm open to having a `.setAxis(i, {show: false})` if it ends up not being too much extra code. i think most of the tricky chart dim re-calc work needed for this was already factored out during the `.setSize()` impl.

as a bonus this can enhance the behavior of turning off all series along a scale. right now the axis just turns off and leaves the whitespace but it would be better for the plotting area to re-adjust.

**Comment by leeoniya** [comment]
actually this needs more thought. it's not axis toggling but scale toggling because simply removing an axis but continuing to show data on a now-unlabeled scale is rather pointless.

effectively this has to be part of setScale({show: false}) which would have the effect of turning off all series on that scale, hiding axes on that scale and re-sizing the plotting area to take up the empty space.

i would say all of this is just equivalent to making the default behavior of turning off all series on a scale also call setSize() when the axis becomes hidden due to nothing being shown along this scales. howver, your dependent scales case throws a wrench into this, since it needs to be explicitly disabled and almost never has series directly using it.

**Comment by leeoniya** [comment]
for your case, i would probably just have a toggle for the type of y scale you want and simply convert the data to that scale and use `setData()`. you can use a custom `axis.values` to decorate the rendered values with `° C` or whatever based on the toggle state. this will be the most performant option, will avoid having to recreate the chart, and will also avoid wasting space for a secondary axis.

**Comment by danekasper** [comment]
That's interesting, so you think converting the data will have better performance than recreating chart? I agree that perhaps that suggestion is a better option for my case, as it is a bit strange if you select `° C` but `° F` is still showing as a series. 

I think .setScale(key, {show: false}) would be a good enhancement, and setting it should hide all dependent scales too.

**Comment by leeoniya** [comment]
> and setting it should hide all dependent scales too.

that's something that might really limit its usefulness, doesn't it? so if C depends on F, then you can toggle C which just has the effect of toggling the axis. but if you toggle F, then it takes all series and C with it? that's not terribly intuitive behavior from a user perspective, imo.

i think the reserved-axis-region collapsing behavior (to be taken up by a resized plotting area) is worth addressing, but otherwise toggling a scale is the same thing as toggling off all the series using it. i still have to see how much is involved in adjusting all the offsets dynamically - it may not be worth it for such a small improvement.

> That's interesting, so you think converting the data will have better performance than recreating chart?

for sure. pure math is very fast as is allocating memory for a 40k numeric array (unless you're re-allocating the whole array at 60fps). pre-computing the alternative 40k data array and just caching it in memory will be *way* cheaper than mutating the dom to re-init the plot, which also forces the browser to re-compute layout, GC the freed memory and other expensive stuff.
