### ISSUE TITLE
Demo request: syncing cursor and time of multiple charts with possibly different time scales

### ISSUE THREAD

**Issue by b4git** [leeoniya/uPlot#267]
Hi, there is a sync cursor demo for multiple charts where all have the same time axis interval. However, would you please also post an example demo code or jsfiddle for multiple timeframes synchronization as well? 

For example: say we have 4 charts with time axis intervals  of 1 minute, 10 min, 1 hour, 8 hour respectively, then what we want to achieve is that when the mouse  is moved over in any one of the charts, we want to automatically sync the time and automatically scroll to the new time if needed. To elaborate, if in 10 minute interval chart, the cursor is moved towards 1:30 PM from 1:20 PM. Then halfway through, 1 minute chart will now show cursor at 1:25 PM, 1 hour chart will show cursor in the middle of 1 PM and 2PM, and 8 Hour chart will also adjust accordingly. If the time is not in visible range (for example due to previous zooming or scrolling etc.), then the charts will also auto scroll so that the current cursor location is visible (possibly better to maintain the previous zoom level).

Hope he description makes sense.

**Comment by leeoniya** [comment]
this is possible but will require some code. the sync sync can be done by x/y coordinates or by matching scale. the ranger demo [1] does sync by scale (which requires matched timestamps but could be different ranges).

the auto-scroll behavior you want will need to hook setCursor events and figure hout the appropriate range for each chart. i will probably leave this part up to you.

i will need sample dataset from you for each of the 4 charts.

[1] https://leeoniya.github.io/uPlot/demos/zoom-ranger.html

**Comment by leeoniya** [comment]
i read your original question again, and i actually think that situation is already mostly handled.

it's not so much time axis intervals as it is datapoint intervals. in the example below, the red chart is 100 datapoints spaced every minute (a "detail" view). the blue chart is the same period with datapoints every 10 minutes (some "aggregated" view). i pre-zoomed the middle 50 datapoints for the red chart and synchronized the cursors. you can instead provide a reduced data range instead of pre-zooming and it will work the same but your "scroll-into-view" code will have to use setData() rather than setScale().

you can see that moving the cursor in one chart will properly position it in the other, even though the data is sampled at different intervals. you can additionally customize the axis tick granularity if you need, which i have not done here.

https://jsfiddle.net/Lkj13e7t/

**Comment by b4git** [comment]
@leeoniya Thank you for putting up the demo code. I just checked GitHub now, so I didn't see your initial comment earlier otherwise I could have uploaded a sample dataset you requested. The example code and comment you posted above does provide enough guidance for now. Thanks again.

**Comment by leeoniya** [comment]
i'll close this for now, but feel free to continue the convo here, if needed.
