### ISSUE TITLE
uPlot.setData with resetScales=false does not update plot

### ISSUE THREAD

**Issue by kele14x** [leeoniya/uPlot#268]
Hi this issue is observed when I want to plot streaming data without reset scale each time the plot is update. I use `uPlot.setData` function with second parameter `resetScales=false`. However, the plot is not update. The plot will only update once I double click the plot to "reset scale".

**Comment by kele14x** [comment]
Forgot the mention that I'm using uPlot v1.0.11 release.

**Comment by leeoniya** [comment]
hey @kele14x 

this is by design, though the i guess that argument name can be somewhat confusing. the way that uPlot "redraws" is in fact to re-set its own "x" scale internally, which causes invalidation and re-calc of all `y` scales. setData() additionally expands the x scale range to accommodate the full range of the new data. so, the arg might be better called `resetAndRedraw`. before, this arg was called `autoScaleX`.

`resetScales=false` is a way to opt-out so you can defer the expensive `.setScale('x') -> .redraw()` and call setScale->redraw or just redraw manually or granularly, e.g. setting the scale to something other than full new data range. for example:

https://github.com/leeoniya/uPlot/blob/ee065f6022c6380dbc5e8389260ea334e47c318e/demos/zoom-fetch.html#L51-L58

while it's possible to split the two concerns by expanding the API to `setData(data, resetScales, redraw)`, this would not feel great to me: `setData(data, false, true)` has too many boolean params.

i would recommend either calling `u.redraw()` explicitly after `.setData(data, false)`, or provide e.g. `scales.x.range` which would revert setData's scale auto-expansion & fixate the range you need, as is done in the third streaming demo:

https://github.com/leeoniya/uPlot/blob/ee065f6022c6380dbc5e8389260ea334e47c318e/demos/stream-data.html#L179

hope that helps clarify the behavior.

**Comment by kele14x** [comment]
Hi @leeoniya , thanks very much for your explanation. I got understand the design. I will use `uPlot.redraw()` after `.setData()`.

**Comment by Kheirlb** [comment]
For future people that are using uPlot with React and the defaulting zooming options, copying the current scales worked for me.
```
      const xScale = plotRef.current.scales.x;
      const yScale = plotRef.current.scales.y;
      plotRef.current.setData(data, false);
      if (xScale?.min && xScale?.max && yScale?.min && yScale?.max) {
        plotRef.current.setScale("x", { min: xScale.min, max: xScale.max });
        plotRef.current.setScale("y", { min: yScale.min, max: yScale.max });
      }
```

leeoniya, if this is bad practice or anything, let me know. redraw() was not working for me.
