### ISSUE TITLE
cursor.snap

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#269]
so that the cursor only moves to exact x indices.

would be useful to add this mode, since visually it's more obvious than just noticing the cursor points snapping.

the whole updateCursor should be conditioned on the index changing, similar to legend updates:

https://github.com/leeoniya/uPlot/blob/ee065f6022c6380dbc5e8389260ea334e47c318e/src/uPlot.js#L1622-L1623

cc @EmiPhil

**Comment by leeoniya** [comment]
i did a quick prototype of `cursor.snap: true` in https://github.com/leeoniya/uPlot/tree/cursor.snap.

some general thoughts:

it's a bit odd to have a crosshair cursor snap in the x direction (to the datapoints), but act smoothly in the y direction, but i guess there's not much to be done about that. maybe if `snap: true`, the `setCursor` hook should not fire unless the snap location changes? dunno.

i don't particularly like the purpose-specific nature of a `snap: true` API, since it should be possible to snap generally, and not specifically to data but to arbitrary points on a scale, if these points happen to come from data then so be it.

i think a general `cursor.snap` API would look something like below, where we snap to the returned values on along the indicated scale.

```js
cursor: {
    snap: {
        x: {
            scale: 'x',
            values: self => self.data[0],
        },
        y: {
            scale: 'myScale',
            values: self => [2,4,6,8,10],
        },
    }
}
```

**Comment by ScottKevill** [comment]
> it's a bit odd to have a crosshair cursor snap in the x direction (to the datapoints), but act smoothly in the y direction, but i guess there's not much to be done about that. maybe if `snap: true`, the `setCursor` hook should not fire unless the snap location changes? dunno.

I had a play with this, and agree it doesn't feel natural with the smooth y-direction. However, snapping the X-direction and then snapping the Y-direction to the closest series data point from the X snap does feel very intuitive, at least on the Area Fill demo. So much so that it feels like it could be the default behaviour.

Undecided when it comes to gaps though, eg. the Nearest Non-Null demo. Each time I try it, I change my mind. It feels acceptable as above, but could probably only be improved by a 2D min-distance search.

> i don't particularly like the purpose-specific nature of a `snap: true` API, since it should be possible to snap generally, and not specifically to data but to arbitrary points on a scale, if these points happen to come from data then so be it. a general `cursor.snap` API would look something like below, where we snap to the returned values along the indicated scale.

Alternatively, rather than returning values, a user-provided function could return the distance, and point (not necessarily related to the distance) to snap to if that distance ends up being closest. Composable with multiple sources then, and the user could use arbitrary geometry or logic without having to assume a spherical cow. (Similiar to the way simple ray-tracers / ray-casters sort a list of ray-object intersection points as distance along the ray to determine the closest hit.)

If uPlot were going to compose/sort/min multiple sources anyway, the user-provided function may be better to return a list of (distance, snap-point) tuples instead of just one.

**Comment by leeoniya** [comment]
TBH, i'm not terribly happy with my hacked-in snap implementation because it relies on faking the mouse position and doing the nearest-index calc in the unthrottled `mousemove`. uPlot does in fact keep track of the nearest series points but it does this *afterwards* in rAF-throttled `updateCursor`.

ideally the whole thing would be in `updateCursor`, but it would introduce a bit of a circular logic of updateCursor calling itself to snap, so would requires setting/unsetting some flags. if this can be moved into updateCursor, i think we can pass or expose the internal `distsToCursor` to an user-supplied callback which can then control the snapping.

i'm not sure i want to provide a completely arbitrary snapping capability beyond this, though i haven't given it too much thought.

**Comment by ScottKevill** [comment]
Yes, there is some circular logic to untangle. Maybe there were other plans for it, but `distsToCursor` doesn't actually get used other than for the min value for focusing the closest series, and it gets rebuilt every time even when `cursorFocus` is not enabled.

For my PoC, I added extra code into `cacheMouse` semi-ripped from `updateCursor`, but didn't use an array:
```

**Comment by leeoniya** [comment]
> Maybe there were other plans for it, but `distsToCursor` doesn't actually get used other than for the min value for focusing the closest series, and it gets rebuilt every time even when `cursorFocus` is not enabled.

yeah that's a good point. i don't recall and cannot think of another use for maintaining the whole array. might just be a leftover from a prototype where i wanted to inspect the array as a whole. as for being updated each time, JITs are finicky things and often re doing simple math is cheaper than adding a logical branch in a hot path. 2ae716a430c2d92da77403adbdba52408a34116f simplifies this and also takes care of a yet-to-be encountered bug since i forgot splice the `distsToCursor` array as part of the add/delSeries() apis; the simplified route no longer requires this.

> For my PoC, I added extra code into cacheMouse semi-ripped from updateCursor, but didn't use an array:

i want to avoid doing anything extra in the unthrottled `cacheMouse()`, if possible. i think adding something like a user-supplied `maybeSnap(self, mouseLeft1, mouseTop1)` at the top of `updateCursor()` and allowing it to return a new `[mouseLeft1, mouseTop1]` would be a sufficient low-level API to basically get everything else done externally to the core. then we can iterate on some simple 90% use case for exposing the snapping functionality via opts more declaratively.

**Comment by leeoniya** [comment]
a4ac82e147fd3a808ac5c066c0d95a5d3d92c342 implements a simple `cursor.move()` API which can be used to snap the cursor position.

demo of an arbitrary snap to 10x10 grid: https://leeoniya.github.io/uPlot/demos/cursor-snap.html

**Comment by ScottKevill** [comment]
I like it! But there's a problem that's a little hairier than it first appears.

To see it more easily, change the snap grid to 100x100. Now click between grid-snaps and start to drag. The current mouse location is snapped, but the drag-start location is not.

Adjusting the drag-start with `cursor.move(self, mouseLeft0, mouseTop0)` reveals a second problem that can be seen more easily with `cursor: { drag: { dist: 25 } }`.

The drag-start is now snapped correctly, but the effect of `cursor.drag.dist` is less obvious because it's tested against the snapped coordinates. If you click the exact centre between grid-snaps, a drag-select requires a raw distance of only 1 because the snapped drag distance becomes 100. So the minimum drag distance needs to be tested against both of the raw, unmoved mouse locations.

**Comment by ScottKevill** [comment]
Sigh. Though I am fairly sure this is the "technically correct" behaviour, it still _feels_ weird, because it's two different kinds of snap combined.

I suspect when combined with `cursor.move` it will feel more natural to allow the drag to start, but ignore the result if the raw drag distance is less than the minimum at the time of mouse-up.

**Comment by leeoniya** [comment]
> Though I am fairly sure this is the "technically correct" behaviour,

that's the best kind of correct :)

> it still feels weird, because it's two different kinds of snap combined. I suspect when combined with cursor.move it will feel more natural to allow the drag to start, but ignore the result if the raw drag distance is less than the minimum at the time of mouse-up.

honestly, the more i use cursor snapping, the less i like it. i'll leave it in since i'm sure there are creative/valid cases for it out there, but i think it would feel more natural to snap the selection and/or another indicator without ever snapping the cursor itself, e.g. the columnHighlight in https://leeoniya.github.io/uPlot/demos/candlestick-ohlc.html. to me, the crosshair cursor serves 2 important purposes:

1. dropping a guide down to the axis so you can more accurately eyeball position on the scale where there are not ticks or datapoints.
2. comparing geometrically distant peaks or valleys in the trendlines to eyeball equivalence when they don't fall near a tick or gridline.

neither of the above can really be done effectively when snapping a cursor to datapoints or a fixed grid.

the original reason i opened this issue (in the first comment) is to make it more apparent when the datapoints shift and the legend updates. while a snapped cursor accomplishes this, you end up with some "interesting" and potentially disorienting side-effects. IMO the column-highlight or another additional indicator provides the best of both worlds.
