### ISSUE TITLE
Static scaling options not working on live chart?

### ISSUE THREAD

**Issue by mmben** [leeoniya/uPlot#274]
I'm working with v1.0.11 and have setup a chart where the x and y scale use a static ~~range~~ scale, e.g:
`let opts = {
  scales: {
    "x": {
      time: false,
      auto: false,
      range: [0, 100]
    },
   "y": {
      auto: false,
      range: [0, 100]
    },
  },
}`

This works fine until I try to zoom and update the data.
To do that, I call e.g. ~~`setRange('y', { min: 4, max: 10})`~~ `setScale('y', { min: 4, max: 10})`.
When I now call `setData` on my chart instance, it resets my previously set scale.

I also noted, that the API documentation states that there is a second parameter on `setData` allowing to 
prevent this behavior, but when I do that, it not only does not reset the scale, it also does not redraw anymore.
```
/** sets the chart data & redraws. (default resetScales = true) */
setData(data: uPlot.AlignedData, resetScales?: boolean): void;
```
I would have expected that it would accept the data and redraw it on the existing scaling.

The only way I could find to get the desired behavior so far was to set the data and then fix the scale, e.g.:
```
setData(myData, false);
setScale('y', { min: 4, max: 10})
```
But this can't be the way it should be, can it?

I think the streaming-data demo has the same issue. Even though zooming seems to be possible, it doesn't work.

**Edited**: Corrected the wrongly used: 'setRange' to what I actually meant: 'setScale'.

**Comment by leeoniya** [comment]
this has come up recently in https://github.com/leeoniya/uPlot/issues/268.

i assume by `setRange()` you mean `setScale()`.

> But this can't be the way it should be, can it?

as described in the linked issue, this is how it is right now.

it might help to understand that uPlot does not store any knowledge that you provided a static range because during init it simply transforms your `[0, 100]` into `() => [0,100]`. without knowing that you want a static range, there are fewer assumptions that can be made about what the fully unzoomed scale is. also, uplot does not really have a concept of zoomed or unzoomed, all it does it scan your data to find the scale limits (if auto: true).

i'm certainly open to discussing and refining how this works as long as it can be clear without a lot of built-in assumptions and additional scale <-> data interdependency. the current API allows for complete flexibility and control and anything additional should be carefully considered to avoid difficult to explain magic for specific cases.

> I think the streaming-data demo has the same issue. Even though zooming seems to be possible, it doesn't work.

i'm open to improving the streaming demos to support zooming capability, which is easily possible with the current API. you would need to store some "isZoomed" variable in the demo code per chart and then conditionally use setData/false and optionally setScale is isZoomed is false. the reason i did not include it is because it would complicate the demo a bit.

discussed previously: https://github.com/Cryptkeeper/Minetrack/commit/6aeb8b5045176cb1b2eacaee3801413c002ac82c#r39869985

as i said, i'm all for improving the default behavior where it makes sense if it does not impact the ability to do full customization with decoupled concerns.

it would be helpful to make a jsfiddle to work out the exact behavior you need and work through any API change ideas. the current behavior is definitely biased towards the non-streaming case where setData will auto-range x to the new data. otherwise, if the x scale was unaffected by setData and you were zoomed, people would think there was a bug because they forgot they were zoomed and the new data was out of range, resulting in no visible setData changes.

**Comment by mmben** [comment]
Thanks for the quick and detailed answer, Leon.

> it might help to understand that uPlot does not store any knowledge that you provided a static range because during init it simply transforms your [0, 100] into () => [0,100].

That a was brilliant guess as it solved my problem. 
I changed my options to providing an arrow-function instead of actual values:
```
let rangeX = [0, 100];
let rangeY = [0, 100];

let opts = { 
   scales: { 
      "x": { 
         time: false, 
         auto: false,  
         range: () => { return this.rangeX; },
      }, 
      "y": { 
         auto: false, 
         range: () => { return this.rangeY; } 
      }, 
   }, 
}
```
With this change, I don't need use the 'resetScaling' arg on `setData()` anymore in combination with a following call to `setScale()` or `redraw()`. I can simply call `setData(myData)` and that scales as desired.

However, `setScale()` does not work at all in this scenario. So to change my scale I set my range and ask uplot to redraw as I now know that this will reset the scale as desired via the arrow-function in the options. 
```
this.rangeY = [4, 10];
uplot.redraw();
```
I don't know, but this feels mighty awkward. I don't really see why `setScale()` does not update the options range in case the user has also opted for `auto: false`. 

> the current behavior is definitely biased towards the non-streaming case where setData will auto-range x to the new data. otherwise, if the x scale was unaffected by setData and you were zoomed, people would think there was a bug because they forgot they were zoomed and the new data was out of range, resulting in no visible setData changes.

If you actively set the x scale to `auto: false`, provide a range or `setScale()` and then forgot that you were zoomed, then you clearly don't know what you're doing.

The current API seems inconsistent to me. I opt for `auto: false` on the x-axis, but it automatically scales anyways.
But that's just my personal opinion. I can still do what I need to, so thanks again for your help.

**Comment by leeoniya** [comment]
> The current API seems inconsistent to me. I opt for `auto: false` on the x-axis, but it automatically scales anyways.

this is a good point and i'll take a look at this. the original thought for `auto` was "does it scan the data to find the scale range". since `x` was always manually zoomed, it is actually defaulted to `auto: false`: https://github.com/leeoniya/uPlot/blob/master/src/opts.js#L453-L459

but as you point out, setData behaves as if x `auto: true` since by default it will expand to the data limits. so really the x default should be `auto: true` as well, and it should respect whatever setting it actually is. `auto: true` does not prevent setting the scale manually, it just tells uPlot to analyze the data limits in cases when the scale is not explicitly specified. it is also an optimization when you have potentially 100k datapoints, but know the limits in advance, so uPlot does not need to scan the whole dataset.

`axis.range` is best thought of as a range `adjuster` in that it can define or *refine* a scale. when `auto: true` it will scan your data and pass what it found to `axis.range` for further refinement. so in your case, you probably want to leave `auto: true` and then use range to further restrict what happens.

you may find reading #187 helpful, particularly this example: https://jsfiddle.net/x8wsmg2a/. also #223.

**Comment by mmben** [comment]
> the original thought for auto was "does it scan the data to find the scale range?".

...and that's what it should do. I also agree when you say:

> so really the x default should be auto: true

This would match the current behavior much better. 

> and it should respect whatever setting it actually is. auto: true does not prevent setting the scale manually, it just tells uPlot to analyze the data limits in cases when the scale is not explicitly specified. it is also an optimization when you have potentially 100k datapoints but know the limits in advance, so uPlot does not need to scan the whole dataset.

I also agree with that. 
When `auto: true`, then uPlot is in charge of scanning the data and set the scale. It could respect the limitations, when a 'range' is provided (as you said: let the range act as adjuster and 'refine' the scale). When `auto: false`, it should not need to scan as I have explicitly opted out on it. Useful as optimization of the already awesome performance. The only special case I can think of, is when you set `auto: false` but don't provide a 'range'. Then uplot probably needs to scan the data to determine the bounds of the plot.

Thanks for being open to this kind of discussion. 
Keep up the great work you do!

**Comment by leeoniya** [comment]
i pushed a few commits, but they'll make little difference for the streaming case.

the whole thing is pretty nuanced because for streaming you *may* want x.auto: true, but only when "zoomed out". there are a lot other behaviors you may need, and simply relying on auto is insufficient for a zoomable streaming case - you still need to do a custom range and call setData/false & setScale granularly because there's not one solution i can think of that is sensible for everyone given the vast array of options that can be active.

**Comment by leeoniya** [comment]
gonna close this since i'm not sure there's anything left to do here, but feel free to discuss further if necessary.
