### ISSUE TITLE
Typings for axis.values not complete

### ISSUE THREAD

**Issue by Joelius300** [leeoniya/uPlot#284]
I've been using this library with angular and therefore with typescript. It's working great but for localization purposes I assign fixed values to my time-axis. I do this by assigning an array of arrays with 4 entries (5 work too) which will get read and understood by `initAxis` (see [this line](https://github.com/leeoniya/uPlot/blob/64a367ba96dc258ece6214bdd6aefa31cb265e95/src/uPlot.js#L466)). It's the same data structure as the default [`_timeAxisStamps`](https://github.com/leeoniya/uPlot/blob/64a367ba96dc258ece6214bdd6aefa31cb265e95/src/opts.js#L133).  
Unfortunately, the only place I found this documented is in the code [above `_timeAxisStamps`](https://github.com/leeoniya/uPlot/blob/64a367ba96dc258ece6214bdd6aefa31cb265e95/src/opts.js#L128-L132).

That's still fine but in the [type file](https://github.com/leeoniya/uPlot/blob/64a367ba96dc258ece6214bdd6aefa31cb265e95/dist/uPlot.d.ts#L423) it only says 
```ts
(self: uPlot, splits: number[], axisIdx: number, foundSpace: number, foundIncr: number) => Array<string|number>
```

when I believe it should be
```ts
((self: uPlot, splits: number[], axisIdx: number, foundSpace: number, foundIncr: number) => Array<string|number>) | (string | number)[][]
```

Considering the _mode_ (the `0: replace [1] -> [3], 1: concat [1] + [3]` thing) in [`timeAxisStamps`](https://github.com/leeoniya/uPlot/blob/64a367ba96dc258ece6214bdd6aefa31cb265e95/src/opts.js#L109) is done with a truthy-check, one could even argue that it should be `(string | number | boolean)[][]` instead of `(string | number)[][]` because this
```
[3600 * 24 * 365,   '{YYYY}',           7,  '{YYYY}',                     false],
[3600 * 24 * 28,    '{MMM}',            7,  '\n{YYYY}',                   true ],
[3600 * 24,         '{DD}.{MM}',        7,  '\n{YYYY}',                   true ],
[3600,              '{HH}',             4,  '\n{DD}.{MM}',                true ],
[60,                '{HH}:{mm}',        4,  '\n{DD}.{MM}',                true ],
[1,                 '{mm}:{ss}',        2,  '{HH}:{mm}:{ss}\n{DD}.{MM}',  false],
[1e-3,              '{mm}:{ss}.{fff}',  2,  '{HH}:{mm}:{ss}\n{DD}.{MM}',  false]
```

seems more semantically correct **(to me)** than this
```
[3600 * 24 * 365,   '{YYYY}',           7,  '{YYYY}',                     0],
[3600 * 24 * 28,    '{MMM}',            7,  '\n{YYYY}',                   1],
[3600 * 24,         '{DD}.{MM}',        7,  '\n{YYYY}',                   1],
[3600,              '{HH}',             4,  '\n{DD}.{MM}',                1],
[60,                '{HH}:{mm}',        4,  '\n{DD}.{MM}',                1],
[1,                 '{mm}:{ss}',        2,  '{HH}:{mm}:{ss}\n{DD}.{MM}',  0],
[1e-3,              '{mm}:{ss}.{fff}',  2,  '{HH}:{mm}:{ss}\n{DD}.{MM}',  0]
```

If you can confirm that that's the case and tell me what your preferred solution to this is, I'd be happy to open a PR to fix this.

### Workaround
I just always edited the typings file in node_modules and compiled it again. Works perfectly fine :)

**Comment by leeoniya** [comment]
hey @Joelius300 thanks for the spot!

yes, that typing is definitely wrong and should be array of arrays.

> Considering the mode in timeAxisStamps is done with a truthy-check,

i originally wanted to leave room for additional modes, and avoided locking that door early on by using a boolean. using a number is also a bit better for minified bytesize, and the truthy ternary check is used essentially for the same reason.

even though i can't really think of any additional useful modes, i'd probably prefer to just leave is numeric and fix the typings.

overall, this config format turned out to be surprisingly effective and flexible, but it does have the limitation of only supporting 2 levels of context, which in some cases forces labels to be more verbose than they technically need to be. this is most obvious when zoomed in to sub-minute resolutions, where the year/month/date might be repeated when every minute rolls over. it seems somewhat more involved to track multiple levels of context (knowing what has already been rendered in view) to dynamically select the proper formatters. the config for something like that could get very gnarly, but maybe a function which accepts the context and returns the proper formatter per tick would be okay. i dunno. if you have any ideas of how to handle this better, i'd be interested to hear it

**Comment by Joelius300** [comment]
I'm fine with that, thank you for fixing it. As for ideas to allow more fine-grained ticks, I'll make sure to tell you if I have some.

Will you release a patch with this fix or should I continue with the workaround until the next minor release?

**Comment by leeoniya** [comment]
> Will you release a patch with this fix or should I continue with the workaround until the next minor release?

still have some minor tweaks to do before release. will tag next version sometime next week.
