### ISSUE TITLE
Y axe zoom auto ?

### ISSUE THREAD

**Issue by eltomjan** [leeoniya/uPlot#290]
Hello Leon,

amazing exceptional work... I am using 2 small scripts to replace Grafana dashboard (by uPlot).
But had some small issue when there are 4 charts grouped and 4 / 1 values inside, Y axe get lost sometimes somehow during zoom.

After short debugging found strange i0, i1 parameters (1,0) here [@uPlot.js / setScales / getMinMax call](https://github.com/leeoniya/uPlot/blob/e50c20a0966fc27d9dd0a18eec53321991115658/src/uPlot.js#L744) - when I hardcode full data interval, it seems to work properly.

Or maybe problem starts on 734 & 736 - in case i1 = i0 + 1 and both indexes are adjusted then i0 > i1 for Y and minMax loop is skipped.

In case you want to see whole dashboard, content is [here](https://stackoverflow.com/questions/63392291/k6-influxdb-grafana-static-alternatives) in snippet, but zoom does not work when running there.

**Comment by leeoniya** [comment]
hey @eltomjan 

> Y axe get lost sometimes somehow during zoom

this usually happens when there are no datapoints in the zoomed range to auto-range from (or all the datapoints are `null`). it sounds like this is what you're encountering?

> In case you want to see whole dashboard, content is here in snippet, but zoom does not work when running there.

there is a lot going on in your demo, so it would be helpful to create a minimal test case. you can see that in https://leeoniya.github.io/uPlot/demos/area-fill.html the y-axis disappears if you try to zoom to a range in between 2 datapoints.

if you want to specify a custom y range when dataMin and dataMax cannot be determined, take a look at #285.

**Comment by eltomjan** [comment]
Ok, depends on point of view - thought if I can see a line but nothing after zoom it has no sense to zoom to such a place at all ;-) (blocked these 2 ifs for me if distance is less than 1)
Anyway I had to adjust also legend, etc. (time in microseconds, hard to show exact numbers under X, etc.), so I have separate logic for each chart X ticks (time, seconds only) and legend (exact number there - microseconds).

**Comment by leeoniya** [comment]
> it has no sense to zoom to such a place at all ;-)

see #187

**Comment by eltomjan** [comment]
Not exactly - fixed bug in original example.
I have 4 charts in a group, 2 with aggregation and 2 without, you can zoomed data in one, but nothing in aggregated counterpart.

**Comment by eltomjan** [comment]
Not exactly - fixed bug in original SO example.
I have 4 charts in a group, 2 with aggregation and 2 without, you can zoom data in one, but get nothing in aggregated counterpart.
