### ISSUE TITLE
Wrap item list below plot

### ISSUE THREAD

**Issue by jasonatball** [leeoniya/uPlot#295]
When I have a smaller width plot (or even a full screen one) and add enough items it eventually becomes impossible to see them. When I mouseover this becomes worse because the actual values are printed. Is it possible to calculate the chart width and wrap the item list below so they can all be displayed?

Your https://leeoniya.github.io/uPlot/demos/log-scales.html demo is an example of what I'm talking about.

Also I see you have a stacked example but I'm not sure which part of the example actually enables the stacking. This could be an alternative solution even though it takes up more space.

**Comment by leeoniya** [comment]
the legend is just an html `<table>`, by default it is un-styled to make it inline, but you can simply run this which will revert the inline styling:

```js
u.root.querySelector(".u-legend").classList.remove("u-inline");
```

you can see this done in the OHLC demo:

https://github.com/leeoniya/uPlot/blob/5d1f92a511fe88c75947b19feee6328bf6b78e6a/demos/candlestick-ohlc.html#L88-L90

> Also I see you have a stacked example but I'm not sure which part of the example actually enables the stacking. This could be an alternative solution even though it takes up more space.

that stacking is a bit different, because it allows you to return additional arbitrary data for the hover-point, like alternative time along x. it's governed by whether you define `series.values` rather than `series.value`:

https://github.com/leeoniya/uPlot/blob/5d1f92a511fe88c75947b19feee6328bf6b78e6a/demos/time-periods.html#L128-L136

**Comment by leeoniya** [comment]
> Is it possible to calculate the chart width and wrap the item list below so they can all be displayed?

all can be done with just tweaking the css:

```css
.u-legend {
    text-align: left;
}

.u-inline {
    max-width: fit-content;
}
```

**Comment by jasonatball** [comment]
Awesome! Thanks!
