### ISSUE TITLE
cursor hover points are cut off at plot edges

### ISSUE THREAD

**Issue by FrantisekPostl** [leeoniya/uPlot#301]
Hi, I'm using version 1.1.2 of uPlot and Chrome v85.0.4183.102. I have found that some points that are close to axis are not filled when you hover over them.

You can see it in demos too, when you zoom:

![Screenshot from 2020-09-14 10-25-50](https://user-images.githubusercontent.com/45075510/93062105-c7fb5d00-f674-11ea-83c2-d0493a78966c.png)

**Comment by leeoniya** [comment]
yes, this is a known issue.

the hover points are drawn in the DOM for performance reasons, and their `.u-over` container is `overflow: hidden` to allow hiding them and cursor by moving them to a negative position. unfortunately this also cuts them off at the boundaries.

in part, this is a performance optimization so that i don't have to do `if (!visible) {point.classList.add("off")}` on every mousemove.

i'll think a bit more about how to solve this efficiently.

**Comment by leeoniya** [comment]
this is fixed on `master`
