### ISSUE TITLE
Fixed legend labels position

### ISSUE THREAD

**Issue by SkyTien** [leeoniya/uPlot#320]
Is there any way to fixed the legend labels position? 
The space between labels will depends on values length.
When moving the cursor outside of the chart, default values are '--', and labels got closer.

I know there is a cursor.lock setting.
Maybe it will be easier to offer a setting always to keep the cursor position the last value before move out the chart.
And set the cursor position to the middle when the chart first created.

![image](https://user-images.githubusercontent.com/8827278/94659891-88509880-0337-11eb-98a6-f5e01447f66b.png)
![image](https://user-images.githubusercontent.com/8827278/94659966-a3230d00-0337-11eb-9776-8c5404e08938.png)

**Comment by leeoniya** [comment]
> Is there any way to fixed the legend labels position? The space between labels will depends on values length.

the legend is just html with plenty of css classes, so you can just give the `<th>` and `<td>` elements a fixed width.

> Maybe it will be easier to offer a setting always to keep the cursor position the last value before move out the chart.

that doesnt work very well since now it's showing some random at-cursor value but there's no cursor visible. and keeping the cursor visible will always leave it weirdly at the edge where it existed.

> And set the cursor position to the middle when the chart first created.

i used to center the cursor automatically on chart creation but removed it. you can always call `.setCursor()` in if you need this.

**Comment by SkyTien** [comment]
Thanks for your reply.
Do you have any example for giving HTML tag on a legend?

**Comment by leeoniya** [comment]
https://github.com/leeoniya/uPlot/blob/1a468670fca6ee1a10d2af0bae71da705f241092/bench/uPlot.html#L14-L17

**Comment by SkyTien** [comment]
Thanks again.
`.u-value {
   width: 100px
 }` will do.
