### ISSUE TITLE
High frequency dynamic update performance for large dataset

### ISSUE THREAD

**Issue by b4git** [leeoniya/uPlot#322]
Hi,

I would like to get the recommendation for the best possible way to optimize performance for my use case.

Scenario:
1) Simultaneously plot about 4 to 8 dynamic real time timeseries data.
2) New data arrives once every 50 to 200 millisecond. 
3) Need to keep lookback window of about 30 to 50 thousand last data points for analysis (older than 50k data values can be discarded). 

Question:
So, what would be the best approach in terms of system performance and efficiency to update the chart? Should we call the uPlot.setData() and re-scale every-time new data point arrives? Or is there another way to only append the newly arrived data value? In addition, if there is a constant focusing/reviewing/analyzing of different chart sections with zooming/re-scaling would it make any difference? For example: if the user is currently focusing/zooming in on a narrow initial part of the chart, then it is not necessary to immediately update the chart because it can be delayed until user focuses on the latest section of the chart if that would help improve performance.

**Comment by leeoniya** [comment]
> Should we call the uPlot.setData() and re-scale every-time new data point arrives? Or is there another way to only append the newly arrived data value?

yes, you should call `.setData()`. there's not much benefit in something like `.addData()` since most of the cost is in rebuilding the paths, and this has to be done in pretty much all but a few specific scenarios anyways.

> In addition, if there is a constant focusing/reviewing/analyzing of different chart sections with zooming/re-scaling would it make any difference?

uPlot will only re-build paths that are in the "zoomed" range, so it should be pretty cheap to call `.setData()`, but if you really want to optimize it then you can simply skip calling `.setData()` if you see that the user is zoomed. uPlot does not keep any flag for whether it's zoomed or not, so it's up to you to track this and do what you need. e.g. see https://github.com/Cryptkeeper/Minetrack/commit/6aeb8b5045176cb1b2eacaee3801413c002ac82c#r39869985.

if you're feeling adventurous, you can disable y auto-scaling by setting `scale.auto: false` and return a static or conditional `[min, max]` from `scale.range()`, which will prevent re-scanning for min/max values on each `.setData() call`. this will also affect zooming, so you may want to do it conditionally and manually scan your data for min/max values when "zoomed", else return some static range. the perfgain:complexity ratio of doing this might be pretty small though.

generally speaking, human reaction time is about 215ms [1] when they're already primed to react. but in most cases it will be at least 500ms. beyond aesthetics, there's not too much value in updating a live chart more often than 250ms, so i generally throttle `.setData()` calls to that timing - it saves cpu cycles, battery and keeps fan noise down.

[1] https://humanbenchmark.com/tests/reactiontime
