### ISSUE TITLE
Question: show additional axis without series being rendered

### ISSUE THREAD

**Issue by dprokop** [leeoniya/uPlot#334]
@leeoniya couldn't quickly figure this out. Is there a way to show an additional axis that does not have a corresponding data in the data set? I want to render an axis for values which are rendered on top of canvas independently from the series being passed to the uPlot (This component is responsible to render on top of the canvas: https://github.com/grafana/grafana/blob/566cd2c6af8dc95b00b79d30e124b9517739f446/packages/grafana-ui/src/components/uPlot/geometries/EventsCanvas.tsx#L15). 

I see the axis space is occupied in the rendered canvas, yet the axis itself is not shown. I get the axis visible only if I had added the series to the data set.

1. Right axis in this case corresponds to a series being added to the data set and rendered as "invisible":
![image](https://user-images.githubusercontent.com/2376619/96442633-bc6afb00-120b-11eb-83f0-54ed45100026.png)

2. Right axis occupies space but is not shown when there is no series in the data set
![image](https://user-images.githubusercontent.com/2376619/96442756-e9b7a900-120b-11eb-8df3-723cf5e40876.png)

3. Single series, no additional axis. Canvas has correct size
![image](https://user-images.githubusercontent.com/2376619/96442840-0bb12b80-120c-11eb-8b77-6b491d503928.png)

**Comment by leeoniya** [comment]
i think the axis just needs a scale with a defined range function (if there are no series on that scale to auo-range the axis from).

i'll double-check in a few hours that there arent any other bail-outs for no-enabled-series-on-scale.

**Comment by dprokop** [comment]
I have the following config of the scale:
![image](https://user-images.githubusercontent.com/2376619/96443644-394aa480-120d-11eb-820d-b3275718f75d.png)
 And the axis:
![image](https://user-images.githubusercontent.com/2376619/96443709-52ebec00-120d-11eb-9a9c-35d80328c56a.png)

With no series provided, the axis is not visible, yet the space it should take is occupied. I'll dig through the code a bit, maybe I'll find sth out. Thanks for a quick repsonse BTW, highly appreciated!

**Comment by leeoniya** [comment]
my guess is that it's bailing here:

https://github.com/leeoniya/uPlot/blob/master/src/uPlot.js#L1240

should be easy enough to fix.

**Comment by dprokop** [comment]
Looked a bit into the code and tracked down the issue to this line:
https://github.com/leeoniya/uPlot/blob/master/src/uPlot.js#L811

Even if I assign min/max to the scale it seems like when processing the scales min/max if first set to Infinity (https://github.com/leeoniya/uPlot/blob/master/src/uPlot.js#L764) making the independent scales ranging to be dropped.

**Comment by leeoniya** [comment]
ideally, i'd like to

1. have the axis auto-hide when all series on the scale are toggled off. (this happens already)
2. have the plot area resize to take up the extra space. (this does not happen now and looks bad)
3. have a way to override this and have the axis visible even when no series exist on the scale. (what you need).

i'll try to think of some logic which makes sense for this. the simple fix to this specific issue is to simply call scale.range(), but then we cannot auto-hide axes when all series are toggled off.

**Comment by leeoniya** [comment]
i'm still digging into the implications of this but i think there will need to be some behavioral changes with regard to rendering (or initializing empty charts).

there have been requests before to avoid a completely blank canvas when creating a chart with no series or no data. because of this, there are fallback `scale.range` values that will return e.g. `[0,100]` when there is no `dataMin` and no `dataMax`. this allows the axes, grid & ticks to render *something*.

i think the condition to show or not show the axis based on whether the scale has a valid range is correct (maybe it should be `null` rather than `Infinity`, but that's something i'll address later). now, if we simply run `scale.range(self, null, null)` when there are no series (or data) on that scale, then this axis will always be visible with `[0,100]`.

so how can we ever determine if an axis should ever be hidden without adding more complexity?

it seems like the most straightforward way is to abandon scale ranging fallbacks and simply return `[null, null]` or `[inf, -inf]`, which will then disable the axes on that scale. this will mean that any kind of data-less chart rendering will require an explicit scale.range() implementation w/fallback if grid and axes decorations are desired.

**Comment by leeoniya** [comment]
this ended up snowballing somewhat, but i'll have a fix soon.
