### ISSUE TITLE
built-in tooltip and bars

### ISSUE THREAD

**Issue by GitHubLionel** [leeoniya/uPlot#344]
Hi,

Sometime it is better to see series as bar graph. I simply add an option "showAsBar" in the series options.
I add a function : drawBars
See code in zip file (search the words  drawBars and showAsBar).
Note : the code as also the tooltip option in my previous post.

Best regards,
Lionel
[uplot_bar.zip](https://github.com/leeoniya/uPlot/files/5430585/uplot_bar.zip)

**Comment by leeoniya** [comment]
hi Lionel, thanks for the suggestion.

the main problem i have with adding a tooltip and bars to the core is that there are many ways a user may want a tooltip to work:

1. within a container: https://leeoniya.github.io/uPlot/demos/cursor-tooltip.html
2. at the cursor and at the series points: https://leeoniya.github.io/uPlot/demos/tooltips.html
3. cosest with custom content: https://leeoniya.github.io/uPlot/demos/tooltips-closest.html
4. limit how many series are shown to prevent obstruction, or sort series by current value: #99
5. stacked at and following cursor
6. etc.

the number of things people may want as options is very large, and a single style of tooltip will not be useful only in some cases, but be dead code in all other cases, unless 100 more options are added. even if a single type of tooltip was added, the code from the legend should be generalized and reused, but since you copied and modified it, there is now a lot of extra code for this.

the bars series situation is very similar. there are many options people may want for bars:

1. custom settings for dynamic bar width
2. custom settings for bar distribution and plot padding
3. corner radius
4. hover each bar
5. bar groups, with custom spacing & distribution
6. values above or inside each bar (plus minimum bar height)
7. stacked bars
8. etc.

again, only having a single bar implementation will leave many people without the control they want, unless 100 options and more code is added for bar control. it is currently easy to define a custom `series.paths` and draw your own bars with the behavior you need.

the nice thing about lines and a legend is that there are not many ways to draw them, and only require a few options to cover 95% of the required cases.

i think that proper bar and tooltip support will add a lot of code to the core to be useful to everyone, but adding only a single version of each one will increase the library size with features which will not be enough for many users.

- you can create a `seriesAsBarsPlugin` that reads `series.showAsBar` and replaces `series.paths` with bar rendering code
- you can also create a stacked tooltip plugin that copies the legend (instead of replacing it as the OHLC demo does). it will be slightly more code to do this externally, but it will keep the core lightweight and flexible.

**Comment by GitHubLionel** [comment]
Hi Leon,

Thanks to take time for this long explanation.
I understand your arguments and there are applicable for all elements (like the actual legend or path).  I thought that integrate a basic tooltip and bar would be more simple. Personal decorations can be done by css style. 
Plugins are more flexible but also more complicated (you need to understand the internal structure of u-plot)  when you just want basic behavior for bar (like for paths). Code for simple bar is very short.
Maybe a good compromise would be to create a directory that contains all the plugin in JS format that we can include when we need it. Now, plugins in samples is not very practicable.
Note : sorry for my poor English :)
Best regards,
Lionel

**Comment by leeoniya** [comment]
> Maybe a good compromise would be to create a directory that contains all the plugin in JS format that we can include when we need it.

agreed, see #249, #184.
