### ISSUE TITLE
some kind resize(width, height) API

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#36]
Use case: Our sensor dashboards are shared by a team of 7 scientists. Some of them have their screens rotated (portrait). They both want to maximize screen usage without changing the code.

Would it be possible to add a "**stretch to fit**" option?

![image](https://user-images.githubusercontent.com/1218608/67707638-1417b300-f978-11e9-94e6-7769fe9cac8a.png)

![image](https://user-images.githubusercontent.com/1218608/67707805-63f67a00-f978-11e9-966c-350b0dccd06f.png)

**Comment by leeoniya** [comment]
i would recommend that you first measure the size of the container you intend to put the charts into using something like [element.getBoundingClientRect()](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) and use those metrics to create the uPlot instances.

i have no plans to implement auto or fluid sizing in the core, since most of this can be done handled outside the lib. and most of the time is not necessary after initial render anyhow.

if you need to resize the plots after initial render. i can maybe add a `.resize(width, height)` method so you can use that after init.

**Comment by danyalejandro** [comment]
A resize() would work perfectly!

**Comment by leeoniya** [comment]
this is now available as `.setSize({width, height})`

**Comment by mfiot-rm** [comment]
So I have an event listener and at certain break points I run:
```
size = document.getElementById("chart-wrap").getBoundingClientRect()
uplotD.setSize(size.width,size.height)
```
But the plot sorta disappears whenever the size is update.
![image](https://user-images.githubusercontent.com/78705290/132061945-8eba8f08-08a9-4673-a488-f024c9869d06.png)

Am I using the setSize wrong does it need some sort of redraw or update after?

**Comment by leeoniya** [comment]
> Am I using the setSize wrong

yes, it takes a single `{width: ..., height: ...}` object, not two arguments.
