### ISSUE TITLE
How to prevent mouseover resizing the chart

### ISSUE THREAD

**Issue by pedro-w** [leeoniya/uPlot#368]
I've got a 'dashboard' app with several independent charts. When I mouse-over a chart, the legend changes to reflect the current point under the cursor, which resizes the chart and causes an unsightly change in layout. I would like to keep the dynamic legend feature but stop the resizing. It would be a useful feature to be able to pre-determine the maximum length of a legend entry, but I can't see how to do it.
In the example below I am putting the mouse over the middle chart and then off again.
![s_](https://user-images.githubusercontent.com/22172519/99646015-e0f30680-2a47-11eb-8af4-7c7d8d89f706.gif)

**Comment by leeoniya** [comment]
the entire legend is css and html, so there are a bunch of ways to do this, depending kn what you want.

one trick i've used is adding `width: min-content` to the uplot container, which prevents the legend from expanding it and forces it to wrap. this would cause the container expansion to happen downwards instead of to the right.

https://github.com/leeoniya/uPlot/blob/master/demos/tooltips-closest.html#L13

you can also assign fixed width or max-width and min-width to the legend's `td` elements.

**Comment by pedro-w** [comment]
Very helpful, that's solved my problem, thanks.
