### ISSUE TITLE
axis._found is null if plot is initialized with width 0 and height 0 but with existent data, causing an error

### ISSUE THREAD

**Issue by joaopaulobdac** [leeoniya/uPlot#370]
[Codesandbox link with a reproduction of the error](https://codesandbox.io/s/uplot-14-null-is-not-iterable-wrtyp?file=/src/index.js)

The error occurs here
https://github.com/leeoniya/uPlot/blob/0316e6b5755ba1bd5d9607d02923b55a163d96e2/src/uPlot.js#L1428

I was going to make a PR with `let [_incr, _space] = axis._found || [0, 0]` but maybe you should just completely bail the `drawAxesGrid` function if width or height are 0?

**Comment by leeoniya** [comment]
i think i've noticed this before when playing with the resize demo [1] and loading the page with the devtools open to a large height.

yeah, let's bail early. probably wrap the marked section in `if (fullWidCss > 0 && fullHgtCss > 0) {}`.

![image](https://user-images.githubusercontent.com/43234/99762788-e8092b80-2abe-11eb-9676-55c7175480fc.png)


[1] https://leeoniya.github.io/uPlot/demos/resize.html

**Comment by joaopaulobdac** [comment]
Cool! You could use `||` instead of `&&` though

**Comment by joaopaulobdac** [comment]
Cool!

**Comment by Venryx** [comment]
A similar error occurs if the uPlot is just too small to fit the chart+legend contents.

In my case, 300x100 was too small, so I had to increase it to 500x300 for the error on the following line to go away:
```
let [_incr, _space] = axis._found; 
```

The reason it's so small for the given contents, is that 300x100 was just the "start size" for the chart -- I use the `use-resize-observer` hook to detect the true size of the container, and then resize the chart to match it, but I need the start size to be large enough that the error in uPlot doesn't occur.

I think either uPlot should not error for too-small containers, or it should give a clear error message, rather than the iteration error that is confusingly hit on t he line above. (due to `axis._found` being undefined)

I will try to make a repo reproducing the issue someday (too lazy atm); just putting it here for reference.
