### ISSUE TITLE
Cropped bars

### ISSUE THREAD

**Issue by balthazar** [leeoniya/uPlot#397]
Hey, thanks for the awesome lib

I was wondering if you had a suggestion as to how to fix the cropping of bars from [this example](https://leeoniya.github.io/uPlot/demos/line-paths.html), as you probably already know the first and last index are half-cropped on the width. I tried tweaking the paths function and playing with the new padding prop without much success yet

Thanks for the help!

**Comment by leeoniya** [comment]
you have to set the x scale to a wider range. e.g.

https://github.com/leeoniya/uPlot/blob/master/demos/multi-bars.html#L105

**Comment by balthazar** [comment]
Ah perfect thank you, I'm sure the issue might help future users 🙂

**Comment by balthazar** [comment]
Oh and is there a way to still keep the select behavior while providing a custom x scale?

**Comment by leeoniya** [comment]
you'll have to handle any range adjustments in that function, so if you detect that a "full" range is requested, you can add some margins, otherwise you'll have to figure out how to tweak the requested range to "nicely" align or snap it without cut-offs (if you need).

the min/max args is what was "asked" for, and you can return the final decision. e.g.:

https://github.com/leeoniya/uPlot/blob/530a46c53213bb63593451ae48d61e566185cb9e/demos/trendlines.html#L26-L30

**Comment by balthazar** [comment]
Ah yeah cool, missed out the min and max params, thanks!
