### ISSUE TITLE
Make cursor crosshair style configurable

### ISSUE THREAD

**Issue by zefirka** [leeoniya/uPlot#400]
Hi @leeoniya!

What do you think about to make  cursor crosshair style configurable from uPlot options? I now that currently I can configure style of crosshair via CSS overwriting styles, but there are some cases when it's not too friendly. Assume that I writing little wrapper for uPlot which accepts config from backend and I want to stylize crosshair from config. In this case I should inject appropriate CSS every time manually.

If you're okay with this, then we can discuss options structure and then I can take it to myself and send PR. If you think that it should not be a part of uPlot then just close this issue. 

I suggest something like this: 

```ts
interface Cursor {
	x?: CursorLineOptions;
	y?: CursorLineOptions;
}

export interface CursorLineOptions {
	show?: boolean;
        color?: string;
        style?: 'solid' | 'dash' // ... one of border-style options
        width?: number;
}

//or 

export interface CursorLineOptions {
	show?: boolean;
        style?: string; // border style e.g. 'solid 2x rgba(0, 0, 256, 0.9)'
}
```

**Comment by leeoniya** [comment]
i'm pretty wary about exposing static styling options that can be set via css, it can quickly turn into a deep rabbit hole. i would prefer that style injection was done externally instead of adding more config options just to proxy css.

you might consider just using this alternative init style, used to move the legend above the plot: https://github.com/leeoniya/uPlot/issues/398

**Comment by zefirka** [comment]
Ok, thanks for reference.
