### ISSUE TITLE
feature: show better error messages to debug malformed input data

### ISSUE THREAD

**Issue by milahu** [leeoniya/uPlot#419]
can we make uplot less strict to treat NaN's as null values?
or throw a better error message when min or max is NaN?

i have a broken calculation which produces `NaN` values (unintentional)
when i feed these `NaN` values to uPlot, it crashes with the crptic error

```js
function drawAxesGrid() {
// ....
axis._values.forEach(function (val, i)

// TypeError: Cannot read property 'forEach' of null
// axis._values == null
```

backtrace:

```js
function axesCalc(cycleNum) {
// ....
let [_incr, _space] = getIncrSpace(i, min, max, ori == 0 ? plotWidCss : plotHgtCss);
if (_space == 0) return;

// _space == 0
```

```js
function setScales() {
// ....
let minMax = s.min == null ? (wsc.distr == 3 ? getMinMaxLog(data[i], i0, i1) : getMinMax(data[i], i0, i1, s.sorted)) : [s.min, s.max];

// initial min/max
wsc.min = min(wsc.min, s.min = minMax[0]);
wsc.max = max(wsc.max, s.max = minMax[1]);

// min == max == NaN
```

related to #208

**Comment by leeoniya** [comment]
> can we make uplot less strict to treat NaN's as null values?

NaN-handling in data arrays is not going to be happen due to the performance impact.

NaN-handling or coercion everywhere else (like scale min/max) is a slippery slope. while it would be easy to coerce to nulls for scale min/max, this situation can happen literally all over the place, because uPlot allows callbacks for dozens of opts, which rely on the user to do the right thing.

staying fast and micro requires some sacrifices; these sacrifices in uPlot are data parsing, handling malformed input or opts, and providing verbose error messages. generally, these types of errors is what TypeScript is deigned to prevent, so I expect users to rely on uPlot's typescript definitions to reduce the likelihood of this occurring.

i'm open to someone contributing a DEVMODE build, though which would have these checks or error messages. similar to what i do with the `dev` build of domvm: https://github.com/domvm/domvm/tree/master/dist. essentially it's a feature flag that i complied away at build time, like https://github.com/leeoniya/uPlot/blob/master/src/feats.js

**Comment by milahu** [comment]
full ack! here's a start https://github.com/leeoniya/uPlot/compare/master...milahu:add-debug-build

tree-shaking could be more aggressive, even the dist/uPlot.iife.min.js still has all the `if (FEAT_DEBUG)` branches
[@rollup/plugin-strip](https://github.com/rollup/plugins/tree/master/packages/strip) can be used to completely remove debug code

**Comment by milahu** [comment]
problem with my first solution: not working in svelte components
cos i cannot set `window.UPLOT_DEBUG = 1` early enough (before uplot is imported)

alternatives:

1\. enable debug per uplot instance

```js
import uPlot from 'uplot';

const opts = {
  debug: {
    enable: true,
    // maybe add more options in future
  },
};

const u = new uPlot(opts, data);
```

2\. allow to set global default options (more complicated)

```js
import uPlot from 'uplot';

uPlot.setDefaultOpts({
  debug: { enable: true },
});

const u = new uPlot(opts, data);
```

**Comment by leeoniya** [comment]
after giving this more thought, i feel that situations which arise from improper data or improper opts (and are not validated at build time by the TypeScript compiler), can be handled by a runtime DEBUG wrapper around uPlot's API that is able to verify that uPlot is getting what it needs. i would prefer to keep the code clean and leave input validation to external tools. something like https://github.com/fabiandev/ts-runtime looks interesting, but really it's just easier to use TS.
