### ISSUE TITLE
Time zone support

### ISSUE THREAD

**Issue by benmccann** [leeoniya/uPlot#42]
I usually have timestamps (millis since epoch) from the server. But often I want to display in a different time zone. E.g. in Pacific Time or the user's local time for server monitoring. In NYC time zone for finance applications.

Luxon has a really clever way of supporting time zones via the `Intl` api, which is the best I've seen. I have an open PR to add this feature to the date-fns library as well, which the author sounded interested in, but wanted to wait for a future release. Potentially you could use one of these libraries or another option would be to copy some of the code needed for support

**Comment by leeoniya** [comment]
i guess my answer for this is more-or-less the same as #43. but maybe native timezone support is more trivial than i18n, so i'll leave this open for now.

**Comment by benmccann** [comment]
Supporting time zones can be a little more challenging than just formatting because it also changes where the date boundaries are. So if you want to support something like what I was calling "major" ticks or labels then the code that determines whether a date is a new hour, month, year, etc. also needs to take into account what timezone the chart is being displayed in.

**Comment by leeoniya** [comment]
i *think* most of the date snapping is already handled in uPlot and simply providing & passing through a tz offset opt should be sufficient.

do you have any small representative datasets and what you expect to see?

**Comment by leeoniya** [comment]
ok, this was a "fun" challenge.

what i ended up with is a solution based on this neat "hack" [1]. i tested it for a few timezones and it seemed to work well. in essence it allows you to grab the timezone offset for any timestamp in a named timezone.

the compat is pretty good for it [2]: "`toLocaleDateString`: IANA time zone names in `timeZone` option".

the high/low bands demo actually needed this since it showed the gold prices at some mid-day 5pm times (on my machine) when the timestamps were all for 12am UTC. here's what the API is for now:

https://github.com/leeoniya/uPlot/blob/master/demos/high-low-bands.html#L44

let me know if it gives you the expected results.

[1] https://stackoverflow.com/questions/15141762/how-to-initialize-a-javascript-date-to-a-particular-time-zone/53652131#53652131
[2] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Browser_compatibility

**Comment by leeoniya** [comment]
closing this as done, but feel free to discuss further or open new issues for bugs. thabks!

**Comment by benmccann** [comment]
Nice! That's awesome :-) Thanks so much for the fast turnaround!
