### ISSUE TITLE
Bundling step in benchmarks

### ISSUE THREAD

**Issue by benmccann** [leeoniya/uPlot#420]
One thing I've always wondered about with the new version of Chart.js - in most projects users will be including from `npm` and only including the scales and chart controllers they need while the others like bar chart, pie chart, etc. will be tree shaken out. Would you be open to including a `package.json` and `rollup.config.js` in the sample project so that we don't end up weighing the entire library vs just what's needed? The Chart.js tree shaking isn't great, but I imagine it should reduce the library size by 30% and maybe give some motivation to improve it a bit more :smile:

**Comment by leeoniya** [comment]
> in most projects users will be including from npm

i'm not sure this is a statement supported by data. the vast majority of existing and next documentation still point to using a CDN with the full build (see links below). additionally, most examples are wrapped in `<script>` tags. i don't doubt that a large portion of the install base does come from npm due to being in huge projects like Linode, but these likely include all the chart types anyways. once the primary docs dont enourage cdn use of the full build, i would be open to considering just including the portions relevent to timeseries.

> but I imagine it should reduce the library size by 30% and maybe give some motivation to improve it a bit more

this won't have much impact on perf, because apparently i'm not even capturing the parse/JIT time of the bigger libs (see the latest bench issue). you'll save a bit on size, but the benches are ordered by speed, so it's not gonna change anything fundamental. anyways, as stated above, if npm ever becomes the default way to install Chart.js, then i'm certainly open to updates.

https://www.chartjs.org/docs/latest/
https://www.chartjs.org/docs/latest/getting-started/
https://www.chartjs.org/docs/next/

**Comment by leeoniya** [comment]
since i think it will be a good while before any meaningful installation base exists that can leverage v3's tree shaking, (following a v3 stable release), i'm going to close this out so it's not sitting here for 6 months. ping me here when you feel there has been measurable progress on this front.

thanks!

**Comment by benmccann** [comment]
Ah, I actually didn't even realize we talked about installation on the main page of the docs. We have a separate installation page that lists `npm` first that's been kept more up-to-date. We just merged a PR to update the main page to list `npm` first there as well after you pointed that out (https://github.com/chartjs/Chart.js/pull/8245). We do use CDNs in the samples, but that's just out of ease of setting up the samples and not because we're trying to suggest that's the better way to do it - I think we'd say the reverse.

We get about 5m installs a month from `npm` and that's what we list as the first option for users to do, so I definitely consider it a first class citizen. Unfortunately, there's no way to compare usage because npm gets installed once per app but we don't know how many pages were loaded with it whereas with the CDNs we don't know how many apps use it but only how many pages were loaded with that script in it, so it's an apples-to-oranges comparison.

Anyway, like you said, it doesn't have a real impact on the results, so I'm fine saying that it's not worth doing for now. Maybe when we come up with a way to measure the parse/JIT time it would be more worth investing in

**Comment by leeoniya** [comment]
> We get about 5m installs a month from `npm`

these numbers are super super difficult to interpret.

`vue-chartjs` is popular and has chart.js as a devdep. their recommended usage is to include it from a cdn:

https://github.com/apertureless/vue-chartjs#install

uPlot's monthly npm install counts i think come largely from AdminLTE. wanna see how they use it?

https://github.com/ColorlibHQ/AdminLTE/blob/656dbcd25231553ca716722c2c948b03c1af77f5/pages/charts/uplot.html#L925

my hypothesis is that the vast majority of Chart.js installs are using the bundles (either from the packaged dist or from a cdn), based on all docs pointing to CDN use. unfortunately, you'll have a very difficult time convincing me that a typical Chart.js user will benefit from tree-shaking in the future unless the use of a CDN or bundle is actively discouraged in tutorials and install guides for v3 to promote tree shaking...and that will take a very long permeate through the whole ecosystem.

it's similar to code splitting. it's great in theory, but if you look at actual apps in the wild of any real complexity, it rarely lives up to its promises, either due to improper packaging setup, lack of developer discipline, apathy, the gospel of pre-mature optimization, etc.
