### ISSUE TITLE
replace buble with babel to produce ES5 code for IE11

### ISSUE THREAD

**Issue by milahu** [leeoniya/uPlot#423]
* buble is out of date
   * no support for optional chaining `obj.prop1?.prop2`
* ES5 code can be produced with [babel](https://stackoverflow.com/questions/34747693/how-do-i-get-babel-6-to-compile-to-es5-javascript)
   * [has support](https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining) for optional chaining
* ~~babel can be used to [optimize functional loops](https://github.com/vihanb/babel-plugin-loop-optimizer)~~

**Comment by leeoniya** [comment]
can you compare the generated code for both?

in my experience, Buble produces much cleaner and tighter code vs Babel in both ES2015 and ES2015-loose mode.

try pasting Buble's example:

https://buble.surge.sh/

 into Babel's REPL:

https://babeljs.io/repl

**Comment by milahu** [comment]
actuall the result is smaller : )

```
$ du -b dist/*.iife.min.js
35497	dist/uPlot.babel-preset-env.iife.min.js
35497	dist/uPlot.babel-preset-es2015.iife.min.js
35497	dist/uPlot.babel-preset-es2015-loose.iife.min.js
36578	dist/uPlot.iife.min.js
```

es2015 is deprecated for env

<details>

```
npm i -D @babel/core @rollup/plugin-babel babel-preset-env babel-preset-es2015-loose babel-preset-es2015

// rollup.config.js
const { babel } = require('@rollup/plugin-babel');

	{
		input: 'uPlot',
		output: {
			name: 'uPlot',
			file: './dist/uPlot.babel-preset-es2015-loose.iife.min.js',
			format: 'iife',
			esModule: false,
			banner: "/*! " + urlVer + " */",
		},
		plugins: [
			bannerlessESM(),
			babel({
				babelHelpers: 'bundled',
				presets: ['babel-preset-es2015-loose'],
			}),
			terser(terserOpts),
		]
	},
	{
		input: 'uPlot',
		output: {
			name: 'uPlot',
			file: './dist/uPlot.babel-preset-es2015.iife.min.js',
			format: 'iife',
			esModule: false,
			banner: "/*! " + urlVer + " */",
		},
		plugins: [
			bannerlessESM(),
			babel({
				babelHelpers: 'bundled',
				presets: ['babel-preset-es2015'],
			}),
			terser(terserOpts),
		]
	},
	{
		input: 'uPlot',
		output: {
			name: 'uPlot',
			file: './dist/uPlot.babel-preset-env.iife.min.js',
			format: 'iife',
			esModule: false,
			banner: "/*! " + urlVer + " */",
		},
		plugins: [
			bannerlessESM(),
			babel({
				babelHelpers: 'bundled',
				presets: ['babel-preset-env'],
			}),
			terser(terserOpts),
		]
	},
```

</details>

**Comment by leeoniya** [comment]
it's smaller because it's not doing the same transforms, most of the extra size comes from converting arrow functions. if you switch to `buble({transforms: { forOf: false, arrow: false }}),`, you'll get smaller sizes with buble (probably because by default it converts const -> var). https://buble.surge.sh/guide/#using-the-javascript-api#list-of-transforms

the size difference doesn't seem as bad as it used to be, so i'll look into this a bit more. i want to diff the non-minified bundles between the two versions to see how they differ. until then, i'm going to set `arrow: false`.

ideally, we can omit both babel and buble, but for some reason a bundle without them has worse startup performance. if we can figure out why (maybe lack of hoisting and TDZ stuff) and simply adjust the source, then we can drop both. i'm not concerned about supporting legacy browsers at this point.

**Comment by leeoniya** [comment]
i'm gonna punt on this. `node_modules` goes from 760 files / 5.6MB -> 4,900 files / 11.3MB

that ROI is not great, especially since the current codebase does not use optional chaining and would not benefit much from it.
