### ISSUE TITLE
Idempotent way to set Series

### ISSUE THREAD

**Issue by KyleAMathews** [leeoniya/uPlot#425]
Something like `setData`.

Perhaps I'm missing something but in my project the series are changing frequently (as driven by backend code) so I want to be able to just call `setData`, and `setSeries` after each backend push. This doesn't seem possible with the current APIs? My workaround is to manually reconcile the current series with the new ones.

**Comment by leeoniya** [comment]
how would this differ from a delete loop followed by a re-add loop?

https://leeoniya.github.io/uPlot/demos/add-del-series.html

**Comment by KyleAMathews** [comment]
I assumed `delSeries` would immediately cause a render which would be glitchy.

**Comment by leeoniya** [comment]
`delSeries` doesnt have any immediate effect besides dom removal and `addSeries` does series series re-init plus dom insertion, but also no redraw. in both cases, this is obviously not ideal to do before every setData call.

unfortunately, it's hard to give more specific advice if anything can mutate at any time. uplot does not have vdom-like diffing functionality and much of its performance comes from creating many invariants at init time.

**Comment by leeoniya** [comment]
gonna close this for now.

there are quite a few options that can be directly mutated and followed up with a redraw call instead of removing and re-adding series, but i can't provide any optimization advice without more specific knowledge on what you're expecting to change and what your data looks like.

feel free to provide more info or ask additional questions here.
