### ISSUE TITLE
Progressive Rendering

### ISSUE THREAD

**Issue by cssberries** [leeoniya/uPlot#432]
Is there a way to render charts incrementally, at an arbitrary rate?
Here is an example that illustrates the Progressive Rendering in action: [http://bl.ocks.org/syntagmatic/2420080](http://bl.ocks.org/syntagmatic/2420080).

**Comment by leeoniya** [comment]
nothing out of the box.

you might be able to do it externally via requestAnimationFrame() + addSeries().

what's the purpose?

**Comment by cssberries** [comment]
The purpose is to be able to render large/arbitrary amounts of data.

Currently, the amount of data you can render is limited by hardware. In theory, you _can_ render a lot of data but your application will be unusable(at best) till the end of the rendering. Progressive rendering enables you to be limited by time. So, if you need to render a lot of data you'll still be waiting, probably even longer, but the application will be fully usable, as if no rendering happens in the background. Imagine 10,000 lines with 500 points each _immediately_ start to appear.

Anyway, requestAnimationFrame() + addSeries() will probably work. I'll try it.

Thanks!

**Comment by leeoniya** [comment]
> Imagine 10,000 lines with 500 points each immediately start to appear.

i honestly don't understand how people can grok 10k series in a single chart. for me, once it goes over ~16, it's already an inscrutable mess with the only discernible things being outliers and maybe general medians in the case of a multi-modal spread is. shoveling that much raw data into a plot without any kind of bucketing or aggregation is an odd practice. the d3 example you linked looks very pretty but i struggle to extract any useful insight from it.

would be interested to hear an alternative viewpoint!

**Comment by cssberries** [comment]
Yeah, I don't think anybody is able to really comprehend more than even 7 series. There is a case though where you are not trying to grasp all the details but, as you mentioned - to look for outliers or any other patterns in general. Interesting stuff might emerge when you look at the whole picture. At once.
I'll give you an example.
Below are two charts showing transactions response time (TRT) of an application under test (AUT). In the first chart all transactions are aggregated/grouped by name. It's 5 series and it's readable. The problem is that there might be some information that you don't even know it's there. 
In the second chart there is no aggregation  - the chart shows all appearances of the transactions. It's 375 series and its a real mess. I don't even bother to colorize each line. But it's not a complete mess. You _can_ see there two interesting insights that you can't see in the aggregated chart. The first insight is the much more pronounced spikes at the beginning of the test. The second insight (between ~3:15 and ~3:25 PM) is more interesting because it shows that in this period of time some transactions don't have any data points! 
   
![image](https://user-images.githubusercontent.com/2432131/104412014-2fb6ab80-5574-11eb-9edf-744cd2ee44fc.png)

**Comment by leeoniya** [comment]
> You can see there two interesting insights that you can't see in the aggregated chart. The first insight is the much more pronounced spikes at the beginning of the test.

yes, but this is easily detectable by even trivial outlier-detection algorithms, after which you can render a "typical" aggregated trend and then additionally plot the few outliers series. these outliers are already obvious even in the top chart, though they're not quite as extreme there.

> The second insight (between ~3:15 and ~3:25 PM) is more interesting because it shows that in this period of time some transactions don't have any data points!

i don't see this at all. what i see is a drop in the *values*, not the *absence* of datapoints. i don't see anything in the bottom chart that adds insight to what's already obvious in the top one for this time period.

what you're showing is actually the exact cases where it's easy to detect from the data. more subtle and gradual patterns are ones that would be more difficult to detect automatically. but i think even in this case, the line quantity would make this mostly impossible. the d3 demo you showed is somewhat more interesting because at least it vertically separates the pathways, thus offering *some* level of grouping / dimensional aggregation, while a raw line chart doesn't do this. i have a demo that shows the same line-trend data in a shifted manner, the insight difference is quite remarkable: https://leeoniya.github.io/uPlot/demos/y-shifted-series.html

**Comment by cssberries** [comment]
We use an anomaly detection algorithm in our product and unfortunately its accuracy is far from 100%. In the example I gave you, none of the spikes happening at the beginning of the test were detected. I guess our algorithm is struggling to define what is "normal" when there is not enough data to analyze - the beginning of the test.  I'm not a specialist in this field so I'd appreciate if you could give some examples of high accuracy contextual anomaly detection algorithms.

Regarding the second insight. There are some straight lines lasting for ~10 minutes. It means that there was no data there. In this case it was due to incorrect test configurations.

**Comment by leeoniya** [comment]
i'm no anomaly detection expert either, but it looks like there is plenty of data across all series by that point to establish a reasonable cross-series rolling median, and detect spikes that large in any one rogue series.

also, since this doesnt look like a real-time application, you can maybe detect them by running the algorithm in reverse :)

for the gaps, yeah i see now. but gaps in data that large should be trivial to detect, and you might not see smaller gaps either (i'm sure they exist in the above dataset also!)

anyways, thanks for the discussion. for such heavy applications i would recommend using webgl instead of trying to do progressive loading into 2d canvas. check out the couple small webgl libs i have listed at the top of the readme.
