### ISSUE TITLE
Dyanmic shifted y-axis with dynamic data

### ISSUE THREAD

**Issue by GoodMorgon** [leeoniya/uPlot#435]
Hello,

This post is related to https://github.com/leeoniya/uPlot/issues/428.

I haven't been able to fully replicate (understand) the example in the linked question to my use-case. How do I scale the plot if the data is not perfectly aligned to the interval of 10 as in the https://leeoniya.github.io/uPlot/demos/y-shifted-series.html example?

Please see the following JS Fiddle: https://jsfiddle.net/kjqoashx/19/

I've tried different changes to the code but without luck. Any help would be much appreciated.

**Comment by leeoniya** [comment]
@GoodMorgon i'm not going to dig through your Vue code and try to re-assemble your copy-pasted code from this issue.

please create a jsfiddle that only uses uPlot, and i will help you make it work.

here is an example: https://jsfiddle.net/xk0y31gq/

**Comment by GoodMorgon** [comment]
@leeoniya I have now updated the original post with a JS Fiddle :)

**Comment by leeoniya** [comment]
thank you.

what are aux1 and aux2? are they simply level indicators or actual data? is you want to just draw lines to indicate levels, you should do it without using a series. example: https://leeoniya.github.io/uPlot/demos/trendlines.html

does the chart look like you want before the shift?

i'm not quite understanding what you want it to look like after the shift.

can you approximately draw pictures of both versions for me?

**Comment by GoodMorgon** [comment]
I have updated the original post with a new JS Fiddle where the purpose of the chart is more intuitive. 

The aux1 and aux2 series are extra data that can be present (but must not). Before the shift the chart looks as it should.

When the data does not match very well on the y-scale (as it does now in the new JS Fiddle) the user should have the possibility to split up the chart into its components, in this case 4 separate small charts.

Each series should then have 1/4 of the y-axis, and be plotted separately (no series overlapping another), just as in the https://leeoniya.github.io/uPlot/demos/y-shifted-series.html example.

**Comment by leeoniya** [comment]
there are quite a few differences here which make this not straightforward to understand without an image of what you want to achieve.

the original y-shifted demo has predictable and the matching y ranges for all series, each can only be 0-10. in the example you have, it's not clear to me what those ranges are for each series, and they're certainly not the same for each. this is what determines the "shift amount", which in my demo is static, but in your case may need to be dynamic (which is possible but more involved, and much easier to just do this in several dedicated charts).

also, i would recommend that your forecast is part of the same series as your historical data. it's possible to mark the "future" period using an hz stroke gradient (https://github.com/leeoniya/uPlot/issues/416) or a canvas shading annotation (https://github.com/leeoniya/uPlot/issues/433#issuecomment-761996274).

**Comment by GoodMorgon** [comment]
@leeoniya Thank you for your answer.

> the original y-shifted demo has predictable and the matching y ranges for all series, each can only be 0-10. in the example you have, it's not clear to me what those ranges are for each series, and they're certainly not the same for each. this is what determines the "shift amount", which in my demo is static, but in your case may need to be dynamic (which is possible but more involved, and much easier to just do this in several dedicated charts).

Yes, this is the issue. In the demo the shift amounts are static, but that's seldom the case with real-world data. If a dynamic computation for the y-axis could be made, that would be awsome (I'm appreciative of the fact that you do this open source, but this feature would be so so awsome). The problem with several dedicated charts is that they will introduce their own problems (such as with referencing etc.). What one wants is to be able to switch between two modes of viewing the data, one where everything is together in a single chart, and another mode where each series is plotted as it's own subchart. 

> also, i would recommend that your forecast is part of the same series as your historical data. it's possible to mark the "future" period using an hz stroke gradient (#416) or a canvas shading annotation ([#433 (comment)](https://github.com/leeoniya/uPlot/issues/433#issuecomment-761996274)).

Thanks!

**Comment by leeoniya** [comment]
i don't want to get too deep into the sub-charts business, as this will quickly lead to shifted x, multiple cursors, etc.

the problem with dynamic shifts is not a technical one -- you just have to do the work to re-compute the baselines and ranges for each series and do the necessary adjustments prior to redraw. there are also many decisions for how much each shifted chart needs to occupy, etc. all of these considerations will be different for each use case and you'll likely realize that not only is it tricky to manage, but also the final experience will be poor, because the baselines of each series will shift suddenly if there are spikes in 1 series -- a problem not unlike the stacking experience: https://leeoniya.github.io/uPlot/demos/stacked-series.html. if you want the baselines to remain stable, then you have to have pre-determined, fixed y ranges (they can be different, but not dynamic based on current data).

thanks for the discussion, but i don't think that dynamic shifts are a good idea. different but static y shifts might be more reasonable and also easy to code. however, i don't have much time currently to do work on this. you can try asking on stackoverflow, but there's nothing uPlot specific that needs to be done here that's not already done in the y-shifted demo -- just some changes to the math.
