### ISSUE TITLE
Recommended approach to enable dark and light theme.

### ISSUE THREAD

**Issue by b4git** [leeoniya/uPlot#436]
Hi,
Is there a concept of theme (such as day vs night mode or dark vs light colors) for the uPlot charts? If not would you please provide a general recommendation on how to add the ability to toggle between the two color themes in an efficient and consistent manner for the uPlot charts? 
A simple demo would be great, if it is something that can be coded quickly, otherwise, general pointers would be helpful. 
Thank you.

**Comment by leeoniya** [comment]
you can see i shamelessly pillaged my employer's dark chart styles here :D

https://leeoniya.github.io/uPlot/demos/line-paths.html

if you want to switch them dynamically, all of the color-related options like `stroke` & `fill` support callback signatures, so this should be pretty easy to do. then just call `u.redraw(false)`. `false` prevents the paths from being rebuilt, so is very fast.

so, here is the theory: https://jsfiddle.net/2d6awt9c/

though in practice it seems like i overlooked a few places to make sure that those callbacks are invoked on every redraw. that will be fixed shortly...

**Comment by leeoniya** [comment]
alright, fixed: https://jsfiddle.net/bfg745km/

one thing that's not so great is the cursor hover points as well as the legend. the things in the DOM will not get dynamically updated, so you'll have to use vanilla js to reach into the dom or use CSS to adjust their styling. otherwise you can always just re-create the chart from scratch with your "dark" theme.

**Comment by b4git** [comment]
Thank you. It helped!
