### ISSUE TITLE
Sparkline not being fully filled.

### ISSUE THREAD

**Issue by shengyan** [leeoniya/uPlot#442]
Hi, @leeoniya.

This [JS Fiddle](https://jsfiddle.net/a5z4r0cm/) shows a single pixel width gap on the left of the Sparkline filling, The code is based on the [Sparklines demo](https://leeoniya.github.io/uPlot/demos/sparklines.html).
You can also reproduce this by adding `td {
  background-color: orangered;
  padding: 0px;
}` to the Sparkline demo.

What could be the problem?

**Comment by leeoniya** [comment]
this is a bit of a tricky situation. uPlot prefers to draw crisp lines, which both help visual quality and speed when lines are vertical (high density data) or horizontal (flat data). to accomplish this, it offsets the canvas by half the stroke width, more info here: https://mobtowers.wordpress.com/2013/04/15/html5-canvas-crisp-lines-every-time/

for cases when there are no vertical or horizontal lines, this is not necessary, and we can simply skip it. in the vertical case, it's pretty easy to know cause we can do a cheap test for data density without looking at the actual data arrays. for horizontal lines it's expensive, since it cannot be done without scanning the arrays. so a solution that handles the the vt case is in this branch: https://github.com/leeoniya/uPlot/tree/skip-stroke-align, and it works for both sparkline cases, since none of them have flat or dense data, or maybe you dont care about the line width increasing and crispness going away.

it feels like an option that should be exposed so the user can decide, since there's no solution that will work for everyone.

![Peek 2021-01-31 13-59](https://user-images.githubusercontent.com/43234/106396548-35165180-63ce-11eb-8cc5-c2630ce852c3.gif)
![Peek 2021-01-31 13-56](https://user-images.githubusercontent.com/43234/106396549-35165180-63ce-11eb-97c1-742bbf69ae51.gif)

**Comment by leeoniya** [comment]
your fiddle now works as expected on `master` with `opts.pxAlign: false`: https://jsfiddle.net/hxbj24ou/
