### ISSUE TITLE
Have both a toolbar AND a legend

### ISSUE THREAD

**Issue by hugovoerman** [leeoniya/uPlot#446]
Hi,

As mentioned in #335 the idea of having a tooltip AND a legend would be very nice.
The tooltip to have the values close to the cursor, the legend to be able to switch series on/off.

I can't see if or how issue #335 made it into uPlot.

So I make this into a question: how can I have both a tooltip (values near cursor) AND a legend (turn on/off series of data).

Right now I use the tooltip plugin, but as mentions in #335, that modifies the legend.

Thanks in advance for the response.

**Comment by leeoniya** [comment]
my viewpoint has not changed since https://github.com/leeoniya/uPlot/issues/344#issuecomment-718104304.

a tooltip and live legend are redundant; it would be like making two legends in the core, with the only difference that one follows the cursor. if you would like to have both simultaneously, it is easy implement a tooltip as you need using the `setCursor` hook. there are several demos that show how to do this.
