### ISSUE TITLE
Synchronizing cursor position but not scaling operations

### ISSUE THREAD

**Issue by fifafu** [leeoniya/uPlot#459]
Thank you for this amazing library, it has pretty much saved one of my projects :-)

I have a question: Is there any way that would allow me to synchronize the cursor position between all charts but keep the "drag to scale" independent in every chart (but still enabled)?

If this is not the right place to ask, feel free to delete this post.

**Comment by Jay27D** [comment]
I'm not sure about the drag to scale part. But if you add the scroll wheel zoom plugin, it definitely works independently.

**Comment by fifafu** [comment]
@Jay27D that's true because when using that the scaling is done "manually". However I really like the drag zoom with the visual range selection :-)

**Comment by leeoniya** [comment]
this should be easy to add, but we need to figure out a logical API for it.

the internal pub/sub works on a more granular level - it doesn't know about selection or scaling, but simply re-emits mousedown, mousemove & mouseup events to all subscribers. so to handle this we need to either:

1. not re-emit mousedown/mouseup/dblclick events at the source (during publish)
2. or ignore mousedown/mouseup/dblclick events at the destination (in the subscribers)

currently, `opts.cursor.sync` looks like this:

https://github.com/leeoniya/uPlot/blob/e45b34f2f7f0d44bd7fb8d9f818136ac15769ef8/dist/uPlot.d.ts#L420-L427

my thought is to add `filterPub(type, client, ...args)` and `filterSub(type, client, ...args)` so you can return `false` to prevent those events from being published or acted upon.

filtering at the subscribers will be more expensive, since this would happen later in the lifecycle. i'm also not sure how useful it is to selectively ignore some events in some bit not all charts in the same sync group. perhaps just a publish-level `filter(type, client, ...args)` would be enough and less confusing than having two.

> Thank you for this amazing library, it has pretty much saved one of my projects :-)

:+1:

**Comment by fifafu** [comment]
for my use-case a publish level filter would definitely be sufficient. However I can think of cases where a subscribe level filter would be helpful. The check whether a filterSub is defined should not have a measurable impact, correct? So it would only be expensive if used (and then the user probably has a good reason to).
