### ISSUE TITLE
mouse cursor lagging on top of real time chart

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [leeoniya/uPlot#466]
I went trough so many charting libraries, they all have some missing feature have horrible design and ux or bugs. 
This one seems really ok except for the crosshair lagging on real time charts.  They seem to lag when adding more graphs on top.

**Comment by leeoniya** [comment]
what is "real time"? 5Hz? 20Hz? 60Hz? 1GHz?

how many charts do you have? how many series per chart? how much per-series data is in view during each setData()? on what hardware? in what OS?

this is a useless complaint with 0 detail. yes, at some point you'll run into limits.

**Comment by hp8wvvvgnj6asjm7** [comment]
sorry, 
I just opened the sine wave example.
maybe its my machine.

**Comment by leeoniya** [comment]
yes, the sine stream demo has some cursor lag. effectively it's fully rebuilding 6 paths of 600pts (3600 lineTo() calls) x 60Hz.

there is a plan to create an addData() api that only  draws the new data and shifts the rest which would improve perf significantly for high freq streaming, but that's still a few months away: https://github.com/leeoniya/uPlot/issues/62

**Comment by hp8wvvvgnj6asjm7** [comment]
Yes it would be way more efficient not having to repaint the entire series.

I don't know if this is helpful, but this thing seems to perform really well:
https://d3fc.io/examples/webgl-with-svg-overlay

If you could get something like this with animation, it would blow the competition away =)

**Comment by leeoniya** [comment]
> I don't know if this is helpful, but this thing seems to perform really well:

you've linked to an example that

1. loads 936KB of js (27x larger than uPlot)
2. is not streaming data
3. has no crosshair cursor to demonstrate how the lag issue is solved

![image](https://user-images.githubusercontent.com/43234/110219121-fa974d00-7e82-11eb-88eb-4eb37af58b36.png)

> If you could get something like this with animation, it would blow the competition away =)

animation is specifically mentioned as being out of scope for this project: https://github.com/leeoniya/uPlot#non-features

please do some basic research, reading and investigation before providing any additional "advice". if d3fc works for you, then definitely use it instead of uPlot.

**Comment by andyb1979** [comment]
Lol @leeoniya had this guy @hp8wvvvgnj6asjm7 troll me as well and be generally unhelpful. I blocked him from our repo, suggest you do the same.

**Comment by leeoniya** [comment]
this is _mild_. i didn't even ban this guy, just locked the convo: https://github.com/leeoniya/uPlot/issues/233
