### ISSUE TITLE
[Ask] Is there a way to update chart's options.bands?

### ISSUE THREAD

**Issue by aim-leo** [leeoniya/uPlot#516]
Hello, I'm looking for a better way to update my chart, some times i have to update the series, and the bands should update too.
But I can't find a method to update this property, is there a way to update chart's options.bands?

If I destory the chart, and reInit it, it will works. but, is there a better way to do it? any response will be grateful!

**Comment by leeoniya** [comment]
i currently mutate them:

https://github.com/leeoniya/uPlot/blob/69fb492b7f0069c5ef910f0cec5091964f2ccd78/demos/stacked-series.html#L79-L86

it's not the most elegant API, and i've considered adding `setBands()` that literally just does the above. but doing it automatically is probably too tricky since bands can be used for a lot of purposes, like stacking, etc.

**Comment by leeoniya** [comment]
i'm going to add something like `.setBands()` so people don't get the impression that it's okay to do this with other structures that are similarly exposed, such as `u.series`, `u.scales`, etc.
