### ISSUE TITLE
implement month incrs

### ISSUE THREAD

**Issue by leeoniya** [leeoniya/uPlot#52]
https://github.com/leeoniya/uPlot/commit/db2b05bc9a1e9cc82146d86200d87286e9bdb795#r35853039

**Comment by benmccann** [comment]
month is by far the trickiest since each month has a different number of days. I ended up making the logic a bit more complicated in chart.js to account for this. I first plotted the first day of each month and then placed the days in between based on the total number of labels that I wanted to display (the code is slightly messy to maintain backwards compatibility with old versions of chart.js, but hopefully should be pretty understandable)

https://github.com/chartjs/Chart.js/blob/94afa634507036d8cd6b34d2c96eb225177b197e/src/core/core.scale.js#L886

**Comment by leeoniya** [comment]
b27a9934a88fd625952f5a455492760b187b8ca0 puts most of the machinery in place.

the strategy it uses is mostly the same as what the 12am snapping code did/does, plus a bit more. the `axis.range()` api had to change from only snapping the min to actually returning all the ticks, since they are no longer always evenly spaced from the `min` + a fixed `incr` multiple; now it's `axis.ticks()`. it's hard to tell from the demo [1], but the grid & axis labels are no longer evenly spaced. (Feb is narrower than March).

something unfortunate that emerged out of writing the demo is #53, since i was trying to verify that the tz offsets were working properly and wanted to zoom in more than what is currently attainable.

i think this is enough to close the issue?

[1] https://leeoniya.github.io/uPlot/demos/months.html

**Comment by leeoniya** [comment]
i'm calling this one done. please open new issues if you spot any bugs.
