### ISSUE TITLE
Cursor syncing between charts where each time series has custom resampling precision

### ISSUE THREAD

**Issue by b4git** [leeoniya/uPlot#520]
Hi,
I am trying to synchronize the cursors between multiple charts where each chart has a custom logic to capture data at its own specified time interval or resampling logic and precision. So, the time axes will be different for each chart.

I have created a sample jsfiddle chart here:[https://jsfiddle.net/d5x60ocn/6/]( https://jsfiddle.net/d5x60ocn/6/)

However, the cursors are not properly synchronizing.

**Comment by leeoniya** [comment]
yeah, i would not expect it to work with `distr: 2` scales, which do everything by data index position. cursor syncing happens by doing math along a continuous, predictable scale (not by scanning data). `distr: 2` is only continuous by ordinal index position, but is discontinuous by the x value, which is how it is able to "skip" periods in time with no data.

you can try to implement sync externally that does data scanning and tries to put the cursor by interpolating positions between neighboring datapoints, or something.

**Comment by b4git** [comment]
> yeah, i would not expect it to work with `distr: 2` scales, which do everything by data index position. cursor syncing happens by doing math along a continuous, predictable scale (not by scanning data). `distr: 2` is only continuous by ordinal index position, but is discontinuous by the x value, which is how it is able to "skip" periods in time with no data.
> 
> you can try to implement sync externally that does data scanning and tries to put the cursor by interpolating positions between neighboring datapoints, or something.

Sure, is there an exposed interface API for that?

**Comment by leeoniya** [comment]
> Sure, is there an exposed interface API for that?

you'll have to write code. the APIs for doing this are there. you'll want, on the source side you'll want to use the `setCursor` hook. on the target side you'll want the `.setCursor()` method. between those two you'll want to look at `u.data` and use `.valToPos()` and `.posToVal()` methods plus whatever logic you want to figure out where you want to position the cursor.

the cursor and zoom demos have a lot of examples of using these APIs.

> Is it possible to merge/collapse those gaps on the chart while using distr:1?

no, this is not possible, because there is no mathematical relationship between pixel position and position along the scale when that scale may discontinuous (expanded or compressed) based on the data.
