### ISSUE TITLE
uPlot and Tailwind CSS (css classes) for height and width of chart

### ISSUE THREAD

**Issue by MartijnHarmenzon** [leeoniya/uPlot#536]
I would like to use uPlot within a website that uses Tailwind CSS.
Normally I would do something like:

```
<div class="flex h-screen w-screen">
  <div class="h-1/2 w-1/2" id="chart01"></div>
</div>

const chart01 = document.getElementById("chart01");

const uplot = new uPlot(opts, intensity, chart01);
```

Can and how would I make something like this work?

Attached a CodePen with some work in progress.

https://codepen.io/martijnharmenzon-the-looper/pen/zYZQMzp

**Comment by Martichou** [comment]
I think you can always wrap the `chart01` inside another div which set the `width` and `height`.

**Comment by leeoniya** [comment]
probably the best and most efficient route to take here is https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver

**Comment by MartijnHarmenzon** [comment]
Thanks @Martichou @leeoniya . We are using setSize(). But how to deal with the legend below the x-axis? At the moment, the legend is pushed outside of the div. How to prevent this.

I created a CodePen to ilustrate. I would like the legend to stay within the white area. 

https://codepen.io/martijnharmenzon-the-looper/pen/zYZQMzp

**Comment by leeoniya** [comment]
> At the moment, the legend is pushed outside of the div. How can we prevent this?

first, you may want to render the chart title outside of uPlot so that you only have to deal with legend sizing.

since the legend size depends on the rendered contents, and that does not happen prior to chart rendering, there are only two ways to getting this working:

1. render once, then shrink the size via setSize() after measuring the legend height and subtracting it from the container height.
2. set a static legend height using css and pre-subtract it from the initial chart width/height.

**Comment by MartijnHarmenzon** [comment]
Thanks @leeoniya! Much appreciated. Will look into your suggestions.
Does uplot have an option to set the legend height?

**Comment by leeoniya** [comment]
> Does uplot have an option to set the legend height?

no, the whole legend is created in the DOM with a lot of classes you can target with css or querySelector
