### ISSUE TITLE
Why there is a line in this chart? (bad title, but look at the picture)

### ISSUE THREAD

**Issue by m-ahmadi** [leeoniya/uPlot#539]
Why is [this ](https://jsfiddle.net/m_ahmadi/6e1vqymt/8/) happening?
![Untitled](https://user-images.githubusercontent.com/16363767/123170714-15bcb580-d490-11eb-8dea-80860ccf6140.png)

My best guess is, it's got something to do with the `timestamp` or the `serie` data in above example,
because [here](https://jsfiddle.net/m_ahmadi/tma9x0n4/19/) I tried to reproduce the problem but I failed.

**Comment by leeoniya** [comment]
your dates are not in ascending order. if you sort them it works:

```js
dates.sort((a, b) => a - b);
```

you also have many duplicate dates in your dataset, which will render okay, but will cause cursor hover issues.

finally, i recommend using unix timestamps in the original dataset instead of converting the custom format from a number to a string and then parsing it. to create a bunch of date objects that then give you timestamps.
