### ISSUE TITLE
Bar chart with multiple (2) data series

### ISSUE THREAD

**Issue by MartijnHarmenzon** [leeoniya/uPlot#546]
What is the easiest way to create a bar chart with multiple (2) data series? See image below as an example. Where series 1 would be the dark bars and series 2 would be the lighter bars.
We have achieved to create a bar chart with a single data series, but multiple...

![Screenshot_20210708-211422](https://user-images.githubusercontent.com/23123158/124978206-c51d8e80-e031-11eb-9eef-b80c88798871.png)

**Comment by leeoniya** [comment]
you'll probably want to use https://leeoniya.github.io/uPlot/demos/multi-bars.html, where the x axis is labels and supports an unlimited number of bars. there is no support for grouped bars along a `time: true` scale/axis.

**Comment by MartijnHarmenzon** [comment]
@leeoniya thanks for your response. I have seen this example. Sorry to say, but I find this example difficult to understand. I really like the library for the small footprint and speed. And I appreciate all the hours that go into it and the fast support. It's the reason we choose this library. But the steps to create a simple looking bar chart is complex. I have read comments that making bar charts more easy is not that simple. You loose flexibility that other users might want. But I also think many users don't want to dive this deep into the code, while still wanting to use uPlot. Just sharing my thoughts...

**Comment by leeoniya** [comment]
i think it's important to view the library through the lens of its original purpose: to plot huge x-aligned datasets as lines that have time for x and numbers for y.

its core design is partly what prevents it from being used easily for scatter and bubble charts (that don't have a shared x and need per-datapoint mouse interaction and styling. stacking has always been an afterthought because in my opinion it's a shitty way to interpret trends, even though people _love_ stacked charts visually. smooth lines are usually also shitty, but i managed to find an interpolation method that isn't complete crap, so now they're in the core.

the further a specific chart type is from the original design, the more effort it takes to get it working. the fact that it is possible at all to do additional charts now without any drop in performance for multi-million point line charts has been both very surprising, and a lot of work. i never intended for uPlot to replace all types of charts (though i hope to make Scatter, Bubble, X/Y first class citizens in a 2.0 API update). uPlot is unlikely to do radial/polar charts like pie, radar, gauge.

part of the reason there is no easy-to-get-started docs is because users are expected to read and write code for their specific needs; many options are implemented as callbacks rather than having an ever-expanding API for every variation of every option that people might want without having to write any code.

if you have a specific question about the bar groups demo you're confused about, then i'm happy to help here, otherwise you can use something like Chart.js for all your charts except for charts that need exceptional performance for huge timeseries datasets.

if someone wants to wrap uPlot & plugins into an additional layer that exposes an ready-to-use bar chart API, then they are welcome to do that as well.
