### ISSUE TITLE
Ability to draw axis lines

### ISSUE THREAD

**Issue by gerhat** [leeoniya/uPlot#547]
Is there a way to draw a line along the axis ticks?

I would like to go from this:
<img width="907" alt="current" src="https://user-images.githubusercontent.com/11447903/125740895-997ed9e5-bf8b-4c7f-add1-4555653626d6.png">

To this:
<img width="907" alt="desired" src="https://user-images.githubusercontent.com/11447903/125740956-d2a6f41d-8477-4808-ab71-c9d62a4c471a.png">

Thank you

**Comment by leeoniya** [comment]
you can kinda hack this using css, so i've been hesitent to add it, but the css solution doesnt help if you have multiple y axes:

https://jsfiddle.net/cL452906/

```css
.u-over {
  box-shadow: -1px 1px #333;
}
```

make sure to use `box-shadow` and not `border`, since that will affect cursor and hoverpoint positioning: https://jsfiddle.net/cL452906/1/

of course, you can always draw them yourself:

https://jsfiddle.net/cL452906/2/

**Comment by gerhat** [comment]
@leeoniya thank you very much for your reply. I prefer the `drawAxes` hook approach, since it gives more flexibility.

I was wondering if there is a way to get a continuous line in case of a dashed grid.

Example:
https://jsfiddle.net/rsgbaenz/

**Comment by leeoniya** [comment]
just unset lineDash:

```js
u.ctx.save();
u.ctx.beginPath();
u.ctx.setLineDash([]);
u.ctx.strokeStyle = "#333";
u.ctx.lineWidth = 3;
...
```

https://jsfiddle.net/guxwnd0t/

**Comment by gerhat** [comment]
Thank you so much for your help!
