### ISSUE TITLE
How to change time format from 12h to 24h in legend?

### ISSUE THREAD

**Issue by atay** [leeoniya/uPlot#548]
When I point a mouse over a point of chart, it's showing 

**Time: 2021-07-01 6:00 PM**

Is there a way to format that date to use 24h, so in this case 18:00?

**Comment by leeoniya** [comment]
for legend display, something like this should work:

```js
{
  series: [
    {
      value: "{YYYY}-{MM}-{DD} {HH}:{mm}:{ss}"
    }
  ]
}
```

if you want to adjust what's shown on the axis ticks, it requires more config, since the tick value are dynamic based on time delta you're viewing. you can see the configurable `axis.values` formatting table here:

https://github.com/leeoniya/uPlot/tree/master/docs#axis--grid-opts
