### ISSUE TITLE
Hardcoded max places in findIncr

### ISSUE THREAD

**Issue by tmcnitt** [leeoniya/uPlot#549]
I am working with nanosecond timestamps. Since JS time objects only go to millisecond, I am rendering them with {time: false} and then using a custom values function in the axes to format them. uPlot decides the increment to use by the [findIncr](https://github.com/leeoniya/uPlot/blob/8449de358d0a3e590671886fdb6d67aa8e428bf5/src/uPlot.js#L251) method. However, there is a hardcoded 17 digit limit. This means the axis will not render, even if they are formatted to something much smaller before actually getting displayed. Maybe it would be possible to have an option to set the max digit? Or the code could run the values through the value function before deciding if it violates the max digit limit

For now I have been able to just increase the limit, but possibly there is a more elegant solution for future uses with really large numbers in an axes that get formatted

**Comment by leeoniya** [comment]
it's limited to 17 because i had issues being unable to advance ticks with higher precision than this, you'll often get back the same number when adding the a tiny increment and land in an infinite loop.

have you considered just pre-subtracting some logical ms-precision baseline and formatting that as a calendar date, (you can render it in the somewhere on the canvas or next to the chart). then the remaining numbers can just be offset during legend display in `series.value`.

also related: https://github.com/leeoniya/uPlot/issues/111

**Comment by tmcnitt** [comment]
Thanks for the info. I also set the increments to only really large numbers that would make sense as ticks, so think I'm escaping the infinite loop bug. For now this approach seems to be working, but will try the offset method if any other issues come up. If I go that route, I will write up a demo since it seems to a common question.

**Comment by leeoniya** [comment]
> If I go that route, I will write up a demo since it seems to a common question.

that'd be :100: .00000000000000000 :rofl:
