### ISSUE TITLE
Typescript Definition Error - uPlot.Series.Points

### ISSUE THREAD

**Issue by tlaverdure** [leeoniya/uPlot#552]
I'm getting this error with the latest release while compiling my typescript code:

```bash
Error: node_modules/uplot/dist/uPlot.d.ts:704:19 - error TS2694: Namespace 'uPlot.Series.Points' has no exported member 'Paths'.

704    paths?: Points.Paths;

```

Would submit a PR but I'm not entirely sure why this may have changed. 😄

**Comment by leeoniya** [comment]
d'oh!

of course VS Code is silent, and the only clue is when hovering:

![image](https://user-images.githubusercontent.com/43234/126678213-cef22fa4-7181-4920-bf6f-90611eb6aa8f.png)

> Would submit a PR but I'm not entirely sure why this may have changed.

`Series.Points.Paths` is new and follows the same pattern as `Series.Paths` instead of relying on `series.points.show` to do the both rendering and/or shouldShow determination.

of course i forgot to add it to the types properly :(

can you try compiling with the latest `master` and see if that works?

**Comment by tlaverdure** [comment]
@leeoniya that fixed it. Thanks!
