### ISSUE TITLE
no way to set y-axis height?

### ISSUE THREAD

**Issue by ileadu** [leeoniya/uPlot#557]
Just find axis.size to set y-axis width

May I set the y-axis height or hide the value over 200?
<img width="1032" alt="2021-08-061 43 09" src="https://user-images.githubusercontent.com/237095/128397137-fa383e13-9736-4293-b43b-4cc364fd2309.png">

![download (2)](https://user-images.githubusercontent.com/237095/128451199-ef9f330a-f1a8-4895-a4dd-ba43f053d4b8.png)

**Comment by leeoniya** [comment]
> or hide the value over 200?

yes, this is the way to do it (code below): https://jsfiddle.net/yzwcfatd/

however, this won't prevent the volume bars from colliding with the candlesticks since the volume and price scales are independently ranged; there's no real way to prevent this with a single plot. it may be a good idea to split this into 2 stacked plots that have cursor sync enabled. you can then hide the x axis on one of them and do a bit of DOM hacking to get a combined legend (see how the "Inverted Log10 Y Scale" is constructed from two charts here: https://leeoniya.github.io/uPlot/demos/log-scales2.html)

```js
const data = [
  [0.8,2,3,4,5],
  [-30, 10, 12, 40, 100]
];

const excludeOver40 = (u, splits) => {
  return splits.map((s, i) => s <= 40 ? s : null);
};

const opts = {
  width: 800,
  height: 500,
  scales: {
    x: {
      time: false,
    },
  },
  axes: [
    {},
    {
      filter: excludeOver40,
      grid: {
        filter: excludeOver40,
      },
      ticks: {
        filter: excludeOver40,
      }
    },
  ],
  series: [
    {},
    {
      stroke: '#059',
    },
  ],
};
```

![image](https://user-images.githubusercontent.com/43234/128458548-c072c8c4-170c-42de-886f-39f5ae7ad391.png)

**Comment by leeoniya** [comment]
@ileadu instead of filters, you can also provide an `axis.splits()` with the tick values you want: `() => [-40, -20, 0, 20, 40]`
