### ISSUE TITLE
Data updates with static xAxis don't redraw correctly

### ISSUE THREAD

**Issue by alextarrell** [leeoniya/uPlot#57]
I'm attempting to plot a live-updating data set however instead of the new data getting drawn, uPlot will always draw the original paths. After some digging I realized that my xAxis never changes, causing the series' paths to never be reset.

A simple example of the data I'm plotting (notice the x axis data doesn't change)
```json
setData([[1, 2, 3, 4, 5], 
         [1, 3, 5, 7, 9]])
...
setData([[1, 2, 3, 4, 5], 
         [2, 4, 6, 8, 10]])
```

This appears to be the relevant code:
https://github.com/leeoniya/uPlot/blob/826fa0118c3b715344fc00439d4dbba5bec2d6f2/src/Line.js#L766-L767

Right now I'm working around the issue with `uplot.series.y.forEach(s => (s.path = null))` right before my call to setData but that seems less than ideal. Is there a more obvious way I should be doing things? Or is this an issue with the library itself? Thanks in either case.

**Comment by leeoniya** [comment]
yeah, this looks like a bug. i'll dig a bit more into it later today.

path & min/max invalidation have to be done carefully since they're expensive to rebuild. just look at the contexts of `setScale()` calls in the code. either an improvement in the heuristics or slight refactoring will be necessary.

if you wanna take a stab at it, you can uncomment all the `console.log()` calls and play around with the demos to compare old and new behavior.

**Comment by leeoniya** [comment]
ok, this should be fixed.

i can't think of a reason not to reset everything in the `setData()` call - all the streaming demos end up in that codepath anyways.
