### ISSUE TITLE
Jitter on x-axis ticks with scroll

### ISSUE THREAD

**Issue by jamie0walton** [leeoniya/uPlot#571]
While editing your resize demo to move the legend and add a real-time scroll I noticed some jitter on the gaps between x-axis tick marks. Attached video and edit to the resize that illustrates this. I observed this in Microsoft chromium edge.

https://user-images.githubusercontent.com/4251994/131320736-5facd65e-90db-4d74-aaf3-ab36cffd9c86.mp4

[resize.txt](https://github.com/leeoniya/uPlot/files/7075798/resize.txt)

**Comment by leeoniya** [comment]
this is due to pixel rounding, which increases perf and rendering crispnesss. you can control the level of rounding using the global and per-series `pxAlign` options. if you have a lot of data, i would advise against disabling it completely since the pathbuilder uses unique x coords to reduce the amount of line segments uPlot needs to draw.

read carefully through this:

https://github.com/leeoniya/uPlot/issues/241

demo:

https://leeoniya.github.io/uPlot/demos/pixel-align.html

**Comment by jamie0walton** [comment]
OK, that's an important proviso. Thanks.
