### ISSUE TITLE
Plot disappears when scale distribution is logarithmic and min range is 0

### ISSUE THREAD

**Issue by gerhat** [leeoniya/uPlot#577]
Range `[0, 2000]` works fine when scale `distr` is linear but disappears when logarithmic.

Fiddle:
https://jsfiddle.net/4mznqb8a/16/

Do I miss something?

**Comment by leeoniya** [comment]
log scales cannot have bounds or values <= 0, because mathematically, logarithms are only defined for non-zero positive values.

you can set your min to something like .001 and it will work. uPlot will still attempt to plot 0 and negative _values_ below the minimum log plot boundary by clamping everything to 1/10th of the scale min, but this is not really accurate either, cause those values are all infinitely far below the plot edge (you can see this 1/10th clamping in the bottom chart here: https://leeoniya.github.io/uPlot/demos/log-scales2.html)

you can instead use an arcsinh distribution, which becomes linear below a threshold of your choosing: https://leeoniya.github.io/uPlot/demos/arcsinh-scales.html
