### ISSUE TITLE
ZingChart, AmCharts, etc. Benchmark is a bit misleading

### ISSUE THREAD

**Issue by tpowell** [leeoniya/uPlot#582]
Hey first off cool lib with clear indications of what it aims to do!

Anyway to the meat of the perf of other libs matter, if you benchmark a larger feature lib you probably should provide a better example to compare properly.  For example, most of the libs have flags to address perf if you are willing to reduce feature sets, allow sampling, etc.  For example, check out [https://app.zingsoft.com/demos/embed/YMCYMHY6 ](https://app.zingsoft.com/demos/embed/YMCYMHY6 )and you'll see it is your demo with a small matter of flags and it is a much better performance like 2x+.  I am sure we could better with some tuning as could all the others like HighCharts with Boost module, AMCharts, etc. which all likely have misleading numbers due to just a quick and dirty try of their stuff.  Maybe put out a call for interest to them?

Anyway cheers and keep up the work!

**Comment by leeoniya** [comment]
> Anyway to the meat of the perf of other libs matter, if you benchmark a larger feature lib you probably should provide a better example to compare properly. For example, most of the libs have flags to address perf if you are willing to reduce feature sets, allow sampling, etc.

it's very hard to compare libraries apples-to-apples with very different feature sets, goals and APIs. i have tried my best to find the most performant settings for each lib (highcharts boost module, chartjs disable parsing/animations, lttb sampling in echarts, etc.) and welcome any improvements to the benchmarks that are exist -- i'm no expert in any of these libs!

if you have improvements such as above, definitely submit a PR!

that being said...

- i'm not going to make custom builds of libs to shake out features (due to lack of time); running the benchmarks manually already takes several hours. if a "light" pre-complied version of a lib exists, then i can certainly use it. and if there are runtime options to disable stuff that is not applicable, then those can/should be turned off.
- any kind of sampling must not sacrifice data accuracy in a way that causes spikes to randomly disappear (based on settings or chart width/height, or devicePixelRatio or browser zoom). your example above does not appear to suffer from this from an initial look, but i'd need to do an overlay of both versions (with and without sampling) before enabling such a setting.
- i'm cautious to include any settings that are not publicly documented or are private APIs, since 99.99% of users will never find them, so i usually ask where such settings are recommended or can be discovered online or docs by the typical user. uPlot can be considered to be "fast by default", requiring 0 tweaking to get 100% of its performance, so this is certainly relevant.

cheers!

**Comment by leeoniya** [comment]
i see there is official docs for this here [1], so try this out in the next few weeks.

[1] https://www.zingchart.com/docs/tutorials/features/performance
