### ISSUE TITLE
Displaying series values only in legend

### ISSUE THREAD

**Issue by miohtama** [leeoniya/uPlot#592]
I am drawing OHLCV diagrams using your excellent uPlot library. Thank you for it!

I am currently having a setup similar to the [OHLCV example](https://github.com/leeoniya/uPlot/blob/master/demos/candlestick-ohlc.html) where the legend hovers over the chart.

I have some data points that make the underlying candle, like average trade size, which I would like to display only in the legend, only on the mouse over - this information is not relevant to be shown on the plotted out graphs.

What would be the best way to have series that only appear in the legend?

**Comment by leeoniya** [comment]
two methods:

1. use `series.values` instead of `series.value` to display additional data in a table-style legend. see [1] [2]
2. use the `init` hook to append additional DOM elements to `.u-legend` element and use the `setLegend` hook to modify your added DOM.

[1] https://leeoniya.github.io/uPlot/demos/time-periods.html
[2] https://leeoniya.github.io/uPlot/demos/scatter.html (bottom plot)
