### ISSUE TITLE
Change style for a particular segment of a line

### ISSUE THREAD

**Issue by tobyzerner** [leeoniya/uPlot#625]
Thank you for this spectacular library!

I'm wondering if there's a way to change the style for only a particular segment of a line? Like Stripe do in their dashboard charts:

![Screen Shot 2021-11-28 at 7 30 47 pm](https://user-images.githubusercontent.com/128862/143735504-70048959-421f-4d35-b46d-0c2c8add4f93.png)

**Comment by leeoniya** [comment]
there's no simple way to do it, because drawing multiple segments makes things bands and area fills very complex and performance very poor.

however, you can kinda fake it by creating a repeating gradient and returning it as the stroke color from a `series.stroke()` function. it won't be as pretty as properly directionally-aligned dashes, but can work. if you're okay with just a differently colored segment (e.g. lighter blue), it would work better and without caveats.

here's a demo that does this: https://leeoniya.github.io/uPlot/demos/gradients.html

if you need dashes, you'll need to combine the above technique with a more complex gradient or canvas pattern. something like: https://stackoverflow.com/questions/56398519/how-to-make-a-repeating-canvasgradient

**Comment by tobyzerner** [comment]
Great, thanks! I might settle on a lighter color :)

**Comment by leeoniya** [comment]
also, if you dont have a lot of data and are not concerned with perf, you can always write your own `series.paths()` generator and DIY all the line drawing and canvas stunts yourself using `u.valToPos()`, but you'll have to handle gap detection, clipping, etc. yourself :)

**Comment by tobyzerner** [comment]
Thanks for the extensive help @leeoniya! 

P.S. First time I've seen Placement.js being used [in the wild](https://github.com/leeoniya/uPlot/blob/master/demos/cursor-tooltip.html) - thanks for using it :)

**Comment by leeoniya** [comment]
you may have finally found your answer to https://github.com/tobyzerner/placement.js/issues/3#issuecomment-797116578 🤣 

i actually prototyped a tooltip impl based almost entirely on IntersectionObserver and ResizeObserver which performed quite well, but still had a few glitches to work out. got busy with other stuff, but i'll get back to it :)

**Comment by tobyzerner** [comment]
Aha I forgot about that issue! For sure I'd love to take a look

**Comment by leeoniya** [comment]
just stumbled randomly upon this: https://github.com/atomiks/floating-ui
