### ISSUE TITLE
Series / Axes symmetrical value formatting

### ISSUE THREAD

**Issue by alextarrell** [leeoniya/uPlot#64]
Is there any particular reason why the series's values are formatted individually while the axes's values are formatted across the set? From a usage perspective they seem inconsistent and simply serve to complicate the api. Since the axes's values result must be same length as the ticks being provided it seems both could operate over the individual values. If having access to the index is valuable (which certainly could be) the index could be provided as a second parameter.

```
let opts = {
  series: {
    y: [{value: rawValue => rawValue.toFixed(1) + "%"}]
  },
  axes: {
    y: [{values: ticks => ticks.map(rawValue => rawValue.toFixed(1) + "%")}]
  },
};

==>

let opts = {
  series: {
    y: [{value: rawValue => rawValue.toFixed(1) + "%"}]
  },
  axes: {
    y: [{value: rawValue => rawValue.toFixed(1) + "%")]
  },
};
```

On a side note, is there any way the axes's value mappers could default to using the one defined for the corresponding series (or maybe the other direction)? While the flexibility is appreciated, even many of the examples are just duplicating the same function in both places.

**Comment by leeoniya** [comment]
> Is there any particular reason why the series's values are formatted individually while the axes's values are formatted across the set?

it started uniform but then changed to the current api because...

you may want to skip labeling some ticks if the labels sizes make things too dense - the full signature is actually `values(ticks, space)`. the ticks may not be evenly spaced, e.g. DST transitions or variable width months. providing the full tick array, so you know how many ticks there are and how they're distributed. this allows you to make all the formatting at once without having to keep state externally while a `value()` callback fires for every tick.

> On a side note, is there any way the axes's value mappers could default to using the one defined for the corresponding series (or maybe the other direction)?

this probably makes sense for numeric y or x axes, but not for temporal x, where the axes tick labels differ in formatting and are shortened to fit along the axis while the value in the legend is uniform. i dont want to introduce automagic value/values sharing only when certain conditions are met. it's easy enough to define and re-use formatters rather than repeating them inline.

**Comment by alextarrell** [comment]
Makes perfect sense, thanks for the response!
