### ISSUE TITLE
Visual artifacts when clipping gaps

### ISSUE THREAD

**Issue by murphycj** [leeoniya/uPlot#647]
Hello! Thanks for the great library!

While making a line plot, I've noticed visual artifacts between two line segments when separated by a null/missing value. These issues become more noticeable when there is more data in the figure.

I attached an example figure and jsfiddle example. In the example I have alternating horizontal line segments at +1 and -1, separated by `null`. There should be no line segments connecting the +1 and -1 segments. My guess is that it is due to some rounding issue when it does the clipping?

https://jsfiddle.net/murphycj/s2c5hbkt/13/

<img width="757" alt="Screen Shot 2022-01-07 at 9 44 24 PM" src="https://user-images.githubusercontent.com/3837196/148628757-34d46016-1853-40d1-a726-78804e286e39.png">

Do you think there is an easy fix for this? Thanks!

**Comment by leeoniya** [comment]
first, thanks for the clear and terse bug report with reduced repro code :+1: :heart: 

> My guess is that it is due to some rounding issue when it does the clipping?

that's a pretty good guess :). it's because line pathbuilder's gap construction does not expand the gap width to include the line width in order to avoid accidentally also clipping out additional data at the gap edges.

for your type of dataset it may be more appropriate to switch to the stepped pathbuilder (via `series.paths`) which _does_ account for line width during gap building by default (via `{ascDec: false}`) [1]

https://jsfiddle.net/pk4mtyza/

```js
paths: uPlot.paths.stepped({align: 1})
```

alternatively, you can mutate the gaps array to expand each gap manually by a pixel amount if you consider this to be safe for your dataset:

https://jsfiddle.net/pk4mtyza/2/

```js
gaps: (u, seriesIdx, idx0, idx1, gaps) => {
  let lineWidth = u.series[seriesIdx].width;
  return gaps.map(([fromPx, toPx]) => [fromPx - lineWidth, toPx + lineWidth]);
},
```

[1] https://github.com/leeoniya/uPlot/blob/5680d8b81aefc8cc7035eb51ff99b3d1dfc733f6/dist/uPlot.d.ts#L640-L641

**Comment by murphycj** [comment]
Thanks for the quick response! And thank you for the suggestions. However, the stepped pathbuilder would not be a good solution for me due to the nature of my data. While the second solution of mutating the gap does help somewhat, I found that when where there is a lot of data in the figure, the gap clipping ends up clipping all data so that it looks like the figure has no data.. this is an even worse problem on small screens.

So I ended up just copying the code from https://github.com/leeoniya/uPlot/blob/master/src/paths/linear.js and modifying it so that is uses `moveTo` instead of gap clipping.

**Comment by leeoniya** [comment]
> I found that when where there is a lot of data in the figure, the gap clipping ends up clipping all data so that it looks like the figure has no data.. this is an even worse problem on small screens.

can you make a fiddle with the real data?

yeah, if you have a lot of intermittent nulls, the gap clips can probably destroy what little is left, though at that point you might be better off just drawing the points and let them blend into a "line" - not a great solution for perf (you'll probably want square points to avoid arc() & antialiasing overhead with large datasets).

> So I ended up just copying the code from https://github.com/leeoniya/uPlot/blob/master/src/paths/linear.js and modifying it so that is uses moveTo instead of gap clipping.

unfortunately, using moveTo() prevents the path from being fill()-able, which is why gaps are done via clip paths in uPlot. if this can be done cheaply without clip paths somehow, i'd certainly be interested in hearing about it.

maybe if some users are okay giving up fills for some series, i can provide a moveTo option in lieu of using gap clips?

**Comment by murphycj** [comment]
Here you go: https://jsfiddle.net/murphycj/s2c5hbkt/23/
Might be slow to load since it is a lot of data.

In my case, I don't need the paths to be filled in and I am not a fan of using points instead of lines. So in my case at least, using moveTo works great... so I think having moveTo as an option would be good.

**Comment by leeoniya** [comment]
@murphycj  thanks, i've added a demo with your data here for further discussion/iteration:

https://leeoniya.github.io/uPlot/demos/sparse.html

a few things stand out to me:

1. when drawing raw points without lines it's:
    1. difficult to asses a change in volatility / noise
    2. easy to miss spikes in normally in mostly-well-behaved regions
    3. easy to completely miss spikes that are off-scale
2. when drawing lines for ultra-sparse datasets like this one you'll always risk not drawing single points surrounded by gaps, regardless of the method you use. for example, the `10` spike in `1,1,1,null,10,null,1,1,1`. the orange trendline in the points demo tries to address this by force-rendering single points surrounded by `null` values that would necessarily get clipped by adjacent gaps - https://leeoniya.github.io/uPlot/demos/points.html

you can see pretty significant differences in the highlighted region if the attached image.

i'm interested to see your modified `moveTo()` pathBuilder that does not suffer from this phenomenon at any zoom level. i did a few simple moveTo() prototypes and in each case spikes would randomly appear/disappear at different chart sizes, zoom levels and scale ranges. can you post your modified pathBuilder code (or make a PR against the `sparse.html` demo for easier dissecting)?

when there are so many gaps, i think the better strategy would be to modify the gaps array in a way that is aware of the scale range, so if you have 16k points in view, it removes gaps that are < 2px wide, which effectively makes it act as a conditional `spanGaps`. another demo that does custom gap insertion is the bottom chart here: https://leeoniya.github.io/uPlot/demos/missing-data.html

![image](https://user-images.githubusercontent.com/43234/149036345-23e37208-cd50-4a38-8f89-fafc8eb9ef2f.png)

**Comment by murphycj** [comment]
Thanks for the code samples. Your `naive w/moveTo()` is basically what I want to do, and your implementation is much simpler then mine, lol... so I'll definitely be using yours. 

As for (1), I agree with your assessment.

As for (2), not rendering single points surrounded by nulls is actually fine for me (and is actually desirable). The algorithm I use to generate this data should ideally be able to either remove such isolated points or do some smoothing/interpolation, but is not always perfect. 

My implementation is not great, so not sure it is worth looking at. But if you still want to look at it you can go here: https://github.com/leeoniya/uPlot/pull/654
One additional thing I do is set a max absolute change between `y` values that have adjacent `x` values.

The indentation got messed up somehow in the PR. Not sure what's going on there, looks fine in my local editor. Feel free to just close/delete it once you're done.
