### ISSUE TITLE
[TS] using typed arrays in AlignedData

### ISSUE THREAD

**Issue by kristofgilicze** [leeoniya/uPlot#667]
**I'm unable to pass type checks, without casting it to a regular array.**
![image](https://user-images.githubusercontent.com/16563329/156901692-87d2aba3-b847-4c88-87f3-274090108913.png)
```ts
const foobar = new Float32Array()
const data: uPlot.AlignedData = [x, Array.from(foobar)]
```
The plot seems to be working just fine with the Float32Array.
Im not sure how expensive is casting, but seems wasteful.

Is this limitation intentional in uPlot, or typed arrays should be possible ?

**Comment by leeoniya** [comment]
for 100k values the casting is ~7ms on my machine:

```js
let len = 1e5;

let tArr = new Float32Array(len);

for (let i = 0; i < len; i ++) {
  tArr[i] = Math.random() * 100;
}

console.time('convert');
let arr = Array.from(tArr);
console.timeEnd('convert');

// convert: 6.90087890625 ms
```

uPlot can use typed arrays directly, but since they cannot contain `null` values, you cannot represent data gaps in them and since they cannot contain `undefined` values, `uPlot.join()` will result in all interpolated spans to be 0 if this util is used to combine multiple series with different x values.

we can probably add typed arrays to the accepted data formats in `.d.ts`, but they will only work correctly for a subset of cases, which makes me hesitant. i would probably prefer that users add a `// @ts-ignore` or override the type to stop TS from complaining instead of pay the cost of the conversion.

**Comment by leeoniya** [comment]
added in https://github.com/leeoniya/uPlot/commit/9cc64305d8051658b90d80eb227e3944910d3ef8
