### ISSUE TITLE
Linear-log dynamic switch 

### ISSUE THREAD

**Issue by gabriel-turturica** [leeoniya/uPlot#669]
Hello, I am trying the setup a dynamic change between linear and logarithmic scales on the Y axis. There seems to be a problem with the recalculation of the axis parameters. 

Fiddle (right click event for the linear scale): 
https://jsfiddle.net/qf4nwkbs/7/      

Am I missing something ?

**Comment by leeoniya** [comment]
generally you cannot change options after init. this is because many internal scale and axis functions are pre-computed and cached to make drawing faster at runtime.

if such a feature was to be added it would probably have to be included as an additional option to `u.setScale('y', {distr: 1})` which would re-init the internal functions. it's worth checking how much extra code this will add.

for now, you have to destroy and re-init the chart which is very fast already, unless you have an insane number of series and/or points. since this operation/toggle should be a quite rare i'm hesitant to add special code to support it; there are many other opts that will still require re-init to change, so the case to make distr special has to be quite strong.

**Comment by gabriel-turturica** [comment]
Yeah, this operation should not happen that often so I guess destroy and re-init should be good enough. Thanks for the help.
