### ISSUE TITLE
Ticks not showing up with big values

### ISSUE THREAD

**Issue by balthazar** [leeoniya/uPlot#674]
Hello and apologies for the issue.
Searched a couple of them (#102, #467 among others), but couldn't find a solution to my problem.

When providing big values to uplot, the scale and everything works exactly as expected. The only issue comes from how the ticks are behaving. When providing the `values` function to the axis, it is simply not called as no tick is being made.

I made two codepens demonstrating the issue, with the same code and same dataset, but one being divided by a thousand, making the ticks properly appear and call the `values` function.

Here is the ["buggy" one](https://codepen.io/_balthazar/pen/dyJMREa) and here is the [working one](https://codepen.io/_balthazar/pen/oNpxejV)

Let me know if there is anything obvious I'm missing!

Thank you so much

**Comment by leeoniya** [comment]
uPlot expects time values to be in UNIX epoch seconds but JS timestamps are epoch milliseconds. if you want to provide milliseconds in your data, you can set `opts.ms: 1`.

https://github.com/leeoniya/uPlot/blob/852829eced8a2bc52c58646636f4daa9b42e68cc/dist/uPlot.d.ts#L357-L358

in your examples all your milliseconds are 000 anyways, so it probably makes more sense to divide by 1000 at the query or server and not waste a bunch of network throughput on transmitting a trailing 000 with each timestamp.

**Comment by balthazar** [comment]
@leeoniya Hum I'm sorry but the issue isn't with the time / X values, it's with the Y ticks.

**Comment by leeoniya** [comment]
ah, sorry.

there's no good way to support numbers outside of JavaScript's `Number.MAX_SAFE_INTEGER`. your data supplies them as strings like `'20756451857089720272'`, but that won't work. BigInt is a non-starter unfortunately, since you cannot use normal math operators on those objects, and the performance will be quite terrible.

i've never encountered a use case when there's a need that level of precision, so my recommendation is to divide or parse huge numbers into something more human and use order-of-magnitude suffixes for the tick labels, like `1.237e13`.

**Comment by balthazar** [comment]
Gotcha, thanks for the clarification!

**Comment by balthazar** [comment]
@leeoniya Actually, since everything is working in the chart besides the call to the `values` function, could you give me any clue of what part of the code is blocking such call? Am I correct to say [this](https://github.com/leeoniya/uPlot/blob/master/src/uPlot.js#L1668) is the place where it should be called?
