### ISSUE TITLE
How to format tooltip plugin using the default axis stamps?

### ISSUE THREAD

**Issue by WhiskeyRomeoTango** [leeoniya/uPlot#695]
Hi @leeoniya !

First I would like to say thank you for maintaining such a robust and performant library. With some explorations I was able to achieve all my weird and demanding use cases with uPlot, while maintaining high performance!

So I played with the tooltip plugin by rearranging the position. Then I formatted the the date using `fmtDate()`, like so:

```javascript
    function utcDate(ts) {
      return uPlot.tzDate(new Date(ts * 1e3), 'Etc/UTC');
    }
    const dateFormatter = uPlot.fmtDate('{M}/{D}');

    u.cursorX.style.left = left + "px";
    u.cursorX.style.top = u.over.style.height;
    u.cursorX.textContent = dateFormatter(utcDate(u.posToVal(left, "x")));
    u.cursorX.style.transform = 'translate(-50%, 0)';
```

My question is - without assigning my own `incrs` and `values` options, how may I extract the default formatting strings (tpls), so that my tooltip format changes dynamically with the zoom? For example,

Right now, my tooltip is formatted as `{M}/{D}` and it stays that way no matter how much I have zoomed in:

![image](https://user-images.githubusercontent.com/18691712/168507867-14f39bc7-78ab-4364-bbd3-7961801fd20c.png)

When I zoom in, I would love to see 2pm instead of the date.

![image](https://user-images.githubusercontent.com/18691712/168517920-99d43b38-66c4-4c26-988c-f1d4396cf786.png)

Thanks again for your support!

**Comment by leeoniya** [comment]
i think you'd just have to create several `dateFormatter`s and dynamically pick which one to use based on delta between `u.scales.x.min` and `u.scales.x.max`?

**Comment by WhiskeyRomeoTango** [comment]
Thank you! Your example was pretty clear. I kinda liked the default config and wondered if there is a way to expose those for me to use. I guess I'll just holistically implement my `incrs` and `values` in `opts.axes`!

**Comment by leeoniya** [comment]
i guess what you're asking for does kind of exist.

`axis.values` becomes the compiled function that -- given an array of splits and other params - will return an array of formatted labels based on the table.

compiled here:
https://github.com/leeoniya/uPlot/blob/ad85ee2a182257a014416ef1c5f507c3d3a3cca5/src/uPlot.js#L1010-L1011

with this resulting function:
https://github.com/leeoniya/uPlot/blob/ad85ee2a182257a014416ef1c5f507c3d3a3cca5/src/opts.js#L271

`foundSpace` and `foundIncr` are cached under `axis._found`:

https://github.com/leeoniya/uPlot/blob/ad85ee2a182257a014416ef1c5f507c3d3a3cca5/src/uPlot.js#L1585

for `splits` you would always pass an array of 1, containing your cursor x value.

something like this will get you close:

https://jsfiddle.net/k62wts38/2/

```js
let x = document.getElementById("x");

let data = [
  [1652763084, 1652783084, 1652803084],
  [35, 71, 20],
  [90, 15, 70]
];

const opts = {
  width: 600,
  height: 300,
  hooks: {
    setCursor: [
      u => {
        let xAxis = u.axes[0];
        let [foundIncr, foundSpace] = xAxis._found;
        let vals = xAxis.values(u, [u.posToVal(u.cursor.left, 'x')], 0, foundSpace, foundIncr);
        x.textContent = vals[0];
      }
    ],
  },
  series: [
    {},
    {
      stroke: "red",
    },
    {
      stroke: "blue",
    },
  ],
};

let u = new uPlot(opts, data, document.body);
```

the reason it always displays the year is because the "rollover" splits always get the extra contextual part rendered, and we're always passing a single split which is always considered a rollover.
