### ISSUE TITLE
Question: how to zoom out?

### ISSUE THREAD

**Issue by alexey-milovidov** [leeoniya/uPlot#712]
It is non-obvious how to zoom out if I already zoomed in?
Maybe make it by right-click?

**Comment by leeoniya** [comment]
it would be strange to hijack a button that people expect to normally pull up a context menu. double click was chosen since it has no native/default behavior in browsers.

you can always hook up your own event listeners (often in [capturing phase](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#event_bubbling_and_capture)) to the DOM and use uPlot's API to zoom out on right click or wheel click, or ctrl+click, etc, if you want to.
