### ISSUE TITLE
posToVal() result is not precise

### ISSUE THREAD

**Issue by lucian-baciu** [leeoniya/uPlot#728]
Hello,

I'm having a normal chart with X being a 'time' axis. My first X value is "1658912732000". If I call `u.postToVal(0, 'x')`, I receive "1658912732849" - see last 3 digits. I would expect that for the extremes to receive exactly the values from data.

Thank you!

**Comment by leeoniya** [comment]
`.posToVal()` converts a pixel coord to a scale value, not a raw data value. there will always be some amount of rounding when converting between pixels and raw data since there's no single pixel that only corresponds to a single infinitely narrow point in time. if you'd like to get the value from the nearest datapoint, you can do

```js
u.data[0][u.valToIdx(u.posToval(0, 'x'))]
```

that being said, you'll need make a demo that exhibits this behavior, since i cannot reproduce what you're describing:

https://jsfiddle.net/ya2rx15u/

```js
let data = [
  [1658912732000, 1658923732000],
  [0, 1],
];

const opts = {
  width: 800,
  height: 400,
  ms: 1,
  series: [
    {},
    {
      label: "Data 1",
      stroke: "blue",
    },
  ],
};

let u = new uPlot(opts, data, document.body);

queueMicrotask(() => {
  console.log(u.posToVal(0, 'x'));
});
```

**Comment by lucian-baciu** [comment]
in your example it's not reproduced, even with my data. most likely there is something else in my code. I will check and get back

**Comment by lucian-baciu** [comment]
![Screenshot_55](https://user-images.githubusercontent.com/52832263/181804576-8793e45d-807e-4ab4-8613-9a1aa3f8cc27.jpg)

Do you think there can be other configs that can affect this?

**Comment by lucian-baciu** [comment]
Nevermind, my bad. You can close the issue.

`scales: {
        x: {
          time: true,
          min: this.selection?.from,
          max: this.selection?.to
        }
      },`

**Comment by leeoniya** [comment]
:+1:
