### ISSUE TITLE
Better support for gamma correction?

### ISSUE THREAD

**Issue by alexey-milovidov** [leeoniya/uPlot#730]
This artifact is noticeable even on 4K display:
![Screenshot_20220731_224936](https://user-images.githubusercontent.com/18581488/182044869-c5ff0c7a-ac3a-4cfc-a806-c73c5bba7e31.png)

(perceived brightness of the line changing periodically - it appeared darker when the line is smoothed between two pixels)

**Comment by leeoniya** [comment]
uPlot relies on the [Canvas 2D API](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) to do the actual drawing, so however the underlying rendering code (Skia, QuantumRender, etc.) chooses to do line antialiasing and alpha composition is generally out of uPlot's control. maybe there's something in https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation, but not sure.

are you setting an alpha value < 1 on the stroke color?

there are probably some pretty expensive and complex ways to work around this by shrinking the fill area, but that could easily halve the performance, since we cannot reuse the same Path2D contour for fill and stroke. and even this is unlikely to be a complete work-around since it will fall over for inter-series shape compositing.

**Comment by alexey-milovidov** [comment]
Thank you! Understood, most likely it is out of our control.
PS. No, the color does not have an alpha component, just `#864`.
