### ISSUE TITLE
Offscreen Canvas Support?

### ISSUE THREAD

**Issue by skortchmark9** [leeoniya/uPlot#733]
Hey, have you experimented at all with offscreen canvas? I'm trying to draw ~10+ plots * many series and running into some performance issues with Flot. My data is already coming from a worker, so it would be cool if the rendering could as well. I understand dom-based axis labels etc would still need to live on the main thread.

**Comment by leeoniya** [comment]
> Hey, have you experimented at all with offscreen canvas?

i have not. not sure how much benefit there would be, but certainly worth checking out. the slowest parts of uPlot that touch canvas are `ctx.lineTo()`, `ctx.fillText()`, and `ctx.font` during resize. i would like to see some perf profile differences of doing a few thousand calls to each of those APIs in a regular and an offsecreen canvas.

> and running into some performance issues with Flot

so are you asking theoretically (since Flot and uPlot both use canvas) without trying out your use case in uPlot? or do you have code and data that exhibits this slowness in uPlot that you can share?

**Comment by leeoniya** [comment]
going to close this for now since i think this is a pretty large undertaking, for a feature only available in a single browser engine, without a concrete demo from you that shows `~10+ plots * many series and running into some performance issues with Flot`. in Grafana we have many such dashboards and no performance issues related to uPlot speed.

if you'd like to get involved in making some proof of concept code for offscreen canvas comparisons or submit some problematic demos, then i'll be happy to take a look and revisit this in the future.
