### ISSUE TITLE
Line series get clipped when they reach the top/bottom of graphing area

### ISSUE THREAD

**Issue by markoleh** [leeoniya/uPlot#808]
Firstly, thank you for creating such a great graphing library. It has been incredibly helpful in visualizing our data with great performance and easy customization.

We have noticed a minor inconvenience in the library. When we plot graph series with lines that reach the top or bottom of the graphing area, the lines are partially clipped. Canvas extends further, so this is not an issue with the canvas size. We often have statically set scale ranges from e.g. 0 - 100%, so values quite often can reach the limits of the scale. This issue would be solved by adding some padding to the min and max values of the scale ranges, but is there some setting that could be used to allow rendering over or to add some padding in pixels for the graphing area? Similar thing was discussed in issue #71.

If you require any additional information or data to help diagnose the problem, please let us know and we will be happy to provide it.

### Screenshot

![image](https://user-images.githubusercontent.com/3479118/225873995-9b8cd3b1-5cfe-4f90-86a0-8b27b9cd9636.png)

### CodePen:
https://codepen.io/markoole/pen/wvEXEXL
Green line is half the width in when reaching the top of the chart.

Thank you for your effort in maintaining and providing this library.

**Comment by leeoniya** [comment]
thanks for finding this and a clear repro!

so, there were a couple things going on here. one was the bug that's fixed in the attached commit. the other is that uPlot skips scanning data for limits when it detects you gave it a static scale range (same as auto: false). the easy work-around for this is to wrap it in a function:

```js
y: {
  range: () => [-12, 12],
},
```

i have some plans to split `scale.auto` into an additional `scale.scan` that can be used to control the limit-scanning behavior independently of actually determining the y scale range.

**Comment by leeoniya** [comment]
hmm, not sure i like the unconditional approach. the alternative is to always scan the data. there will still be edge cases there, for example if you have a bunch of values at 0 and one value at -1 and your scale min is 0.

![image](https://github.com/leeoniya/uPlot/assets/43234/f42357ca-99fd-40ce-9335-52f5d5ffe2b9)
