### ISSUE TITLE
valToPos calculation error when x scale distr = 2

### ISSUE THREAD

**Issue by zChanges** [leeoniya/uPlot#809]
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/16421725/226287783-8e4011d3-d2ef-41da-873b-77338f30ff29.png">
valToPos calculation error when x scale distr = 2, the reason why min max is not a timestamp,
How can I get the pixel position of the data point

<img width="486" alt="image" src="https://user-images.githubusercontent.com/16421725/226290701-7c178cc3-f9e1-47fe-a12b-f19fd417add6.png">

**Comment by leeoniya** [comment]
this is expected, but the design/goal of `distr: 2` should be more clear.

`distr: 2` is basically an index/ordinal scale, where every x datapoint is equidistant from each other. internally all x data is converted to indices, so `['a','b','foo']` becomes `[0,1,2]` and `[1679330065, 1679357829, 1679381234]` also becomes `[0,1,2]`. the original values are simply used for x tick labels. when `time: true` the labels are formatted using the built in time formatter, but the scale itself is not time, it's just numeric indices.

so for example, if you have this in timestamps: `[1 year ago, 1 hour ago, 1 second ago]`, and each of them is 100px apart, then half between 1 year ago and 1 hour ago would also have to be 100px apart (because every point is equidistant on a `distr: 2` scale.

for this to work as you're asking, you would need to pass the fractional _index_ to `valToPos()` and you will get back the correct position on the canvas between your datapoints, but what that position means in terms of your x labels is up to you to interpolate.

maybe a better description of `distr: 2` is that it's a labeled index scale with labels coming from your x data.

`distr: 2` is just a convenient way to do this, (but it allows you to pass the xLabels as part of your `data`):

https://jsfiddle.net/xk0t71zs/

```js
let xLabels = ['a', 'b', 'c', 'foobar'];

let data = [
  [0, 1, 2, 3], // x scale values
  [10, 50, 25, 100],
];

const opts = {
  width: 800,
  height: 400,
  scales: {
    x: {
      time: false,
    },
  },
  axes: [
    {
      incrs: [1],
      values: (u, splits) => xLabels,
    }
  ],
  series: [
    {
      value: (u, idx) => xLabels[idx],
    },
    {
      stroke: 'red',
    },
  ],
};

let u = new uPlot(opts, data, document.body);
```

when `scales.x.time: true`, the only thing that changes is the `values` callbacks start formatting the timestamps as date strings. everything else about `distr: 2` remains the same as above.

i hope that helps.

**Comment by zChanges** [comment]
Can solve my problem, explain very clearly, thank you very much

**Comment by Siim** [comment]
I had the same situation today, so I ended up constructing this easy function:

```typescript
const  toPosX = (x: number, u: uPlot) => {
  return u.valToPos(u.data[0].findIndex((k: number) => x === k ), 'x')
}
```

By doing so, you can keep `distr: 2`. Hope that helps someone in the future.
