### ISSUE TITLE
First of year not chosen as tick value

### ISSUE THREAD

**Issue by benmccann** [leeoniya/uPlot#81]
See an example here: http://plnkr.co/edit/nXxKPkb2nZtdj46RAMtP?p=preview

I'd expect Jan 2019 to be chosen as a tick value. I.e. choose the first date of each year and then fill in the values in between as necessary

**Comment by leeoniya** [comment]
`distr: 2` doesnt care about anything except for the index and number of elements. `time: true` still makes it use the date formatters, but what you're seeing is most likely not the starts of those months, but probably some random timestamp element that it landed on when it divided the scale range by a numeric integer divisor.

for this case you'd want to kill `distr: 2`, and if you wanted to reduce the tick granularity then you can increase `axis.space`.

if you next question is, how can this work with the "skip weekends" which relies on `distr: 2`, i don't have an answer at the moment.

**Comment by benmccann** [comment]
My computer screen just died, so unfortunately I'm stuck on mobile for the next few days until I get home :-(

Customizing `axis.ticks` does sound like the most performance way to do it. Why does tz and dst handling make things that much harder? Wouldn't I just need to adjust by some number of hours? I would probably use something like Luxon for that part since it would live in my own code and it should handle that for me. 

I'd be interested to try in a few days when I get back to a working computer. Any pointers on how I'd get started overriding `axis.ticks`?

**Comment by leeoniya** [comment]
> My computer screen just died

ring in 2020 with a new computer! 💻  

here's a simple x-axis ticks override which is derived strictly from the data which it scans for the 1st of any month and adds a tick. it does account for tz, but not dst shifts, though in your use case it probably doesnt matter since the date would not change (and with distr:2 the tick/grid spacing is even so there would not be a visible shift anyways).

http://plnkr.co/edit/XlSWQwFuNZ6P4MV4nQlN?p=preview

the missing ticks don't have timestamps in the data on the 1st dates of those months. also, the reason ticks has to be an array of indices is because `distr: 2`. for `distr: 1` the ticks array is one of timestamps.

the naive version has to create `data[0].length` number of date objects to run `.getDate()` on each. this can be optimized by just pre-calculating the month break timestamps in the given scale's range and testing against that.

**Comment by leeoniya** [comment]
@benmccann should i keep this open?

**Comment by benmccann** [comment]
Thanks so much for this!! I haven't gotten a chance to really dig into it yet, but I'll close for now to keep the issue tracker clean and let you know how it works or if I have any follow up questions. I really appreciate how responsive and helpful you've been to all my questions!
