### ISSUE TITLE
Latest dist version: Strange bug on plot click

### ISSUE THREAD

**Issue by danyalejandro** [leeoniya/uPlot#84]
To reproduce in Chrome: https://jsfiddle.net/m9bp4k68/
(the same happens on my data)

Click the plot; the mousemove interaction stops.

Zoom-in, Click, then double-click to zoom out a few times: click behavior stops working as expected.

Maybe the latest click event commits have something to do?

**Comment by leeoniya** [comment]
this isn't a bug, it's an intentional cursor lock which allows you to freeze the legend values and cursor position in case you need to move your mouse away from the plot. this is especially important for multiple synchronized plots, where you may want to hover some point and then scroll to another synced plot to see the values there.

i could maybe make it optional.

**Comment by danyalejandro** [comment]
oh, I see, makes sense now.

Yes, please make it optional, this is the first time I experience this functionality in any plotting lib and thus freaked out thinking it was a bug.

**Comment by leeoniya** [comment]
ok, this is now off by default. i think double-click to unzoom is enough mystery behavior by default. it can be enabled via `opts.cursor.lock: true`.
