### ISSUE TITLE
How to set background to dark mode ? 

### ISSUE THREAD

**Issue by ddublon** [leeoniya/uPlot#844]
Hi there! 

I need to make the background darker, like what you did here

![image](https://github.com/leeoniya/uPlot/assets/127298010/e2a3d489-9119-4918-95b8-b331472fe8ca)

but I have to use ReactJS in my project

I tried to find the right way to do so but didn't manage to succeed 

https://codesandbox.io/s/uplot-react-example-dark-background-c3cmml?file=/src/App.js This is my code sandbox experiment

![image](https://github.com/leeoniya/uPlot/assets/127298010/5cfa8fbb-936c-434e-bb58-e59bad16919a)

Thank you a lot in advanced!
Dolev

**Comment by dolev146** [comment]
Hey there,

I looked up previous issues https://github.com/leeoniya/uPlot/issues/780  and was able to make the background dark by wrapping the <UPlot /> element with a div with a dark background, but! the Axis color is black too so I can't see the numbers , how can I change that? 
![image](https://github.com/leeoniya/uPlot/assets/62290677/c238e6cd-d20d-46ee-ac84-19fc518b404b)


let me know what you think 👍

**Comment by dolev146** [comment]
I saw this issue https://github.com/leeoniya/uPlot/issues/561 

I think the example needs to be called dark mode or something like that so that it will be easy to find an example to dark mode

 thank you a lot 
![image](https://github.com/leeoniya/uPlot/assets/62290677/862d5471-0734-45e6-a1ee-16850407d060)

I just now need help with the 2 lines

**Comment by dolev146** [comment]
the green and purple lines are lines that when they move they make some filtration on the data in some way, is that kind of thing possible in muplot?

**Comment by leeoniya** [comment]
> is that kind of thing possible in muplot

it's not built in, but you can certainly do it. a basic example of drawing on canvas using the scales is https://leeoniya.github.io/uPlot/demos/trendlines.html

of course you can make it more complex with svg/dom drag handles, your own data filtering, etc.

**Comment by dolev146** [comment]
can you advise me on how to approach this kind of problem? 

I need the lines to be dragged and dropped 

how would you approach this? with the library? 

or build a div that will be on top of the graph and will always calculate what height the line is located?

**Comment by leeoniya** [comment]
if you need the lines to be draggable, then putting them in the DOM will be the easiest. just append them into the `.u.over` div and use `u.valToPos()` and/or `u.posToVal()` to look up the coordinates or scale values.

**Comment by dolev146** [comment]
i didn't use the approach you said because I needed the lines to be draggable, and now I have a different problem :) that I used absolute positions and now the lines move with the screen instead of being attached to the parent chart 👎 

I need help with this, I will make a reproducible example in a couple of hours, is there an example of what I am looking for already on the examples page?

**Comment by leeoniya** [comment]
> that I used absolute positions and now the lines move with the screen instead of being attached to the parent chart 👎

that doesnt make sense to me. i think you're doing sometbing wrong, but i can't tell you what.

> I will make a reproducible example in a couple of hours

okay, we can reopen once you do this.
