### ISSUE TITLE
uPlot chart draws numbers half of other libraries

### ISSUE THREAD

**Issue by benmccann** [leeoniya/uPlot#86]
These all go up to about 90 (I haven't checked the other libs):
* https://leeoniya.github.io/uPlot/bench/Flot.html
* https://leeoniya.github.io/uPlot/bench/dygraphs.html
* https://leeoniya.github.io/uPlot/bench/Chart.js-next.html

The uPlot one only goes up to about 45:
* https://leeoniya.github.io/uPlot/bench/uPlot.html

I'm wondering why / how uPlot truncates all the spikes and if this is a bug.

Also, one thing I'm curious about is that Chart.js tries to find the min / max y values to set the scale range before starting drawing. It does this more slowly than the entire chart rendering process for uPlot in the benchmark. Does uPlot also have to do this? I'm curious where the code for it is because I wonder how it can be so much more efficient

**Comment by leeoniya** [comment]
> These all go up to about 90...The uPlot one only goes up to about 45:

that's because i didn't bother figuring out how to group the series onto different y scales for any libs except for uPlot. uPlot's `mb` scale & axis do go to 90 (right side of chart), but its `%` scale & axis go to 45.

> Does uPlot also have to do this?

of course:

https://github.com/leeoniya/uPlot/blob/920ccf55377bff708c53eb19f08283aa4e89ff2c/src/Line.js#L465

**Comment by benmccann** [comment]
Ah, I didn't notice there were two y-axes! Thanks!

**Comment by leeoniya** [comment]
i recently dropped the `body {margin: 0}` style from all demos, so i think all the full-width charts are now partially off-screen. i'll reduce their widths.
