### ISSUE TITLE
hooks.setSeries

### ISSUE THREAD

**Issue by dingjunweibjkanyun** [leeoniya/uPlot#895]
If I have a mixed graph of columns and lines.I only want the lines to trigger hooks.setSeries when the mouse moves in the drawing area.Is there any way?
![image](https://github.com/leeoniya/uPlot/assets/135958780/23b53b09-4edc-4d4b-8477-21d9c131b139)

**Comment by leeoniya** [comment]
not currently, i wonder if this should be done similarly to the `cursor.dataIdx` api that lets you return `null` to short-circuit the focus. something like `opts.cursor.seriesIdx = (u, seriesIdx) => seriesIdx | null`.

https://github.com/leeoniya/uPlot/blob/378faf6fab9b84d86fd25a5b4425dc44d486b64d/demos/stack.js#L49

**Comment by dingjunweibjkanyun** [comment]
I understand. Thank you.

**Comment by leeoniya** [comment]
i think this should work for you: https://github.com/leeoniya/uPlot/commit/e5a9747585a8255269ce4a558c59e86db6fd761d

it exposes uPlot's internal y-distance measuring fn so you can customize it to return a custom distance that's bigger than `focus.prox` for whatever series you need, which will prevent focus.

https://github.com/leeoniya/uPlot/blob/e5a9747585a8255269ce4a558c59e86db6fd761d/demos/focus-cursor.html#L59-L66

turns out we needed this fn exposed in Grafana to give us control over the `setSeries` hook with custom pathBuilders, e.g. where the values represent a color scale and not cartesian y coordinates.
