### ISSUE TITLE
When the data is too large, such as exceeding 1.00e+16, the y-axis cannot render properly？

### ISSUE THREAD

**Issue by dingjunweibjkanyun** [leeoniya/uPlot#906]
<img width="1115" alt="image" src="https://github.com/leeoniya/uPlot/assets/135958780/edcee7f3-98d1-4c8f-bbd5-b03b701bd5d4">

**Comment by leeoniya** [comment]
yes, the axis does not have unlimited resolution and uPlot only pre-generates tick increments up to 1e16:

https://github.com/leeoniya/uPlot/blob/bef151e62a5947641b2ba7734ba062823b03af9e/src/opts.js#L50-L59

i'm not sure i want to change this limit since values at these magnitudes are much better divided to more human numbers and the tick formatting callback adjusted to append a suffix or power to the tick labels. if your units are in Petabytes, you can just append PB to 1.234 instead of returning raw values in bytes like 1234123123123123.

for example, in Grafana we've had no requests or bug reports of users needing additional magnitudes.

**Comment by leeoniya** [comment]
if you really need such huge raw values, you can supply your own tick increments using the `axis.incrs` option.

**Comment by dingjunweibjkanyun** [comment]
tks
