### ISSUE TITLE
1.6.28 broke plot zooming in mode 2

### ISSUE THREAD

**Issue by davidlougheed** [leeoniya/uPlot#914]
Hello,

Thanks for your work on uPlot. As of 1.6.28, I get an error when zooming just the x-axis of a plot in mode 2. The error occurs in the following line, because `wsc` is undefined: https://github.com/leeoniya/uPlot/blob/master/src/uPlot.js#L1263

Here is a fiddle demonstrating the error:

https://jsfiddle.net/3L7qx1tr/

**Comment by leeoniya** [comment]
oof, i knew this would bite me :sweat_smile:. those changes cut pretty deep.

https://github.com/leeoniya/uPlot/issues/902#issuecomment-1859519504

**Comment by leeoniya** [comment]
i probably should mention that for a dataset like this you don't need mode 2 :)

**Comment by leeoniya** [comment]
in the beginning, all of uplot's built-in pathbuilders expected an aligned / timeseries-like data structure, which requires ascending and non-repeating x values. that makes it fundamentally incompatible with rendering scatter plots that can have arbitrary points and ordering, and often no special meaning for the x axis, since you're just correlating two numeric dimensions. mode 2 was introduced to disable some internal timeseries data shape assumptions, auto scaling, and cursor internals. you can plug your own renderer for each series and DIY.

since then, i have updated the built-in pathbuilders to support the mode: 2 data shape. i'm not really sure that x-only zoom makes sense in mode 2 / scatter plots.
